<?php
	$selected = "pedagogy";
	require '../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../">Main</a></li>
	<li><a href="../pedagogy/">Pedagogy</a></li>
	<li>The Best of Times, The Worst of Times: Teaching With Computers in the Classroom</li>
</ul>
<h2>The Best of Times, The Worst of Times: Teaching With Computers in the Classroom</h2>
<p><cite>Prof. Thompson Webb III, Department of Geological Sciences</cite></p>
<p>What fun I had last semester using my laptop computer to teach students about the fossil record and the history of life on earth. In MacMillan 101, I would hook my laptop up to a projector and to the Internet and take off. In Powerpoint, I had new images to show the students, and I also had new websites to introduce them to. I was surprised a few times by finding their own webpages on course topics linked into my site and ready for their use in class presentations. Of course, to have one student superimpose my face on the body of an orangutan was a new lesson in human (ape?) evolution. Such were my experiences when all systems worked, and I was in the best of times. The contrast was the worst of times when parts of the system malfunctioned or were not available. I had much new to learn about my computer and the technology for presenting my images, and my operator errors sometimes added to the unexpected happening, such as the projector not being available or not operating as guaranteed. I was well into November before I could enter the classroom without a technical expert available and have full confidence that I could do what I wanted. Some of my worst problems seem unique to this year and my initial learning curve, but I know that from now on I will need a level of prior preparation and of technical help that I have never required when teaching in the past. Such are the challenges that we faculty face as we head into this amazing future.</p>
<h4 class="center">Initial Commitments and Worries</h4>
<p>When I committed to creating a webpage and adding this dimension to my already established and seemingly well working course Geology 31 (The Fossil Record), I was an internet neophyte without a laptop or experience in using Powerpoint. But I had an ace in the hole. A former TA for my course, Vicki McKenna, who was an Assistant Director at the Sheridan Center, was willing to help me use the Internet in redesigning some of the labs. Here I could introduce the Internet and a website for one part of my course, but not try to do everything at once. I would also have an experienced motivated guide to help me and my new TA to make the necessary transition and improvements. I had the summer in front of me and planned to attend a series of sessions run by the Sheridan Center to allow me to learn about designing a website and about the technology for doing it. So I ordered my laptop and settled in to see what would arise.</p>
<p>Change is both exhilarating--with its promise of new discoveries and learning--and scary. I was headed into new territory not in what I was teaching but in how I was to teach it. I was leaving the realm of the familiar and the realm of how I had been taught. What I had learned from my elders was not the full guide for my course nor did it tell me what the ethics of fair use are. I was also unfamiliar with the boundaryless cyberspace with its bulletin boards and hyperlinks. What was out there? Could I find reliable accurate information? Could I set up an attractive website without arousing the wrath or snide comments of my peers? What was it going to be like when I became so much more public with what and how I was teaching? In fact, the public nature of websites made me wonder at the exposure that I was giving Brown as well as myself. Would the amateur clumsily designed nature of my site show up Brown when a relative new comer at a community college had a slick well-working site?</p>
<p>I also worried some about pedagogy. Untrained in pedagogy, I had gradually perfected my teaching style to stimulate learning in students. That had taken 30 years with help from the Writing Fellows Program, Nancy Dunbar, and the Sheridan Center. Now I was moving into a new medium. What were the best ways to use it to stimulate learning? If I put all my course notes there, would anyone come to class? Would my valuable discretionary time be invaded by email queries from students? Here I would be using extra time in my already overloaded schedule to develop the website and then would it eat me up as students sought technical and other advice outside the scheduled classroom and office hours?</p>
<h4 class="center">Planning and Implementation</h4>
<p>Full of these concerns and with some curiosity, I went to the opening Sheridan session this summer on the use of the Internet in teaching. From that session, I learned that using Frontpage or an equivalent program was the way to set up my website. I also learned that some mysterious copyright issues might be out there. From the subsequent bag lunches, I learned that a password-protected website would get around the copyright issues and also allow me to control access to my site. I also figured out a rough overall design for my site that would allow me to keep updating it throughout the semester as I prepared for each class. That way I could combine my normal time and energy in preparing for class with constructing the webpage for each class topic. For the first few classes, I also chose topics that could rely on my research website, which I was simultaneously constructing this summer, and thus gave myself a little breathing room at the beginning of class. The discussions at the Sheridan Center helped me develop a plan of action before doing any detail work and carried me into August when my laptop finally arrived.</p>
<p>I had my research programmer, Phil Leduc, building my research website in Frontpage and was able to draw on his help and advice in setting up my course website. He loved exploring the new software and learning its bells and whistles and thus saved me much time and retraining. As has been my wont for 30 years of scholarly work, I let him handle technique, design, and details while I worked on content and objectives. I decided not to suddenly reinvent myself to do this new work. I could let him help me find a good customized background for my pages while I dealt with content. With somewhat different planning an undergraduate UTRA student might have helped me here, but I was glad to have the advice of a seasoned professional while my eyes were opening to all the new decisions and options that websites demand.</p>
<p>When the course started, my website consisted of a welcome statement and photo of myself on the first page along with links to pages with the syllabus, course goals, and class topics. On the class topics page, I had a list of all the class topics (e.g. ice ages, origin of life, etc.) that each linked to its own page, which I planned to build up, as the course progressed, with study questions and links to websites relevant to that topic. Each page for a class topic already had two key links on it as my textbook had a website with pages for each topic and the Museum of Paleontology at Berkeley had a fantastic website for the fossil record. I also included a few topics that I would not cover directly in class but that focused on prerequisite material, e.g. evolution and plate tectonics, that students could review as needed. (One geology concentrator thanked me for the evolution links and said she needed that review. It was there and ready when she was.) Ironically my new site had no pages for the lab, which had been my initial plan for development. My former TA, Vicki McKenna, had received a 2-year appointment at Michigan, and she left with my good wishes. Her departure forced me to let go of her advice for the labs, which was the Dumbo's feather that that had helped launch me into this new adventure, but by August, I had picked up too much momentum to crash. I also had a new TA from Rice who had designed webpages in some of her geology courses there, and she was willing to work with the students in designing webpages for some of their lab assignments.</p>
<p>For the beginning of classes, I just published publicly the welcoming page with the syllabus and goals and kept the full and growing site at a separate address known only to my students and myself. I never did sort out how to make the site password protected. That will come next year.</p>
<h4 class="center">The Best of Times: Class Preparation</h4>
<p>What fun I then had in preparing for class. I would sit down the night ahead at home with my laptop and bring up single webpages in the editor in Frontpage and hit the button to make them active in my web browser. I would click on a link to check on it and be out on the Internet. There I could download any pictures for later use in Powerpoint, and I could explore new websites relevant to the topic. Both the Berkeley site and the textbook sites had plenty of links. Because I was starting with discriminating experienced sites, I was mostly linking to other reliable sites. I found that I was a good editor here. I knew what I wanted to teach and I knew my material, so I could navigate the web with a critical eye and choose the websites for my webpages that I wanted my students to see. I also found other course websites that were also a source of good new links. Once I had used command C to copy a new web address, I would return to the page in Frontpage and add the link with appropriate prose to describe it. After saving the new version of the page in Frontpage, I would find this new version active within my web browser where I could check it out and proceed to new sites. I found that I had fun building the class topics pages each week and could work on two or three at once as the Internet led me to jump among topics. I could follow my surfing with my editing. I often could work down to close class time and then, with the help of my programmer webmaster, I could publish the new pages to be ready for use in class. I was also able to be using Powerpoint in parallel to being on the net and to build up some amazing Powerpoint presentations for class. Here I had access to the museums of world for pictures of fossils. I also could download photos and figures from the websites of colleagues and other experts. I was in a wonderland of fossils and had color images of what I had only verbally described in class before. It really powered me up to come into class with all this new material at my fingertips. These were the best of times.</p>
<h4 class="center">The Worst of Times: Technical Difficulties</h4>
<p>But it was in the classroom that reality struck. I had many new tricks to learn in order for all the new technology to work smoothly. First I needed a departmental technician, Bill Collins, to show me how to configure my computer so that I could project the images in the classroom. Next I needed to learn how to configure it to go out on the net. Here I needed a new address since I was signing on from MacMillan Hall and not my office. That took time, so I missed going out on the net during the first week of classes, but I did show Powerpoint images. I then had to miss a class because of a meeting and when I returned to class, I found the projector had been moved to another classroom to meet the needs of other professors. Fine, but no one had told me, and my whole class was planned around use of Powerpoint and my newly acquired ability to go out on the net. I was floored for the few minutes before class, but I shifted to my old overheads and class discussion. By the next class, Bill had found me an old projector that I could use until a new one would arrive. But this old projector required a whole new protocol and was often out of synch with my newer faster machine. It would also only show part of my computer screen. I spent the rest of September and all of October battling with the old projector and ate up plenty of Bill's time in solving the incompatibility problems. These were the worst of times. In all my years of teaching, I had never had problems like those that arose when the machines would go dead in the middle of class. Sometimes I forgot the new protocols and sometimes the machines became ornery. Luckily my class was tolerant and supporting of what I was trying to do. I also had my old overheads along, but that meant that the class experienced some sudden unplanned shifts in my presentations.</p>
<h4 class="center">The Best of Times: Student Involvement</h4>
<p>Still the best of times could reemerge to keep me going. One day I had to go to a Sheridan Center lunch on teaching technology just before class. I knew that I would have to run back just before class, so with a little trepidation I hid my $2500 laptop in a cabinet in the classroom and went off to lunch. When I came back just before class and projected that day's webpage about dinosaurs on the screen, I discovered a new link that had not been there when I had published the page at noon. The student who was making a 10-minute presentation that day had found my webmaster over the lunch hour, and they had added her page, the first completed by a student in the course, to mine. It was exciting for everyone in the class to watch her use her page with animated images. She was excited and her effort prompted several more webpages to accompany presentations before the class ended. Here students were following my model and going one better in incorporating pictures within their pages. I loved watching them learn and show off new skills even when my face appeared on an orangutan. Luckily I had better control of the projector when this work came forward in the class. So I was back to the best of times.</p>
<h4 class="center">Conclusions and Recommendations</h4>
<p>What can I conclude from this new adventure in teaching? Plenty.</p>
<ol>
	<li>We need leadership and vision for what we should be trying to accomplish in using the new teaching technology. How best can we use it to induce student learning? We need to get that right before we start worrying about how to save time or to sell our products. Inspired student learning is a horse that will pull many carts. How do we breed that horse out of the available stock of our vast experience as educators?</li>
	<li>How does Brown want to present itself to the outside world in terms of websites? Is it going to be each professor, course, department, program for itself or is there some way for us all to cooperate in achieving a &quot;web presence&quot; that might match our reputation?</li>
	<li>We need plenty of support to get this job done right. What are the key types of equipment, software, and technical support that will empower us to move forward efficiently? How can we prevent the classroom disasters that I experienced and also make it easy to design, revise, and publish websites for both our students and us?</li>
	<li>We also need to have a continuous set of seminars to help us wake up to new developments in technology and all that it will enable. What is just around the corner? How can we best design our courses and curricula now to take advantage of what is coming? Experience with the new technology has taught us that change is accelerating. So how do we create new patterns of work and course development to adapt to this rapidity of change without killing ourselves? Overwork is not an option; everyone is already overworking.</li>
	<li>We need time and rewards for doing this new work and exploring this new territory. This work is an add-on to our current teaching and advising work. We are going to have to let some things go if we are to retool for this new way of teaching. Where are the incentives to encourage us to let go and grow? Only from the death of old things can the new be born. But that transformation requires some nurturing and stewardship.</li>
	<li>For myself, I found plenty of rewards in being able to tap into all the work many of my colleagues had done. There are some magnificent websites out there--some done by interested laypersons and others by teachers at junior colleges. The love of knowledge is alive and well outside of universities as well as inside, and it is inspiring to find that. What a source of energy to tap into. A course website can be one way to show students what lifelong learning can lead to.</li>
	<li>We have a critical opportunity to redefine teaching. What a burden that we place on ourselves in trying to be the main source of knowledge in a course, which forces us to lecture. How can we offload some or all of that burden onto the web and then redefine ourselves as guides, coaches, and co-learners. To me that has been a liberating vision.</li>
	<li>With information spelled out on the web, we create memory in the system. Former students can return to websites in future years to refresh their knowledge and also to contribute knowledge or useful comments. With data readily available on the net, we can formulate more challenging problems for our students to solve in our courses.</li>
	<li>I want to explore the use of bulletin boards and other means of group communication. Tom Banchoff has that central to his courses. I want to add this new dimension to my course next year. It is another way to tap the energy and knowledge of the students. Ever since I opened my course to having students make short presentations in each class, I have been astounded at the learning that this task can induce in students. How might the public representation of knowledge on a webpage induce similar displays of learning and critical analysis?
	<li>In creating links to prerequisite material for my course, I see an opportunity for us to join forces in creating interlinked websites that define bodies of knowledge well beyond the individual courses. We can begin to think of defining curricula this way. What if we put the knowledge out there in this form and then allow students to choose different pathways to and through the knowledge and learning? How will this arrangement enhance our cooperation with colleagues at other institutions? We may have a new mechanism for creating inter-institutional interdisciplinary programs.</li>
	<li>But to create some of the above networks of knowledge, we will need to rethink the ownership of knowledge, data, graphics, animation, and prose. Who is leading those discussions? Will we keep the access to knowledge open on the web in our courses?</li>
	<li>I love the sense of how differently we can practice our profession with this new technology. Our accumulated expertise in each of our disciplines will allow us to shape knowledge and create understanding as never before. Will we?</li>
</ol>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../footer.php';
?>
