<?php
	$selected = "pedagogy";
	require '../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../">Main</a></li>
	<li><a href="../pedagogy/">Pedagogy</a></li>
	<li>Lessons from Consumerism: A Note for Faculty Thinking About Technology</li>
</ul>
<h2>Lessons from Consumerism: A Note for Faculty Thinking About Technology</h2>
<div>

									<p class="bodynoindent"><i>Roger B. Blumberg</i></p>
									<p class="bodynoindent"><i>Department of Computer Science &amp; Sheridan Center for Teaching and Learning</i></p>
								</div>
								<div align="left">
									<blockquote>
										<p class="bodynoindent"><a name="ret1"></a>&quot;The worship of the idea of technology involves a decline in the value of all other ideas.&quot;<a href="#fn2"><sup>1</sup></a> - Octavio Paz</p>

									</blockquote>
								</div>
								<div align="left">
									<p class="bodystyle"><a name="ret2"></a>Twenty years ago, in his report to the Carnegie Council, David Riesman discussed the promises and perils of the rise of student consumerism in American higher education. Reading On Higher Education today, one is reminded of the degree to which student consumerism was valued as a means toward a variety of educational ends, rather than as a desireable (or undesireable) educational end in itself. Whether as a method of resistance to the verbal virtuosity that some students found oppressive in faculty-dominated seminar settings, often identified with the Hutchins-era University of Chicago, or as a spur to new approaches to curriculum, like the &quot;Modes of Inquiry&quot; courses proposed by Brown undergraduate Ira Magaziner as part of his plan for a more meaningful curriculum, the rise of student consumer power was thought to make possible, in the best case, learning experiences that would be superior as judged by traditional standards of intellectual authority and educational worth.<sup><a href="#fn2">2</a></sup></p>
									<p class="bodystyle">In the years since Riesman's report appeared, what has changed most significantly is not the degree of student consumerism in postsecondary education, which seems to have risen apace, but rather the ways this consumerism is explained or justified. Increasingly, the consumerist attitude on the part of American undergraduates, and now at all levels of schooling in the US, is regarded as a worthwhile end in itself, or at least as something longer in need of a particular kind of educational justification.</p>
									<p class="bodystyle">At Brown, for example, it is common to find curricular innovations (e.g. the &quot;values&quot; initiative) strongly prefaced by an assurance that no courses will be required, regardless of how worthwhile the faculty or administration believe them to be. Similarly, one often hears of undergraduates' annoyance when they feel their freedom of choice has been compromised (e.g. by changes in departmental offerings after pre-registration) without regard to whether the results of this compromise might be judged academically equivalent or even superior by the faculty. Such examples -- clearer perhaps at Brown than elsewhere, but certainly not unique to Brown -- reveal the degree to which student choice has replaced and subsumed the ends to which it was previously a means.</p>

									<p class="bodystyle"><a name="ret3"></a>An interesting if digressive question is whether the change in the status of student consumerism has been due primarily to consumerism having become itself an unassailable form of justification, in all matters including education; or to the force of earlier ideas of intellectual authority and educational worth having been argued away effectively or made obsolete by changes in the traditional role of the university.<sup><a href="#fn3">3</a></sup> How did it come to pass, for example, that whereas thirty years ago the thought of a television news anchorman writing a history of World War II, or of the 20th Century, or indeed of any war or any century, and having that book displayed in college bookstores alongside the works of scholars, was genuinely laughable, last year two such books appeared and their authors lectured widely at US universities? Does Tom Brokaw really have scholarly authority that Chet Huntley didn't, or have our ideas concerning intellectual authority, its establishment and justification, undergone a dramatic change?</p>
									<p class="bodystyle"><a name="ret4"></a>A similar change is that, whereas the worries expressed by Riesman in 1980 about the spread of &quot;Learning at a Distance&quot; programs concerned how such programs could receive appropriate academic accreditation from professional associations, today the worries of those interested in distance-learning programs are as likely as not to consider the demands of the potential consumer exclusively. &quot;A lot of adults want a graduate education, but the system is just not presenting it in a way which meets their lifestyle needs,&quot; says Michael Gaffney, the CEO of Ottawa-based Learnsoft Corp., using language that sounds disturbingly like parody.<sup><a href="#fn4">4</a></sup> Learnsoft is the parent company of Unexeus University (<a href="http://www.unexus.com">www.unexeus.com</a>), which hopes to be the first private degree-granting Internet university.</p>

									<p class="bodystyle">Whatever the cause of our changing views of student consumerism or intellectual authority, thinking about Riesman's book today is a worthwhile exercise for teachers who worry about how both enthusiasm and neglect can allow decidedly worthwhile educational means to become questionable, or at least less clearly worthwhile, educational ends. For anyone thinking about the use of computers in education such a worry is especially understandable, both because no one wishes that all education become merely computer education and because the proliferation of computers in everyday life has made us aware of the non-neutral (i.e. not merely instrumental) character of computer technologies. In the case of college and university teachers, for whom access to computers is increasingly not the circumstance that most limits their use, this worry is both understandable and urgent, as the sophistication required to sensibly resist and manage the technology is often as great as that required to put it to good use.</p>
									<p class="bodystyle"><a name="ret5"></a>In his article &quot;Computers at School?&quot;, first published in 1986, the philosopher of education Israel Scheffler pointed out that the property of being an educational technology is not something given in the idea of the computer, but rather something that comes through the uses and purposes to which the computers are put. &quot;There is,&quot; he wrote, &quot;no necessity that compels an advancing technology to be mirrored in school offerings, nothing fated about it.&quot;<sup><a href="#fn5">5</a></sup> Scheffler discussed the then fashionable justifications of the use of computers in school, both as a means and an end: as a means to enhanced and enriched learning of traditional subjects, and the development of more advanced cognitive skills; and as an end in itself as preparation for a computerized world and/or a computerized world of work.</p>
									<p class="bodystyle"><a name="ret6"></a>Scheffler was critical of the idea that using computers in school was a worthwhile end in itself, noting that even if we think familiarity and facility with computers extremely worthwhile it doesn't follow that schools (especially those identified with education in the liberal arts) are the appropriate places to carry out the training. For postsecondary school teachers, one might argue that today there is even less in a justification of the use of computers in classrooms that appeals to the computerized world and workplace. First, because our students have grown up with computers and often have (and are likely to always have) greater facility with them as educational and workplace technologies than we. Second, and more importantly, even if we believe that our mission includes preparation for the workplace, it is unclear what sorts of facility and familiarity with computers are appropriate and valueable enough to merit our devoting class time to them. Finally, when we examine economic trends over the last decade (and not merely the last few years of technology stock boom and Y2K preparation), it is unclear that we are doing our students any long-term economic favors by teaching them to use or program the hardware and software we have on campus today.<sup><a href="#fn6">6</a></sup></p>

									<p class="bodystyle">But recognizing the importance of separating technological means from educational ends does not insure that the two will be easily or forever separable. In the field of educational research, which suffers from a formidabe hype/evidence ratio in the area of educational technology, nearly all the success stories reveal a complex relationship between means and ends, a relationship that changes with time. Perhaps the best example has come from the introduction and widespread use of graphing calculators and compuer algebra systems (CASs) in the teaching of both secondary and postsecondary school mathematics over the past ten years.</p>
									<p class="bodystyle"><a name="ret7"></a>The use of calculators like the TI-82 and programs like Derive, Maple and Mathematica have allowed undergraduate mathematics, and especially calculus, to be taught and learned in experimental and computational as well as traditional axiomatic ways. The widespread use of these technologies (with the blessing of the major professional mathematics organizations concerned with education) has resulted in important changes in both the US undergraduate, and secondary school Advanced Placement calculus curriculum. The computer has made possible not only the visualization of mathematical structures in new ways, and allowed programming skills to be integrated seamlessly into the study of mathematics, but has resulted in families of problems once reserved for professional research becoming accessible to undergraduate study. Just as important has been the way the use of the computer has significantly transformed the range of exercises now considered worthwhile in the study of calculus.<a href="#fn7"><sup>7</sup></a> Finally, the new technologies have encouraged the sharing of programs and instructional materials in both secondary and postsecondary calculus education, and have contributed to the coherence not only of the calculus-teaching profession but of the community of students who study the subject. In short, the use of these technologies fulfilled the promises that many have claimed for the use of computers in education: an enriched curriculum; the improvement of problem-solving skills through the use of more diverse and sophisticated problems/materials; improved opportunities for collaboration between students and teachers on substantive, purposeful work; clearer connections between student work and professional research; and greater versatility in the methods for teaching and learning a traditional subject.</p>
									<p class="bodystyle"><a name="ret8"></a>In the context of the previous discussion, however, the calculator/CAS story is also noteworthy for the degree to which means and ends have become inseparable. Some teachers, especially in higher education, believe that emphasizing experimental and computational aspects of mathematics is misleading, and confuses students about the difference between doing mathematics and programming computers.<a href="#fn8"><sup>8</sup></a> Similarly, in the process of learning to use the computer programs effectively many students spend less time thinking about the nature of mathematical knowledge and proof, not to mention the techniques for solving problems and manipulating mathematical structures that were common before the introduction of powerful personal computers.</p>
									<p class="bodystyle">To its credit, the College Board has been careful to preserve sections of the AP exam for which students may not use graphing calculators, and, of course, mathematics-major tracks of college calculus routinely involve proof and emphasize non-computational methods. If the use of the computer has indeed changed the sorts of problems and exercises young students will find intellectually stimulating, there remains a strong constituency of mathematicians and mathematics educators anxious to make sure that a rich understanding of mathematics remains the end and computers remain simply a powerful means to that end.</p>

									<p class="bodystyle">What, then, have we learned about means and ends in our thinking about the use of computers in education, aside from the always useful but hardly revalatory: &quot;Be Careful!&quot;? First, that being clear about our educational ends is difficult but necessary if we are to assess whether/how the computer may serve as a suitable means. Second, if as teachers we find ourselves justifying the use of computers as an end in itself, we have probably lost sight of or become foggy about those ends. Third, we will need to evaluate and perhaps redescribe our ends over time, whether our use of computers is successful or not, and we probably need a professional community of some sort to assess and refine what we're doing (and what we think we are doing) with any new technology.</p>
									<p class="bodystyle">Finally, we need to recognize that while there may be something special about the idea of technology, in the sense Octavio Paz speaks of it in the quotation at the start of this essay, the special qualities are probably shared by a number of seductive and powerful ideas. Substitute &quot;consumerism&quot; for &quot;technology&quot; and I believe the quotation would lose none of its truth. That the most successful uses of computers in higher education have come in courses, like calculus, where there is a strong technology-independent curriculum and a large number of veteran teachers with different persuasive arguments concerning what should count as positive change, is no surprise. The more clear and compelling our educational ends, and the more people concerned with pursuing them, the easier it will be to plan, implement and evaluate effective uses of computers at school.</p>
									<p class="bodynoindent">---</p>

									<p class="bodynoindent"><a name="fn1"></a><sup>1</sup>Octvavio Paz. &quot;Satiety and Nausea,&quot; in Alternating Current, translated from the Spanish by Helen Lane. (Arcade Publishing, 1990), p. 160. Paz' Corriente Alterna was published in 1967.  <a href="#ret2">return</a></p>
									<p class="bodynoindent"><a name="fn2"></a><sup>2</sup> David Riesman. On Higher Education: The Academic Enterprise in an Era of Rising Student Consumerism. (Jossey-Bass Publishers, 1980). The difficulties with the Hutchins model are discussed on pages 27ff. The fate of the &quot;Modes of Inquiry&quot; courses is mentioned along with Magaziner's promising proposals on page 275.  <a href="#ret2">return</a></p>

									<p class="bodynoindent"><a name="fn3"></a><sup>3</sup> For a compelling argument concerning the changing role of the university see Bill Readings' The University in Ruins (Harvard University Press, 1996).  <a href="#ret3">return</a></p>
									<p class="bodynoindent"><a name="fn4"></a><sup>4</sup> &quot;Canadian Firm to Open Internet University,&quot; by Susan Taylor. Reuters, November 14, 1999.  <a href="#ret4">return</a></p>
									<p class="bodynoindent"><a name="fn5"></a><sup>5</sup> Israel Scheffler. &quot;Computers at School?&quot; Teachers College Record 87, no. 4 (1986), pp. 513-528. Reprinted in Scheffler, In Praise of the Cognitive Emotions (Routledge, 1991) pp. 80-96. The quotation is from the reprinted version, p. 82.  <a href="#ret5">return</a></p>

									<p class="bodynoindent"><a name="fn6"></a><sup>6</sup> For statistics on the declining wages of white-collar and technical workers in the early 90s, see <br>
										Lester Thurow's The Future of Capitalism (William Morrow and Co., 1996) and Robert Heilbroner's Visions of the Future (Oxford University Press, 1995).  <a href="#ret6">return</a></p>
									<p class="bodynoindent"><a name="fn7"></a><sup>7</sup> Perhaps the most dramatic illustration of the change is revealed in the latest AP Caclulus exams, part of which require that students use a graphing calculator. For an example, see question 5 of the 1998 Free Response Questions at the College Board's AP Calculus site (<a href="http://www.collegeboard.org/ap/calculus/">www.collegeboard.org/ap/calculus/</a>).  <a href="#ret7">return</a></p>

									<p class="bodynoindent"><a name="fn8"></a><sup>8</sup> Some teachers of mathematics and natural science also worry that by further emphasizing technical skills, rather than critical thinking (for example), they do little service to either their students or their discipline. For an example of this sort of anxiety, see Claudia H. Deutsch, &quot;The Digital Brain Drain: So Many Computers, So Little Interest in Hard Science,&quot; The New York Times, September 2, 1999.  <a href="#ret8">return</a></p>

</div>
<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../footer.php';
?>
