<?php
	$selected = "pedagogy";
	require '../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../">Main</a></li>
	<li><a href="../pedagogy/">Pedagogy</a></li>
	<li>Faculty Use of an Instructional Management System</li>
</ul>
<h2>Faculty Use of an Instructional Management System</h2>
<div>

									<p class="bodynoindent"><i>Caroline A. Hazen<br>

											CIS / WAIG, Academic Technology Consultant</i></p>
								</div>
								<div align="left">
									<p class="bodystyle">Three years ago, CIS contributed to Brown's use of instructional technology by distributing software and providing clusters, computing classrooms, and the multi-media lab, course folders for document sharing, and email and newsgroups for communication. Specialized projects, like the Landow webs, received assistance from the Scholarly Technology Group. Support for instructional technology was the primary responsibility of only two CIS staff members. This level of CIS investment matched the level of campus interest: even two years ago there was little discussion on campus about the application of computing to teaching and learning.</p>
									<p class="bodystyle">Most of the new developments came from 'vanguard' faculty finding their own way to make use of the web in their teaching. In some cases these were individuals, comfortable with computers, who acquired the knowledge of html and graphics needed to develop their own web sites; in others, student assistants created the course sites, which often could not be maintained beyond the semester of their creation. To support other faculty who wanted to publish course information to the web, in the spring of 1997 CIS developed &quot;Course Publisher&quot;, an easy-to-use tool for the creation and administration of class web pages and for access to instructional support services.</p>
									<p class="bodystyle">Technology, particularly that used by Instructional Management Systems (IMS), has improved dramatically over the past few years and, more importantly, the level of campus interest in using technology in teaching has risen. It is important for all of us to reconsider Brown's goals and needs in this area. To this end, the CIS Web and Instructional Applications Group (WIAG) has begun to gather data on other schools and products, as well as pay close attention to the ongoing discussions in the technology community about IMS standards and ask for feedback from faculty members who are using our current systems.</p>

									<p class="bodystyle">This article will describe briefly how faculty might use an Instructional Management System and how CIS is presently meeting those needs. Then it will discuss the various models being used by other schools and what we see as their strengths and weaknesses. Finally it will explain what we hope to do next and what sorts of feedback we would like from the Brown community as a whole before these important decisions can be made.</p>
									<p class="headerstyle">An Instructional Management System</p>
									<p class="bodystyle">An IMS is a product or group of products, usually web-based, that work together to allow faculty to perform a variety of tasks, from publishing course material to tracking students' grades, in an integrated environment. An IMS has three basic uses: 1) for information distribution, 2) for discussion and collaboration, and 3) for student assessment and tracking. At the present time, CIS's offerings fall mostly in the first category.</p>
									<p class="bodystyle">1) <i>Information distribution</i> in an IMS includes: producing an online version of a traditional syllabus, which can help to ease course shopping and advising; creating an easily updated and accessed electronic site for course announcements; posting assignments in a central location; and distributing course materials, including text, sounds, images, and movies. Course Publisher allows faculty to achieve most of these goals, and this service is widely used at Brown, with 95 courses published using this tool for the fall '99 semester, more than doubling from the 45 of the previous semester.</p>
									<p class="bodystyle">2) <i>Discussion and collaboration</i> through an IMS can take the form of <i>asynchronous</i> discussion, such as a newsgroup, an e-mail list, or a web-based bulletin board; <i>synchronous</i> discussion, such as live online chat; or document sharing through communal file server space that is accessible to students and faculty members. CIS currently offers course newsgroups, which are integrated into Course Publisher, as well as common file server space.</p>

									<p class="bodystyle">3) <i>Student assessment and tracking</i> consists of tools that allow faculty to evaluate the students' understanding of the course material and to view how the students are using the online component of the course. Faculty can employ quizzes and exams administered over the web to see how well their students are picking up new concepts. Most IMS products allow instructors to post grades for viewing by individual students. At present, Brown does not have central support for such services, though some departments and members of the faculty have implemented similar tools on their own.</p>
									<p class="headerstyle">IMS Products</p>
									<p class="bodystyle">Commercial IMS products and the solutions that other schools have implemented follow four basic models: 1) commercial integrated, 2) commercial semi-integrated, 3) homegrown, and 4) piecemeal. At this point, no school is using only one system, and the boundaries between the models are perhaps somewhat artificial, but this division can help to delineate the different approaches to adopting an Instructional Management System.</p>
									<p class="bodystyle">1) A commercial integrated product, such as &quot;Blackboard Campus&quot;, is an overarching package that links in with or indeed replaces existing administrative systems (such as that in the Registrar's office) and creates a single, monolithic system in which faculty and students can store, retrieve, and use course and university information through a single interface that can include the ability to chat, to use a web-based discussion, to turn in or modify documents, to create an electronic grade book, and to search for course reserves. UCLA, for example, uses such a system for student registration and indeed teaches some classes entirely online. Such a system would require tight integration of many segments of the diverse systems used on campus, which would potentially change current work practices, and its output is perhaps best suited to schools where online courses and distance learning are high priorities.</p>

									<p class="bodystyle">2) A commercial semi-integrated system is similar to the previous category except that it stands more on its own and doesn't require integration with other departments. Similarly to the commercial integrated option, the semi-integrated system allows for students and faculty to access and to store information through a single interface that has a variety of capabilities already built into the package by its designers. Schools like Cornell, Duke, and Berkeley have chosen this type of solution by offering &quot;Blackboard CourseInfo&quot; on their campuses.</p>
									<p class="bodystyle">3) The homegrown system, like Brown's &quot;Course Publisher&quot;, is a tool or group of tools that were created from scratch by a team from the university. Harvard and Yale also are using homegrown tools, which have the obvious strength of being entirely under the control of the university and thus being able to be adapted to the specific needs of the campus. The only limitation is the amount of time that the programmers are able to spend coding, which is certainly less time than the teams working on a commercial package. Though homegrown systems come in varying levels of complexity and functionality, a homegrown system like ours can link up to other university resources, such as the way that we connect to BOCA and the library catalogue through Course Publisher, and can create a standard output and central location to store course information.</p>
									<p class="bodystyle">4) The piecemeal approach to publishing course materials is prevalent among universities but is not necessarily supported as such; people on campuses including Columbia, Dartmouth, and Stanford seem to be using whichever tools they like best to put up their information in whatever format they prefer. There are also many professors at Brown who create their own pages from scratch using their own tools. Although such an approach certainly allows for greater flexibility on the part of the page designers, it does not create a universal, well-designed output nor does it give Brown any easy way to support such a wide array of tools.</p>
									<p class="headerstyle">What is Best for Brown?</p>

									<p class="bodystyle">As we surveyed other institutions, it became clear that most schools are in a similar position to ours; we're all looking around and trying to find the best solution for our unique environment. Any of these systems will require CIS's resources and support, but not all of them will meet the needs of the Brown community, particularly as the market seems to be driven by the requirements of universities focused on large lecture-type classes and distance learning. WIAG, therefore, is setting out to gather as much information as possible from the Brown community at large. We have received some extremely helpful responses from the faculty members who have responded to our online surveys about Course Publisher, but we have only just begun to collect feedback. Over the next months as we evaluate our various technological options, we expect to go out and speak to various committees and groups of faculty, students, and staff to get as full a picture as possible of Brown's needs and desires before we make our choice.</p>

</div>
<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../footer.php';
?>
