<?php
	$selected = "pedagogy";
	require '../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../">Main</a></li>
	<li><a href="../pedagogy/">Pedagogy</a></li>
	<li>Teaching to Variation in Learning</li>
</ul>
<h2>Teaching to Variation in Learning</h2>
<div>

									<p class="bodynoindent"><i>Brian Hayden, Ph.D.</i></p>

							<div align="center">
									<p class="headerstyle"><font size="+1">Contents</font></p>
								</div>
								<div align="left">
									<p class="bodynoindent"><a href="#intro">Introduction</a><br>
										<a href="#learning">Learning</a><br>
									</p>
									<blockquote>

										<p class="bodynoindent"><a href="#how-learn">How Do We Learn?<br>
											</a><a href="#fund-cog-proc">Fundamentals of the Cognitive Process<br>
											</a></p>
									</blockquote>
									<p class="bodynoindent"><a href="#strategies">Strategies for Teaching<br>
										</a></p>
									<blockquote>

										<p class="bodynoindent"><a href="#receptive-strat">Strategies for the Receptive Function<br>
											</a><a href="#learning-strat">Strategies for the Learning and Memory Function<br>
											</a><a href="#cognitive-strat">Strategies for the Cognition and Thinking Function<br>
											</a><a href="#expressive-strat">Strategies for the Expressive Function<br>
											</a><a href="#personal-strat">Strategies for the Personality Function<br>
											</a></p>

									</blockquote>
									<p class="bodynoindent"><a href="#conclusion">Conclusion</a></p>
									<p class="bodynoindent"></p>
								</div>
								<div align="center">
									<p class="headerstyle" style="font-size:14pt"><a name="intro"></a>Introduction</p>
								</div>
								<div align="left">

									<p class="bodystyle">Learning is part of everyday life. Typically the process of acquiring knowledge in an educational context involves two key elements: one (the educator) who actively imparts knowledge and two (the student) who actively gains knowledge. Each of these elements is equally essential for learning to be successful. The success is earned mutually for both the educator giving the knowledge and the student gaining the knowledge. In educating students we hope to engage their minds and passions. The educator must consider what he has to give and how he hopes to increase the student's knowledge. The true goal is not only that the student gains new information, but also that the student weaves this information into his life so that it gives added nuances to his way of experiencing the world. For the student, the key is how she acquires information and what she might do to make this information part of her experience.</p>
									<p class="bodystyle">We all learn differently. There are a host of ways to present information and even more ways to demonstrate what has been learned. This variability in how we learn and how we show what we have learned may have dramatic effects. The way an educator presents information and evaluates knowledge may facilitate one student's learning, may impede the apparent learning of another student, and may impair a well intentioned student's efforts to learn.</p>
								</div>
								<div align="center">
									<p class="bodystyle"><a href="#top">top</a></p>
									<p class="headerstyle" style="font-size:14pt"><a name="learning"></a>Learning</p>
									<p class="bodynoindent"><a name="how-learn"></a><b>How Do We Learn?</b></p>

								</div>
								<div align="left">
									<p class="bodystyle">Our focus as educators is on teaching a specific content. We rarely try to remember or even take into account how we learn. This kind of ignorance blinds us. What is worse, if we are not vigilant, we assume two things:</p>
									<ul>
										<li class="bodynoindent">someone else automatically can learn what we have learned, and
										<li class="bodynoindent">someone else can take in, or process, the information in the same way as we have. In effect, as teachers we unwittingly wear blinders that mar our best intentions. We fail to notice the variation in how our students learn so we fail to teach with them in mind.
									</ul>
									<p class="bodynoindent"><b>A FABLE</b></p>
									<p class="bodystyle">An enterprising merchant who lived near the border of two Kingdoms was stopped everyday as he wheeled a wheelbarrow full of straw across the border. One customs officer could not resist thinking that the merchant was smuggling something across the border. But as many times as he searched through the straw, he found nothing. Years later he left his duties. The merchant, an old man now, no longer crossed the border. Still questioning, the retired customs officer went to the old man's hut and said &quot;We are old men now. Before one of us dies do tell me what it was you were smuggling all those years.&quot; After a long pause, the merchant said, &quot;Wheelbarrows.&quot;</p>

									<p class="bodystyle">There, right under his nose, were wheelbarrows of all colors, materials, and shapes but he never paused to notice them as the critical feature. Similarly educators may fail to notice certain critical features of learning: what is involved in learning and how varied the learning process can be. Like the customs officer who did not 'see' the wheelbarrows, we tend not to 'see' the differences and genuine variation in how students learn. As George Orwell wrote, &quot;To see what is in front of one's nose needs a constant struggle.&quot;</p>
									<p class="bodystyle">To both the teacher and her students the unnoticed wheelbarrows symbolize the variations in how each of us learns or more accurately how each of us processes and acquires information. This information is stored in memory sometimes having been transformed, that is, augmented by effective teaching. For example, if the D&uuml;rer etching &quot;Adam and Eve&quot; stored as visual memory is paired with the semantic label and description of &quot;Early Northern European Renaissance,&quot; then it may be recalled, or retrieved, from memory and may be expressed in a prescribed way (i.e. on an exam), typically to be evaluated by an educator.</p>
									<p class="bodystyle">There are a variety of ways in how we process and acquire new information. These differences within learning can effect</p>

									<ul>
										<li class="bodynoindent">whether or not a person learns what we are teaching,
										<li class="bodynoindent">whether or not she will be able to retrieve from memory what has been learned,
										<li class="bodynoindent">whether or not the format of evaluation favors his own particular variation within learning.
									</ul>
									<p class="bodystyle">A simple example may enliven this observation. Two brothers are poised to repair the carburetors of their cars. Both brothers love to read. One begins by searching the glove compartment for the car's manual and reads how the carburetor is constructed, how to disconnect it, how to clean the filter, while the other brother already has the hood up and is fiddling with the bolts and filter. Both were successful in repairing the carburetor. Yet how they learned was very different. In effect, the brothers embody two variations in learning. One favors the logical, analytical, sequential, word-based acquisition of knowledge prior to implementation; the other favors an action (or motoric) based acquisition and implementation of &quot;trial and error&quot; knowledge.</p>
									<p class="bodystyle">Within this broad spectrum of learning are Brown University undergraduates. All of them exhibit variation in learning. We must create ways to engage and involve as many students on this spectrum of cognitive diversity as possible. How we teach them may alter their apparent effectiveness in mastering what is taught and how we ask them to demonstrate their knowledge of the course's subject matter may determine how they perform on tests, term papers, discussion sections, and class presentations. These learning differences will effect the student whether the course content is Archeology, Physics, or Urban Studies. Similarly this variation in learning impacts on how a student may perform on tests. For instance whether the test is made up of multiple choice questions, definitions, matching of concepts, class demonstrations, short essay, take home questions, or the evaluative procedure is a term paper with a fixed deadline in the future may effect a student's performance. If we fail to understand and appreciate learning differences in students, as educators we will not reach some students who otherwise might be eager to learn if taught within a different presentation style, different thinking emphasis, different testing format. Our teaching improves with the appreciation that these learning differences or variations in learning effect a student's mastery of course content. By being more sensitive to the types of diversity that educators encounter, we will be better able to evaluate our successes and failures.</p>
								</div>

								<div align="center">
									<p class="bodystyle"><a href="#top">top</a></p>
									<p class="bodynoindent"><a name="fund-cog-proc"></a><b>Fundamentals of the Cognitive Process</b></p>
								</div>
								<div align="left">
									<p class="bodystyle">One way to recognize the types of learning differences or variations within learning is to review the distinct intellectual functions involved in processing information. In doing so, we can underscore where variations may occur, and thus where educators may teach to those differences rather than ineffectively teach at cross purposes to those differences.</p>
									<p class="bodystyle">The intellectual functions are as follows:</p>

									<ul>
										<li class="bodynoindent">The receptive function or sensory modality through which one acquires, processes, classifies information. That is, the incoming information could be something heard, held, seen, smelled, tasted, or some combination of these sensory modalities.
										<li class="bodynoindent">The learning and memory function or the way this information is organized and then stored in memory. Often there is a direct link between reception (something tasted) and how that information is retrieved from memory (memory is accessed in multiple ways but the original mode of sensory input may determine speed, extent, and effectiveness of recall). For instance, if my early experiences with a childhood friend is eating slices of carrot cake, as an adult years later, I may find myself flooded with memories of that childhood friend only after a taste of carrot cake (having neither seen my long ago childhood friend or having tasted carrot cake for years).
										<li class="bodynoindent">The cognitive and thinking function or the various mental activities used in the organization and reorganization of information. One could be required to calculate with numbers, to think of as many uses for a pot holder, to extrapolate from one historical event to another, to make judgments of works of art, to plan a vacation.
										<li class="bodynoindent">The expressive function or the various ways in which one can express the information recalled. One can say it, write it, draw it, enact it, each of which allows one to demonstrate what was learned.
										<li class="bodynoindent">The personality function or those factors which effect what we notice. For instance, does a student have the attention span to take in all of the lecture or can she attend to only brief but frequent segments of the lecture, does her concept of time (e.g., focus on the present) allow for meeting deadlines (e.g., where the focus is on the future), is she persistent, what kinds of study habits has she developed, is she from a culture which stresses practical abilities and competencies or a culture stressing verbal skills?
									</ul>
									<p class="bodystyle">Each of these functions are interwoven as we process information. By segmenting the processing of information we can pinpoint some of the variation in learning, locate where variation effects learning, and understand how teaching to differences can enrich teachers' and students' appreciation of content.</p>
									<p class="bodynoindent"><b>RECEPTIVE FUNCTION</b></p>
									<p class="bodystyle">The receptive function may seem unimportant, but it, in fact, can make quite a difference in teaching. Recall the two aspiring mechanics - one favored reading the visual word, the other favored the visual-spatial 'hands on' fiddling with bolts, parts, and filter. Some students favor</p>

									<p class="bodystyle">seeing; others favor hearing (the words organized by the speaker); others favor holding or manipulating something. Whenever possible it is preferable to teach to (or convey information to) at least two receptive functions or modalities. Example: structure a lecture so that information is presented variously (i.e., simultaneously visually and auditorily or visually and motorically or auditorily and motorically or visually and motorically.) Not every course content or lecture presentation or lab or discussion section allows for more than one mode of presentation, but just providing some variation in presentation alone allows more students on the spectrum of learning differences to become engaged in the learning process. Simply stated, some students prefer to see the information and others may prefer to hear the information. If taught to that preference, individual students will process the information more effectively.</p>
									<p class="bodynoindent"><b>LEARNING AND MEMORY FUNCTION</b></p>
									<p class="bodystyle">The learning and memory function is a pivotal function. What information eventually is stored in memory, as well as how accessible that information is, will be determined by how effectively organized that information was (both by the student and teacher). How a teacher organizes the presentation of information and how a student organizes the information received can affect dramatically how one gains access to or retrieves from memory what was previously organized.</p>
									<p class="bodystyle">What is stored in memory can be thought of in the various receptive modalities: word, sight, sound, touch, smell, and taste. Consider a &quot;memory&quot; of CAT. I may hear the word c-a-t, and as I recognize the word, the existing memory file includes all sorts of information about small, four legged, bewhiskered, long-tailed animals with sharp claws, potentially making sounds of purring. The various attributes of cat interconnected within the memory file can be accessed or information can be retrieved in a variety of ways. So if I am asked to describe a cat, the visual image of cat, the semantic meaning of cat, the auditory and tactile sensation of cat, even the smell of kitty litter allow me to provide the answer. If I am asked to tell what a cat is, I can. If I am asked to look at a picture of a cat and detect what physical detail has been omitted, I can. If I hear a recording of a noise, I can determine that it is a purring cat. Each of the sensory modalities allow access to the stored memory of cat. In effect, the more varied the input modalities have been, the greater the likelihood that any type of query can access the stored information and one can retrieve from memory what was learned. Considering my stored knowledge of cat, an educator could test me in any of the following ways. I could be asked to write (or state) a brief description of a cat. I could be asked to draw a cat. I could be presented with photographs of four legged mammals and be asked to select the one of a cat. I could be presented with an incomplete rendering of a cat and be asked to complete it or state what part is missing. I could be asked to choose a purring cat among recordings of animal noises.</p>
									<p class="bodystyle">Organizational aids can greatly assist what is learned, how it is stored, and how it is retrieved. As noted above a student may prefer processing information as either heard or seen. As an example, two students - one who prefers to hear information and one who prefers to see information may leave a lecture hall having processed the information very differently. The teacher presented on the overhead projector very clear, well organized transparencies but simultaneously gave a rambling lecture. The former student may leave the lecture hall confused whereas the latter has a well organized set of newly learned ideas. The teacher deserves credit for providing information in two receptive modalities: simultaneous auditory and visual information.</p>

									<p class="bodystyle">Our rambling teacher could have provided, in addition, some other organizational aids. These could include a handout of an outline (to offset the rambling lecture), writing key concepts on the blackboard, projecting transparencies of definitions or even an actual flow chart of the key concepts or themes simultaneous with the lecture. These aids are particularly successful because the teacher is providing students in advance with organizing principals (or how to group information about to be seen or heard). Then students are more likely to notice the material and will have a pre-established way of thinking about the upcoming information.</p>
									<p class="bodystyle">Another organizational aid is the use of metaphor. Metaphors have powerful heuristic value; they are elegant short cuts. A metaphor is a cognitive instrument which links some known aspect to a new and yet unrealized aspect. Metaphors are tools for grasping and suggesting connections. Implicitly a metaphor suggests that two apparently unrelated things, in fact, share something in common. Considered in this way metaphors transport meaning from one context to another context. The paths of transport are the parallels, commonalities, and even paradoxical similarities between the two aspects and contexts. Thus, they often provide an element of novelty or incongruity yet must give a concrete image to an abstraction. Sometimes they even provide an emotionally charged awareness and vividness to one's understanding.</p>
									<p class="bodystyle">Earlier in the brochure the fable of the unnoticed relevance of wheelbarrows was linked to how we often fail to notice what is relevant under our noses: how we learn and the variation in learning. The customs officer failed to notice the relevance of the old merchant's wheelbarrows. For some readers the concrete image of the wheelbarrow immediately provided a curious link between what they knew of learning and the unrealized aspects about to be presented. The image, for some, triggered a way to organize or group the information about to be read and processed. For other readers, the concrete image of a wheelbarrow may not yet have helped organize the new information until they read this paragraph. At various points in the learning process a metaphor can be a guidepost or reference which crystallizes a concept into a succinct image or grouping with a new or richer or more integrated meaning.</p>
									<p class="bodystyle">Conceptually similar to the metaphor is the organizational aid of using a quotation. A lecturer stressing the profound impact and importance of childhood could incorporate the line from a Wordsworth poem &quot;the child is the father of the man.&quot; At first perhaps, the sentence might elude the listener. Gradually, and at differing rates of comprehension and appreciation, students will process or notice information as grouped under certain categories: child, adult, childhood influences. The quote provides the teacher with an organizational aid and simultaneously her aid becomes the student's own uniquely interpreted organizational aid. The quote provides an interwoven thread of consistency. Information given earlier in the lecture may be reorganized as the organizational aid gains meaning or usefulness. During the hours of summarizing testimony in the Simpson trial Johnny Cochran repeatedly said &quot;If the gloves don't fit, you must acquit.&quot; He deftly used an organizational aid to restructure previous information on O. J. Simpson to fit his purpose.</p>

									<p class="bodystyle">Students have to develop organizational aids as well. These strategies will ensure organization and memory storage of material presented. Such strategies are designed to make and keep the information in their mind salient. That is, the aids ensure that students notice what is under their noses and the students develop links among relevant concepts or information. Most &quot;studying&quot; is helping the student to organize and store information. It is the active rehearsal and (re)organizing of information. Strategies many students use include: underlining concepts, definitions, key names and dates as well as taking notes as they read or writing chapter outlines. Their best strategy is to develop a 'master plan' for integrating information - a personal strategy according to their learning preferences for using strategies. With such a plan their various efforts are meaningfully orchestrated toward successful learning.</p>
									<p class="bodystyle">An exercise in memory may illustrate the point of how organization is a central feature in teaching. Imagine that you are to hear a list of letters read aloud to you and you are to write them down after the last letter is read: TWAIBMMCIATTBA.</p>
									<p class="bodystyle">Most people simply can not remember all fifteen letters. If, however, an organizational rule is given: &quot;The beginning three letters and last two letters are the acronyms of two world wide air lines and the letters in between are the acronyms of three major computer telecommunication companies,&quot; and then the letters are read aloud, now you would more likely remember all of the letters because what you would 'hear' are groups of letters: TWA IBM MCI ATT BA.</p>
									<p class="bodynoindent"><b>COGNITION AND THINKING FUNCTION</b></p>

									<p class="bodystyle">We are ready to discuss the function within the learning process that most people equate with learning: the cognition and thinking function. The learner may be required to engage in a variety of mental activities including computation, reasoning, making judgments, developing concepts, abstracting and generalizing, ordering or sequencing, organizing, planning. The unit or element involved in these mental activities could be words, numbers, works of art, actions, as well as one based in one or more expressive modalities (oral: spoken; motor: written, stated, drawn, acted on). Some of these mental activities could be viewed as quite concrete or basic and some could be viewed as more abstract or of a higher order of thinking. The mathematical computation involved in balancing one's check book would be considered a relatively concrete level of thinking; whereas the mathematical computation involved in proving a Euclidian theorem would be a more abstract level of thinking.</p>
									<p class="bodystyle">One significant learning difference has to do with a variation in thinking. A useful distinction to make is between two types of thinking. Naturally thinking is a process, but as a process its flow can be characterized in two different ways. One is a sequential or linear process of thinking. Incremental bits of information are assembled into a unit of understanding. A kind of mental convergence has occurred. The earlier presentation of the separate components (reception, memory, and learning, cognition and thinking, expression, personality) of the intellectual functions engaged the process of linear thinking. The aspiring mechanic who first read the car manual before fixing the carburetor was thinking in a linear way. Once the 'unit' of intellectual function is grasped one can now dissemble and reassemble the 'bits' of information.</p>
									<p class="bodystyle">But a different type of thinking process exists. Some educational tasks require it and some students prefer it to linear thinking. It is called the simultaneous or nonlinear process of thinking. This type of thinking involves 'seeing' the whole picture, a creative simultaneity wherein thoughts diverge (rather than converge). The other brother who simply began fiddling with the carburetor was thinking in a nonlinear way. When asked the open ended question &quot;How has Watergate affected American Politics?&quot; or asked &quot;What uses of a screwdriver can you come up with?&quot;, in answering the person is using nonlinear thinking. If asked &quot;Give the three major influences of Watergate on American politics&quot; or &quot;Define screwdriver,&quot; then the answer requires the use of linear thinking.</p>

									<p class="bodystyle">The discussion of metaphors pertains to both the degree of abstractness of the ideas and types of thinking. The metaphor of &quot;wheelbarrow&quot; employed earlier involved taking a concrete concept (wheelbarrow) and manipulating that concept with a highly abstract mental operation (extrapolating or generalizing). To 'capture' the essence of what the metaphor meant, that is, to transport the relevance of the unnoticed wheelbarrow in the context of the tale to the unnoticed variation in the context of learning one must use nonlinear thinking. If the metaphor was successful as an organizational aid it was because nonlinear or divergent paths of thinking transported the concrete mental image into an abstraction and in doing so emotionally charged a new awareness.</p>
									<p class="bodystyle">It might be useful to pause and to consider if the reader has a preference for (or difficulty with) linear or nonlinear process of thinking. Many unwittingly do. This could determine how one prepares a class presentation, how it is presented, how one evaluates students (what type of exam questions, term paper topics). Similarly a student who struggles when asked in class an open ended question (nonlinear thinking) may excel on the highly specific types of exam questions (linear thinking). The seeming disparity in that student's performance in class is more clearly understood when the academic performances are considered in terms of what type of thinking the student is employing.</p>
									<p class="bodynoindent"><b>EXPRESSIVE FUNCTION</b></p>
									<p class="bodystyle">In all of this discussion, we have yet to focus on the expressive function or how the learner conveys the information: he can speak it, write it, draw it, role play or enact it in some way. Just as some students prefer a visual presentation (vs. auditory) of information, and prefer to engage in nonlinear (vs. linear) thinking, other students prefer to express their ideas in writing rather than in spoken form. For instance, one student may appear awkward and wooden in discussion section but hand in an eloquently developed term paper, or a student may excel in discussion section but hand in a sketchy, poorly worded and weakly developed term paper. These preferences are unrelated to intelligence. Rather the issue is variation in processing information. People simply learn in different ways. The intellectual functions contain the inherent possible variation in learning which results in differing qualitative performances. Depending on how we teach to those possible diversities, some students may produce better results than others.</p>
									<p class="bodynoindent"><b>PERSONALITY FUNCTION</b></p>

									<p class="bodystyle">Since students have personalities as well, we must consider the personality function or those attributes which affect their learning. One broadly defined attribute involves attention. Some students have excellent powers of concentration which enable them to attend fastidiously to a lecture, to their reading, to a class discussion. Some students (as many as fifteen percent) have deficient powers of concentration. They may fidget, are easily distracted (by their own thoughts, or more commonly by extraneous distractions - a cough, someone arriving to class late, a siren of a passing ambulance outside the building), cannot follow directions (they are distracted mid-sentence), are forgetful (they are distracted while thinking about what to do next). They are sometimes mislabeled as 'lazy.'</p>
									<p class="bodystyle">Another broadly defined attribute is motivation. We have a broad range of motivations, some of which can interfere with learning, some of which facilitate learning. One motivation that impedes learning is fear of failure - &quot;I am scared of failing so I avoid doing certain things.&quot; Another impeding motivation is fear of success - &quot;I won't succeed because then everyone will expect so much of me.&quot; There is another motivation with contradictory results: need for affiliation. &quot;I really want this teacher to like me.&quot; Sometimes this need to affiliate with others motivates one to stay focused on the academic task. But a student could become more focused on being personally pleasing rather than acknowledging the teacher with outstanding academic accomplishments in class. Naturally some motivations enliven the student. These include the desire to master and the desire to excel. Students so motivated may be a joy to teach. The above noted variation in learning may, nevertheless, impact their motivational desires to master or to excel.</p>
									<p class="bodystyle">In addition to attentional and motivational attributes, the issues of culture, ethnicity, and race highlight that every learner comes from a context that shapes and defines how he perceives the world. Our culture defines values which influence motivations which in turn influence learning. One student may come from a culture which emphasizes the value of verbal skills, another may come from a culture which emphasizes practical skills and practical competencies. The former student may readily learn about Existential Philosophy, the latter may not be drawn into the discussion.</p>

									<p class="bodystyle">Our sense of time dramatically effects how we meet academic deadlines. Every culture, ethnic group, and race shapes its own perception of time. The focus may be on the relevance of the past, one's heritage. Everything viewed through the muted lens of the past gives the present and future meaning only as it relates to promoting the purpose, meaning, and tradition of the past. Another focus may be on the present: the moment is essential. Planning ahead may be difficult, so deadlines are experienced as not terribly important; until of course when the future deadline is now. Yet another time perspective allows one to focus on the future. This perspective is ideal in the American educational system. One's view of the world is through a time lens which highlights the future: what in the present will promote the future. Planning ahead is the most natural given. Students with this sense of time will readily meet deadlines, plan ahead (whether it is homework, the next chapter, going to section the day of an athletic event), and study. Where there is the future, plans are already being devised. But if one's time perspective is different (the time lens exaggerates the past or present), woe be that student's every effort to scramble to some semblance of success based on a concept of futurity.</p>
								</div>
								<div align="center">
									<p class="bodystyle"><a href="#top">top</a></p>
									<p class="headerstyle" style="font-size:14pt"><a name="strategies"></a>Strategies for Teaching</p>
								</div>
								<div align="left">

									<p class="bodystyle">It is not the task of any teacher to diagnose learning differences. A teacher's obligation is to be sensitive to the potential variation in learning amongst any group of students (undergraduate and graduate). It need not be a daunting task. But the task does challenge a teacher to </p>
									<ul>
										<li class="bodynoindent">think about her presentation style, her preference in one or both types of thinking (linear and nonlinear), and her preferred format of evaluation or testing; as well as
										<li class="bodynoindent">consider how she decides to teach to the spectrum of variation in learning.
									</ul>
									<p class="bodystyle">Variation in learning occurs within each of the five intellectual functions. Strategies to teach to this spectrum become avenues to enliven the teaching process and to ensure that more students learn.</p>
								</div>
								<div align="center">
									<p class="bodynoindent"><a name="receptive-strat"></a><b>Strategies for the Receptive Function</b></p>

								</div>
								<div align="left">
									<p class="bodystyle">Simultaneous presentation in two sensory modalities is important. The most common coupling of modalities in a college setting is the auditory and visual modalities. One's spoken word parallels a simultaneously projected slide or transparency. Yet other coupling of modalities (i.e., auditory and motoric) might better accommodate some course material (i.e., a visual art course). The issue is to vary the 'input' so that what is acquired and then stored in memory is accessible by more than one memory trigger. As noted earlier there are some individuals who simply prefer or favor either a visual or auditory processing of information as well as some individuals who prefer or favor either semantic labels (words) or a visual-spatial configuration. Equally valuable is the consideration of what to present visually. A teacher could state a definition (words auditorily presented) and simultaneously project on a screen transparency (words visually presented) of that identically worded definition. This may suffice on occasion.</p>
									<p class="bodystyle">Perhaps a more effective device is to alter the presentation of the actual visual information in accordance to the learner's visual preference. Consider the brother who immediately opened the car's hood and began fiddling with the carburetor bolts and filter favored a visual, spatial, and action based acquisition of information. Were he attending Basic Auto Mechanics, he would hear and understand the instructor's stated definition perfectly well. He might learn more effectively (and so recall it better later) and certainly be more engaged in what he was learning if he had some different but relevant visual information simultaneously presented (for instance a diagram of the interior of a carburetor, a cartoon from the Los Angeles Times of Donald Duck fixing a car, an illustration by David Macaulay of how the parts of a carburetor fit together). In other words, some different visual information emphasizing a visual and spatial format while de-emphasizing the semantic labels or words which the instructor already was emphasizing in the auditory presentation.)</p>
									<p class="bodystyle">Not only would such a visual presentation engage the brother with his visual preference, but everyone in Basic Auto Mechanics might enjoy and be more engaged in the presentation with this additional feature.</p>
								</div>
								<div align="center">

									<p class="bodystyle"><a href="#top">top</a></p>
									<p class="bodynoindent"><a name="learning-strat"></a><b>Strategies for the Learning and Memory Function</b></p>
								</div>
								<div align="left">
									<p class="bodystyle">The focus within this function is to</p>
									<ul>
										<li class="bodynoindent">reinforce what is to be learned,
										<li class="bodynoindent">foster it being stored in memory, and
										<li class="bodynoindent">provide sufficient organizational aids so as to access or retrieve from memory what was learned.
									</ul>

									<p class="bodystyle">This function is the key to engaging the mind and passion of a student. We need concise, compelling, intriguingly presented information which grabs attention by its force and unanticipated relevancy. Repetition, allowing for questions, providing thematic links between presentation (lecture/ lab/section), and allowing for feedback all reinforce what is learned.</p>
									<p class="bodystyle">Regardless of the actual content, some degree of repetition or reiteration is needed. Pacing the presentation of information is a serious consideration for every educator. This consideration requires careful thought. Part of how we pace the presentation is when we repeat information. Repetition of a central phrase, quotation, or visual device often focuses attention, as well as reinforces what is learned. Repetition (in moderation) allows, for rehearsal of information, essential for students' eventual storage and retrieval from memory.</p>
									<p class="bodystyle">Allowing for questions at junction points between a transition to a new concept or new material or new unit is helpful. Some questions will be relevant, others non-relevant or even farfetched. But the questions are indicators of how students are beginning to integrate (or have failed to) the material into meaningful systems of knowledge. Questions, too, are reflections of the successfulness of our teaching effort. From the questions, the educator can determine what needs to be repeated, or reinforced, modified, enlivened, or when to proceed with her presentation.</p>
									<p class="bodystyle">Another strategy to reinforce what is learned is the creation of thematic linkages between the previous lecture/lab/section and the present one. By doing so the educator triggers memory of the last presented information which then is the remembered context into which new information will become interwoven. The linkages could be the use of metaphor(s), central phrase(s), quotation(s), visual device(s), a reference to a current event (on campus, in the state, or country or world or universe) used to reinforce last week's lecture/lab/section. An educator might even repeat a question posed but not answered (which if answered it would have increased too rapidly the pacing of information, essential for students' eventual storage and retrieval from memory.</p>
									<p class="bodystyle">Allowing for questions at junction points between a transition to a new concept or new material or new unit is helpful. Some questions will be relevant, others non-relevant or even farfetched. But the questions are indicators of how students are beginning to integrate (or have failed to) the material into meaningful systems of knowledge. Questions, too, are reflections of the successfulness of our teaching effort. From the questions, the educator can determine what needs to be repeated, or reinforced, modified, enlivened, or when to proceed with her presentation.</p>
									<p class="bodystyle">Another strategy to reinforce what is learned is the creation of thematic linkages between the previous lecture/lab/section and the present one. By doing so the educator triggers memory of the last presented information which then is the remembered context into which new information will become interwoven. The linkages could be the use of metaphor(s), central phrase(s), quotation(s), visual device(s), a reference to a current event (on campus, in the state, or country or world or universe) used to reinforce last week's lecture/lab/section. An educator might even repeat a question posed but not answered (which if answered it would have increased too rapidly the pacing of information) in the last lecture, and then answer it in today's presentation. In a sense, a course can be envisioned as an architectural structure, each presentation (lecture/lab/section) is a building block reinforcing every element of the overall structure. References to various 'blocks' of the evolving structure is one way to reinforce what is learned and to help broaden the context of the remembered, and anticipated, information. By referring to some aspect of last week's presentation or some aspect taught weeks ago or to some aspect to be taught in two weeks makes today's presentation more relevant. Linking past, present, and future knowledge creates continuity and relevance to what is learned.</p>

									<p class="bodystyle">Another way to make a presentation relevant is to ask for feedback. Even if the question is 'Does this make sense?' The query provides the educator with essential information of his success thus far. More importantly, the question instills in the student the sense that he, as a learner, matters to the educator. The willingness for feedback (lectures, sections, tests, textbooks) also underscores that educator and student together are essential for learning to be successful. That success hinges on the educator's sensitivity to potential variation in learning as well as using that sensitivity to vary presentation format, vary sensory modalities, vary the repetition devices. Such variations in how an educator attempts to teach may increase her success in teaching to students' variation in learning.</p>
									<p class="bodystyle">As mentioned earlier, organizational aids provide ways of organizing information, anticipating new information and restructuring pre-existing information. Outlines serve as flow charts, providing key phrases, explicit sequencing of ideas, implicit organization or relationships amongst ideas. The outline could be a handout, written on the blackboard, projected from a transparency (all visual and semantic inputs). Other organizational aids might include use of metaphors, quotations (literary, contemporary musical lyrics, famous historic persons), key phrases, summaries or overviews; cartoons or illustrations. Any one of these aids could be stated or written (as a handout, on the blackboard, on a transparency) or pictorially presented (on a transparency, on a handout). In a sense, these aids are devices to help students think about what they are learning. If we provide ways to think about or organize information, then our students are more likely to learn what it is we are teaching them. Learning is discovery, but vital clues will ensure the discovery.</p>
									<p class="bodystyle">There is enormous variation in how students transform information into relevant (to them), meaningful (to them), concise (to them) units of knowledge stored in memory. The transformations are determined by which of the sensory modalities (auditory, visual, motoric) a student may favor, by the students preference in storing pictorial or semantic units of information, and by the students preferred types of thinking (linear, nonlinear). Educators should vary the organizational aids and type of thinking used in their own presentations or in the questions posed in class or the types of exercises used in lecture/lab/section.</p>
									<p class="bodystyle">Teaching to the spectrum of variation includes accessing information with variety. That is, vary the evaluation or testing format. Points to consider are the</p>
								</div>
								<ul>
									<div align="left">

										<li class="bodynoindent">type of thinking (linear, non-linear) required in answering test items
										<li class="bodynoindent">type of questions (such as recall vs. recognition). Some students prefer either linear or non-linear thinking. Some students prefer multiple choice questions, others abhor them. Some students have difficulty expressing their ideas in writing, but excel in class discussions. Variations in testing formats might include definitions, matching of concepts, multiple choice questions, short answer, fill in the blank, essay questions, class presentation, term paper, three dimensional models. Many of these formats involve differing ways to access memory. A multiple choice question or matching concepts provides the answer in the question so one is, in effect, measuring recognition. Whereas questions requiring writing out an answer requires recall of knowledge. Since we use organizational aids to help students' structure and store knowledge, whenever possible we should make reference to those aids in actual test questions. In doing so we promote retrieval of what has been learned.
									</div>
								</ul>
								<div align="center">
									<ul>
										<p class="bodystyle"><a href="#top">top</a></p>
									</ul>
									<p class="bodynoindent"><a name="cognitive-strat"></a><b>Strategies for Cognition and Thinking Function</b></p>

								</div>
								<div align="left">
									<p class="bodystyle">The educator and learner are required to use mental activities, involving specific units or elements in one type of thinking process (linear, nonlinear). The mental activities may include reasoning, making judgments, developing concepts, abstracting, generalizing, sequencing, organizing, planning. As for the units or elements involved in many of these mental activities they could be words numbers, actions, works of art. Finally one uses one or both types of thinking (linear, non-linear) to sequence a series of words or make a judgment about a work of art.</p>
									<p class="bodystyle">Imagine the different styles of the presentation &quot;The Carburetor&quot; in Basic Auto Mechanics by the two brothers described earlier. The brother who first read the car manual most likely would be inclined to give an oral presentation, provide a handout of an outline with clear definitions of terms and carburetor parts, and give an exam question such as &quot;Describe how to change a carburetor.&quot; He has selected the mental activities of reasoning and sequencing, generalizing, and planning of words in a linear process of thinking to present important information and for his students to demonstrate their knowledge. Whereas his brother most likely would have a demonstration car in place, hood open, tools laid out, and engage his students with a visual, spatial, action based acquisition of information. He might have available pictorial depictions of carburetor parts. And his final exam question might well be fixing an actual carburetor. This brother has selected the mental activities of reasoning, developing concepts, sequencing, organizing, and planning of words, images, and actions in both a linear and non-linear process of thinking. These examples represent two different ways to present information and to evaluate knowledge. The ramifications in teaching, however, can be enormous when teaching to variation in learning.</p>
									<p class="bodystyle">As educators we need to pay attention to our own preferences in mental activities, in units or elements involved in each of these activities, and in the type of thinking required.</p>

									<p class="bodystyle">In an earlier section on strategies the idea of obtaining feedback was stressed. Here, too, is when feedback can highlight to us where our preferences, as well as choices yield varying degrees of success in how we provide information and how our students gain knowledge.</p>
								</div>
								<div align="center">
									<p class="bodystyle"><a href="#top">top</a></p>
									<p class="bodynoindent"><a name="expressive-strat"></a><b>Strategies for Expressive Function</b></p>
								</div>
								<div align="left">

									<p class="bodystyle">The idea of varying the format in which students can express their knowledge already has been discussed. But it is important to note that some students excel at one type of organization. Some excel at organizing their ideas in an oral format while others excel at organizing their ideas in a written format. While the unit of mental activity involved in organizing ideas is the same (words), the part of the brain organizing words into an oral version differs from the part of the brain which renders words into a written form. So there can be significant differences among students in each of these organizational activities in terms of expressing what is learned. One student might excel in both; one student may excel in only one and appear surprisingly ill prepared in the other. This variation has little to do with motivation, intelligence, or preparedness. The broad spectrum of learning includes many surprises.</p>
								</div>
								<div align="center">
									<p class="bodystyle"><a href="#top">top</a></p>
									<p class="bodynoindent"><a name="personal-strat"></a><b>Strategies for the Personality Function</b></p>
								</div>
								<div align="left">

									<p class="bodystyle">Perhaps the most elusive and thus the most difficult function to deal with are those factors which we educators have the least direct knowledge of regarding any student: attention, motivation, cultural values and expectations, time management. Sensitivity to these issues should be interwoven into an educator's way of both thinking and doing such that any student feeling overwhelmed or not learning successfully will readily seek his teacher's advice. Having openly sought feedback in class, as well as having encouraged students to meet with and talk to their teacher will facilitate a student's likelihood of seeking out an educator in times of difficulty. In discovering how an individual student learns, the educator may be able to resolve her temporary impasse to successful learning.</p>
									<p class="bodystyle">Other issues may need to be explored. These include the ability to concentrate, motivation, and cultural values. As discussed earlier, students vary in their ability to concentrate. For some it may be a matter of considering</p>
									<ul>
										<li class="bodynoindent">where it is best to study (dorm or library) or
										<li class="bodynoindent">when (during the day or night), or
										<li class="bodynoindent">with whom (finding a more conducive study mate).
									</ul>
									<p class="bodystyle">A student who is distracted by classroom noise may be offered a quiet office in which to be tested. Some forms of motivation impede performance: fear of failure, fear of success, need to be pleasing and to be liked, or anxiety when tested. Each of these can be explored. Finally, some cultural values and expectations may interfere with a student's success. For instance, if one's cultural value is to acquire practical skills, a course emphasizing theoretical issues may have little seeming relevance. A dialogue between educator and learner would permit the learner to re-examine the original assumption that a theoretical issue has no practical impact. And the educator may learn from this dialogue a new way to make his subject matter relevant. Another culturally based experience is the subjective experience of time. More practically stated, some students have to explore their conceptualization (or lack of) of time management. Some remedies are: untimed exams, periodic updates of work progress, planned time extension, a check off sheet included in a syllabus.</p>
									<p class="bodystyle">Some students may remain overwhelmed or lack success. There may be a genuine need for the educator to suggest professional support: motivational problems may require counseling or specific behavioral remedies; cultural values and expectations may be best addressed by the educator seeking out information and a more sensitive understanding.</p>

									<p class="bodystyle">The broad spectrum of learning includes all that has been mentioned. At the extreme is a heterogeneous group of disorders. These include Dyslexia (a language processing disability), Dysnomia (difficulty in recalling names or words), Dyscalculia (a problem with math), Attention Deficit Disorder (problems in concentration, impulsivity, and in understanding social cues). Professional support is essential for a student with such a disorder. Having one (or more) of these learning differences does not mean a student is lazy or stupid or brain damaged or has a bizarre psychiatric disorder. Simply, the learner with his educators must develop special strategies to handle the processing and organizational needs of daily life (academic, social, personal).</p>
								</div>
								<div align="center">
									<p class="bodystyle"><a href="#top">top</a></p>
									<p class="headerstyle" style="font-size:14pt"><a name="conclusion"></a>Conclusion</p>
								</div>
								<div align="left">

									<p class="bodystyle">Within this spectrum of enormous complexity and variation in how we process and acquire information there is a student who can and will learn if effectively taught. That individual can be drawn into the experience of learning. An educator's use of creativity and originality can help in this process. Successful teaching requires, on the part of the educator, an appreciation and consideration of how she learns and therefore of how she may present material. It is essential that every educator create for himself a personally relevant format and conceptualization of teaching which is effective but diversified and teaches to not at cross purposes to variation in learning.</p>
								</div>
								<div align="center">
									<p class="bodystyle"><a href="#top">top</a></p>
								</div>

</div>
<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../footer.php';
?>
