<?php
	$selected = "society";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Society</a></li>
	<li><a href="../">Medieval Sex and Sexuality</a></li>
	<li>Fornication and Adultery</li>
</ul>
<div class="image_right">
	<img src="../images/infidelitas.jpg" width="208" height="493" />
</div>
<h2>Fornication and Adultery</h2>
<h3>Fornication</h3>
<p>Although forced to accept <a href="sex-spouses.php">sex between married couples</a> as legitimate and even useful (for procreation), the church urged a suppression of <a href="sexual-desire.php">sexual desire</a> in favor of spirituality, which was considered to be man's true vocation in life. Celibacy and virginity were exalted as &quot;the highest forms of life,&quot; according to Jeffrey Richards, author of <em>Sex, Dissidence and Damnation: Minority Groups in the Middle Ages</em> (23). Along with others, Thomas Aquinas believed that lust undermined reason, which then led to a corruption of morals and judgment (Brundage, 421). In fact, the church did not deny that sex was pleasurable, but openly acknowledged the power it could wield over humans, claiming that sex itself only functioned as a generator for more sexual desire. However, according to Nicholas of Lyra and countless others, the pleasure obtained from intercourse was a sin, which automatically led to shame, guilt and even depression, resulting from the &quot;strength of carnal passion&quot; (Brundage, 424).</p>
<p>Law dictated that the <a href="sex-clergy.php">clergy</a> report known fornicators (those who were unmarried and had sexual relations) to the law authorities, who might either punish the offenders with fines (these varied locally), or in many cases try to coerce the couple to marry. Marriage, or at least the provision of some sort of dowry for the female on the part of the male, was actually the most commonly suggested solution to the problem of fornication. We see this several times in the <em>Decameron</em>, for example <a href="../../texts/DecShowText.php?lang=eng&myID=nov0504&expand=day05">V.4</a>, in which Ricciardo Manardi sleeps with the daughter of Messer Lizio da Valbona and upon being discovered, is persuaded to marry her. If the man refused either of these options, he might be forced to pay a fine, but in some cases more serious, corporal punishment resulted. In general, however, the focus was more on healing &quot;social wounds&quot; than on inflicting penalties (Brundage, 461).</p>
<p>Penalties for fornication were influenced by the age and the social, religious, and marital status of the offenders. Punishment was harsher for the old than for the young, as sexual behavior was to be expected of the latter but exceedingly inappropriate for the former. Female peasants were often considered &quot;fair game,&quot; and any man who fornicated with one of them was usually treated leniently, even if there was violence involved - as there often was (cf. Richards, 28-29). Vern L. Bullough: &quot;If a nobleman desired a peasantwoman so strongly that he could not resist the temptation, he was free to rape her on the spot since a courteous approach would only be wasted on a woman who could not possibly feel love&quot; (185). Christians who fornicated with non-Christians (usually Jews or Muslims) often faced the death penalty, as generally much harsher punishment was reserved for instances of miscegenation (Brundage, 461). As might be expected, sex between married persons (who were not married to one other) was a more serious sin than sex between those who were unmarried.</p>
<p>Despite the edicts of canon law and the real risk of punishment, it appears that unrestrained sexual activity was quite common throughout Europe during these times. In fact, most did not believe fornication was a sin at all, and many were taken by surprise at confession when priests informed them that they had indeed sinned by committing certain sexual acts. St. Vincent Ferrer (1350-1419) claimed that by age fifteen, all young men had lost their virginity (Richards, 38). There are also suggestions that rural populations were much more accepting of illicit sexual behavior, and that country folk were viewed as much more &quot;free&quot; sexually than urban dwellers (Richards, 36). Lastly, although premarital sex was obviously considered sinful by the church, in reality, once couples were betrothed, they often slept together during a sort of &quot;trial period&quot; before the wedding. That way, if one or both were not satisfied with the results, they might still attempt to release themselves from future consent to marry (sometimes by becoming godparents of the same child, a relationship which would lead to an <a href="sexual-deviance.php">incestuous union</a>) (Brundage, 436-7).</p>
<h3>Adultery</h3>
<p>While adultery was not quite as common as simple fornication, it too seems to have been relatively widespread. It was so common in fact that by the later Middle Ages it was not even considered grounds for the dissolution of marriage (Brundage, 455). Andrew the Chaplain, author of <a href="../../themes_motifs/amore/courtly_love.php"><em>The Art of Courtly Love</em></a>, wrote that if a man is unfaithful to his wife out of passion and not love, his actions are acceptable (Richards, 40).</p>
<p>However, adulterous offenders were punished more severely than those who simply engaged in fornication. Adultery was considered a more serious sin because it betrayed the marriage vows and could produce illegitimate children (Brundage, &quot;Sex and Canon Law,&quot; 42). Although theologians were somewhat divided on the issue, female adulterers were generally punished more harshly than their male counterparts. Indeed, the general public seemed to agree with the notion that an adulterous woman brought shame and dishonor to her husband and her family, and should face strict penalties (Brundage, 462-463). Guilty women were often expelled from their homes, their dowries were confiscated by their husbands, or, heads shaven, they were forced to parade through the streets. The courts were also hesitant to punish men who murdered their wives' lovers (Brundage, &quot;Sex and Canon Law,&quot; 42). In general, the notion that chastity was more important for a woman than a for a man was universal.</p>
<p>(A.M.S.) Boccaccio, Giovanni. <em>The Decameron.</em> Trans. G. H. McWilliam. New York: Penguin, 1972.<br />Brundage, James A. <em>Law, Sex, and Christian Society in Medieval Europe.</em> Chicago: The University of Chicago Press, 1987.</p>
<p>Brundage, James A. &quot;Sex and Canon Law.&quot; <em>Handbook of Medieval Sexuality.</em> Vern L. Bullough and James A. Brundage, eds. New York: Garland, 1996, pp. 33-50.</p>
<p>Bullough, Vern L. &quot;Prostitution in the Later Middle Ages.&quot; <em>Sexual Practices and the Medieval Church.</em> Ed. Vern L. Bullough and James Brundage. Buffalo: Prometheus Books, 1982, 176-86, pp. 176-86.<br />Richards, Jeffrey. <em>Sex, Dissidence and Damnation: Minority Groups in the Middle Ages.</em> New York: Routledge, 1994.</p>

<?php
	include 'sexlawRelatedPages.php';
?>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
