<?php
	$selected = "society";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Society</a></li>
	<li><a href="../">Medieval Sex and Sexuality</a></li>
	<li>Prostitution in the Middle Ages</li>
</ul>
<h2>Prostitution in the Middle Ages</h2>
<h3>Prostitution and Canon Law</h3>
<p>The Middle Ages in Europe witnessed a universal paradox of tolerance and condemnation with regards to prostitution. While technically a sin (because it hinged on the act of <a href="fornication-adultery.php">fornication</a>), prostitution was recognized by the church and others as a necessary, or &quot;lesser evil&quot; (Karras, 246). It was accepted as fact that young men would seek out sexual relations regardless of their options, and thus prostitution served to protect &quot;respectable&quot; townswomen from seduction and even <a href="sexual-deviance.php">rape</a>. In 1358, the Grand Council of Venice declared that prostitution was &quot;absolutely indispensable to the world&quot; (Richards, 125). In general, declarations proclaiming the necessity of prostitution were not quite so enthusiastic. Indeed, the church did not hesitate to denounce prostitution as morally wrong, but as St. Augustine explained: &quot;If you expel prostitution from society, you will unsettle everything on account of lusts&quot; (Richards, 118). Thus, the general tolerance of prostitution was for the most part reluctant, and many canonists urged prostitutes to reform, either by marrying or by becoming nuns. In fact, there were many religious sanctuaries set up specifically for prostitutes who wished to quit the profession (Bullough, 183).</p>
<p>Prostitution in the Middle Ages was, much as it is today, primarily an urban institution. Especially in Italy, efforts were made early on by municipal governments to expel prostitutes from the cities, but to no avail. The demand was simply far too great, as not only young unmarried men, but men with wives and even members of the <a href="sex-clergy.php">clergy</a> considered themselves in need. Many cities tried to solve the problem by banishing prostitutes to certain areas of town. Often, these quarters turned into &quot;criminal underworlds&quot; associated with the poor and the undesirables of the city, the most famous existing in Bologna (Brundage, 464). (We may think here of neighborhoods such as Malpertugio, in which Andreuccio meets Fiordaliso, in <a href="../../texts/DecShowText.php?lang=eng&myID=nov0205&expand=day02">II.5.</a>) Vern Bullough provides interesting note: streets with the word &quot;rose&quot; in them, he observes, were most likely designated for prostitution during this period, as the phrase &quot;to pluck a rose&quot; was a common metaphor for the act of hiring a prostitute (Bullough, 182).</p>
<p>Another almost universal restriction placed on prostitutes pertained to the clothing they were allowed to wear. In order to set them apart from &quot;decent&quot; women and avoid confusion, the church required that prostitutes adopt some type of distinctive clothing, which each particular city government was allowed to select. For example, in Milan the garment of choice was a black cloak, while in Florence prostitutes wore gloves and bells on their hats (Richards, 119). According to Bullough, a citizen who found a prostitute clothed in anything other than the official dress had the right to strip them on the spot (Bullough, 182).</p>
<p>Many cities decided to take advantage of the situation and earn a little money, setting up municipal brothels with laws and restrictions prohibiting beatings of the prostitutes by brothel keepers, restricting the number of customers a prostitute might entertain in one day, and of course demanding a certain percentage of all earnings (Karras, 246). In 1403, about forty years after ending a long policy of expulsion, the municipal government in Venice established its own brothel in the Rialto, which has since become the traditional center of prostitution in the city. Later, there were attempts to set up other brothels, but this only led to more expulsions in order to regulate the trade and finally to strict compromises between these businesses and the church (Richards, 125-126).</p>
<p>Those who argued against prostitution suggested all sorts of reasons for its existence. For some it was the product of poverty, for others greed or lustfulness, and according to some people, even the stars had something to do with it (Brundage, 464). There were also those who justified prostitution on the grounds that it was a viable economic activity and was primarily directed towards the earning of money rather the gratification of <a href="sexual-desire.php">sexual desires</a> (at least, for the prostitutes themselves). As a matter of fact, when it came to economics, concubinage was often an appealing option; formal contracts involving agreements of sexual fidelity, support obligations and the like were frequently drawn up between partners. Concubinage could be an easy way for poorer families to make beneficial social connections and gain monetary support for their unmarried daughters. Once in a while, concubinage even led to marriage (Brundage, 446).</p>
<h3>Prostitution in the <em>Decameron</em></h3>
<p>There is really only one obvious instance of prostitution in the <em>Decameron</em>: the &quot;young Sicilian woman... willing to any man's bidding for a modest fee,&quot; who swindles Andreuccio in II.5. This young woman is presented as extremely clever and exceedingly cruel. She seems to have created quite a network for herself, but she is by no means a &quot;high class prostitute.&quot; Also called &quot;courtesan mistresses,&quot; these women, who restricted their business to the nobility, began to appear in the later Middle Ages as a result of urbanization and the growing popularity of the ideal of romantic love (Bullough, 184). In general, prostitution seems to be a topic which Boccaccio avoids, contrary to his treatment of certain other sexual behaviors.</p>
<p>(A.M.S.) Boccaccio, Giovanni. <em>The Decameron</em>. Trans. G. H. McWilliam. New York: Penguin, 1972.<br />Brundage, James A. <em>Law, Sex, and Christian Society in Medieval Europe.</em> Chicago: The University of Chicago Press, 1987.</p>
<p>Bullough, Vern L. &quot;Prostitution in the Later Middle Ages.&quot; <em>Sexual Practices and the Medieval Church.</em> Ed. Vern L. Bullough and James Brundage. Buffalo: Prometheus Books, 1982, pp.176-86.</p>
<p>Karras, Ruth Mazo. &quot;Prostitution in Medieval Europe.&quot; <em>Handbook of Medieval Sexuality.</em> Ed. Vern L. Bullough and James A. Brundage. New York: Garland Publishing, Inc., 1996, pp. 243-60.</p>
<p>Richards, Jeffrey. <em>Sex, Dissidence and Damnation: Minority Groups in the Middle Ages.</em> New York: Routledge, 1994.</p>

<?php
	include 'sexlawRelatedPages.php';
?>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
