<?php
	$selected = "society";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Society</a></li>
	<li><a href="../">Medieval Sex and Sexuality</a></li>
	<li>Sex and Medieval Authors</li>
</ul>
<h2>Sex and Medieval Authors</h2>
<p>There has been much debate over the moral value of the <em>Decameron</em>, perhaps due to the multitude of overt sexual references and instances of <a href="fornication-adultery.php">adultery</a> and premarital sex present in the text. Authors argue over whether Boccaccio did in fact present a precise moral stance in his collection or whether his work was simply ahead of its time in its flagrant disregard for contemporary moral values. In his article, &quot;Texts Naked and Veiled: Erotic Elements in Medieval Italian Literature,&quot; Christopher Kleinhenz notes in Boccaccio's Epilogue what he terms a &quot;plea for freedom of expression, for a concept and acceptance of literature free of didactic and moralistic constraints and directed towards the amusement, pleasure, and consolation of the reader&quot; (104). He contrasts this attitude with that of most medieval authors, who would &quot;often conceal their erotic subject matter under thinly veiled wraps, employing euphemisms and double-entendres to produce a culturally acceptable version&quot; (83). For example, in Italian lyric poetry, the ultimate goal (intercourse) was rarely stated by the subject, although it was almost always understood (87).</p>
<p>Kleinhenz does cite some other works of the time that seem to have more in common with Boccaccio's writing. A collection of one hundred anonymous tales from the Middle Ages, <em>The Novellino</em> is similar to the <em>Decameron</em> in its overt descriptions of sexual activity. The following passage from one of the stories has obviously been censored, most likely to suppress offensive material:</p>
<p>Fu uno c'avea s&igrave; grande naturale, che non trovava neuno che fosse s&igrave; grande ad assai. Or avenne c'un giorno si trov&ograve; con una putta che non era molto giovane e, avegna che molto fosse orrevole e ricca, molti n'avea veduti e provati. Quando furo in camera, et elli lo mostr&ograve; e per grande letizia la donna rise. Que' disse: &quot;Che ve ne pare?&quot; E la donna rispose:</p>
<p>[There was a man who had such a large penis that no one could be found who had one so big. Now it happened one day that this man was with a whore who was not very young and, although she was very honorable and rich, she had seen and tried out many penises. When they were in the bedroom, and he showed it to her, the woman laughed with great joy. The man said: &quot;What do you think about that?&quot; and the woman replied: (text missing)] (101)</p>
<p>It seems from this quote that perhaps <em>The Novellino</em> goes even further than the <em>Decameron</em> in crossing social and moral boundaries, although the infamous <a href="../../texts/DecShowText.php?lang=eng&myID=nov0310&expand=day03">Tenth Tale of the Third Day (III.10)</a> (in which Alibech learns to &quot;put the devil back in hell&quot;) was seen as so scandalous that it was replaced by different tales in various editions of the <em>Decameron</em> up through the nineteenth century (103). Kleinhenz also cites writers of burlesque poetry, who were much more overt in their descriptions of sexual matters than their more serious contemporaries. Dante's <em>tenzoni</em>, a sort of a poetic &quot;duel&quot; (the most famous being those addressed to Forese Donati), and Florentine Rustico di Filippo's <em>filone</em> are two of his examples (99).</p>
<p>According to Jeffrey Richards, in medieval stories similar to Boccaccio's, much of the humor involves overstepping the bounds of social sexual norms: &quot;excessive&quot; sexual behavior, the use of nonstandard <a href="sexual-positions.php">sexual positions</a>, the celebration of nudity and so on. Richards cites in this regard <em>Les cent nouvelles nouvelles</em>, a book of stories written in the fifteenth century, and in particular, a story in which the husband sleeps with his wife whenever and wherever he pleases (she is opposed to this behavior but never openly objects). One day the husband strips her naked in the woods, and a farmer comes upon them, thereby creating the humor for the story (Berger, 35). Thus, the reader laughs at the violation of social norms relating to sexual behavior.</p>
<p>In addition, there was the popular genre of the <em>fabliau</em>, described by Sidney E. Berger as a &quot;short tale, usually in verse, and often dealing with some sexual activity [in which] the characters are usually portrayed realistically, speaking an earthy dialogue, performing 'natural' acts, and exhibiting, uncensored, their needs and desires with grace, lust and enjoyment&quot; (162). There is little doubt that Boccaccio was familiar with the <em>fabliaux</em> and it would not be unreasonable to include them among his sources. For instance, there is &quot;the old, lusty, half impotent man with his young, even-more-lusty wife -who invariably finds a young lover who can satisfy her needs,&quot; illustrated in <a href="../../texts/DecShowText.php?lang=eng&myID=nov0210&expand=day02">II.10</a>, the tale in which Messer Ricciardo's wife is kidnapped and seduced by the pirate Paganino and then chooses to stay with him. Also &quot;the woman who wishes to keep her reputation, but who can be convinced, for one reason or another, to give her body to a man&quot; appears in <a href="../../texts/DecShowText.php?lang=eng&myID=nov0402&expand=day04">IV.2</a>, in which Friar Alberto convinces a lady to sleep with him by disguising himself as the Angel Gabriel. The &quot;lusty <a href="sex-clergy.php">monks</a>,&quot; the &quot;jealous, maniacally overprotective husbands,&quot; the &quot;oversexed, clever wives,&quot; and the &quot;eager lovers&quot; are also common characters (173). Not surprisingly, numerous examples of all of these <em>fabliaux</em> character types can be found in the <em>Decameron</em>. Perhaps Boccaccio's work was not as unique in its cry for freedom of expression and its promotion of &quot;natural&quot; behavior as one might suppose.</p>
<p>(A.M.S.) Boccaccio, Giovanni. <em>The Decameron.</em> Trans. G. H. McWilliam. New York: Penguin, 1972.</p>
<p>Berger, Sidney E. &quot;Sex in the Literature of the Middle Ages: The <em>Fabliaux</em>.&quot; <em>Sexual Practices and the Medieval Church.</em> Ed. Vern L. Bullough and James Brundage. Buffalo: Prometheus Books, 1982, pp. 162-75.</p>
<p>Kleinhenz, Christopher. &quot;Texts, Naked and Thinly Veiled: Erotic Elements in Medieval Italian Literature.&quot; <em>Sex in the Middle Ages: A Book of Essays.</em> Ed. Joyce E. Salisbury. New York: Garland, 1991.  </p>


<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
