<?php
	$selected = "society";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Society</a></li>
	<li><a href="../">Medieval Sex and Sexuality</a></li>
	<li>Sex and Spouses: Marriage, Pleasure and Consummation</li>
</ul>
<div class="image_right">
	<img src="../images/matrimonio.jpg" width="200" height="186" />
</div>
<h2>Sex and Spouses: Marriage, Pleasure and Consummation</h2>
<p>Throughout the Middle Ages, the church essentially presented women with two options in order to escape the &quot;sin of Eve&quot;: to become celibate (the preferred choice), or to become mothers (Richards, 25-6). Thus most women, if they did not choose to become nuns, were expected to marry and procreate. According to Hostensius, once a girl was physically ready to consummate a sexual relationship, she was ready for marriage, and the same was true for boys. However, since puberty came earlier for females than males, they could marry at a younger age (usually, he said, girls were ready at age twelve and boys at age fourteen) (Brundage, 434). As a result of arranged marriages involving exchange of property, many couples did not wed for love, or even for sexual attraction. Marriages were not infrequently loveless, unhappy affairs and this frustration is reflected in a popular saying of the times: &quot;No man marries without regretting it&quot; (Richards, 34). Only among the lower classes did people marry consistently for reasons of love or <a href="sexual-desire.php">sexual desire</a>. In general, however, peasant marriages were not common, as there was little need for a formal exchange of property among the poor.</p>
<p>Besides being a means of property exchange, marriage was also seen - especially by the church - as a means for regulating sexual activity and controlling carnal desire. All sex outside of marriage was universally considered sinful, and for most canonists and theologians, sex within marriage was only acceptable as a means for procreation. Although most authors agreed that a good sexual relationship was beneficial to marriage, it was also popular opinion that neither desire nor pleasure should play a major role in these relationships. For example, Thomas Aquinas warned that a man who slept with his wife solely for pleasure was treating her like a <a href="prostitution.php">prostitute</a> (Brundage, 448). Similarly, St. Jerome stated in the fourth century that &quot;a man who is too passionately in love with his wife is an <a href="fornication-adultery.php">adulterer</a>,&quot; and this was a sentiment which remained prevalent up until the end of the sixteenth century (Richards, 23-24). William of Pagula was a bit more lenient in his view that it was not sinful to marry for sexual attraction, so long as this was not the primary reason (Brundage, 430). Consistently, procreation, or &quot;the divine plan&quot; of continuing the race, was seen as the only acceptable end to marital relations.</p>
<p>Not only was the purpose of sex within marriage made abundantly clear by the church, but there were many rules and regulations pertaining to the act itself. According to James Brundage, &quot;marital relations required forethought, deliberation, and conscious reflection if one wished to avoid serious sin&quot; (450). The<em>Summae Confessorum</em>, a handbook for confessors published during the early thirteenth century, listed some of the times in which sexual activity between husband and wife was not permitted, which included all feast and fast days, on Sundays, and at all times when the woman was considered &quot;unclean&quot; (during menstruation or pregnancy, while she was breast-feeding, and for forty days after childbirth). This meant that, on average, most married couples could legally have sex less than once a week (Richards, 28-29). In <a href="../../texts/DecShowText.php?lang=eng&myID=nov0210&expand=day02">II.10</a> of the <em>Decameron</em>, Messer Ricciardo di Chinzica, who cannot keep up with his younger, lustier wife, finds a similar way to limit their sex life:</p>
<p>For he made it clear to her that there was not a single day that was not the feast of one or more Saints, out of respect for whom... man and woman should abstain from sexual union. To the foregoing, he added holidays of obligation, the four Ember weeks, the eves of the Apostles and a numerous array of subsidiary Saints, Fridays and Saturdays, the Sabbath, the whole of Lent, certain phases of the moon, and various special occasions... For a long time (much to the chagrin of his lady, whose turn came round once a month at the most) he abided by this r&eacute;gime...(179-80)</p>
<p>In addition to prescribing when couples might have intercourse, the church also provided instructions for marital coitus. The treatise <em>De secretis mulierum</em> gave a detailed account of the process, advising physical and mental preparation (such as the emptying of the bowels and bladder) and sufficient foreplay, or fondling of &quot;the lower parts,&quot; in order to raise the female's body <a href="heat-coldness.php">heat</a> to the correct temperature. When the wife began &quot;to speak as if she were babbling,&quot; the husband should know to make his move (Brundage, 451).</p>
<p>Although general opinion regarding sex within marriage tended to remain static throughout the Middle Ages, some more modern opinions began to surface during the thirteenth and fourteenth centuries. Earlier issues of ritual purity, such as the prohibition of intercourse during menstruation and pregnancy, were not considered as serious as they had been in the past by a number of theologians and canonists. Albert the Great even excused sex during pregnancy, claiming that the fetus stimulated sexual desire in the woman: &quot;A woman never desires sex so much as she does when she is pregnant... Medicine is most needed in the time of greatest illness&quot; (Brundage, 451-2).</p>
<h3>The Question of Consummation</h3>
<p>In the Middle Ages, some linked the sacrament of marriage to the nuptial blessing given by the church, but there were others who insisted that it depended on the physical consummation of the marriage. It seems that many held consummation as essential to the validity of a union, while the church generally maintained that mutual consent of the couple (signified by the blessing) was the only thing necessary to complete a marriage. Evidence for the first opinion can be found in Boccaccio's tale about Sophronia, who weds Giusippus but consummates the marriage with his friend Titus, who thus becomes her &quot;real&quot; husband (<a href="../../texts/DecShowText.php?lang=eng&myID=nov1008&expand=day10">X.8</a>) (Brundage, 456). Granted, this story takes place in Greece and not in medieval Italy, but it does seem consistent with the popular view that physical consummation was what determined the validity of a marriage.</p>
<p>In the twelfth century, Gratian had defined the two essential parts for the proper validation of a marriage: spiritual consent and physical consummation. According to him, without either of these components the union was invalid (Richards, 27). However, among the general public it seems that there were two opposing forces, neither of which saw the need for both of these two components. Some canonists actually argued the necessity of physical consummation. Aquinas and Bonaventure both agreed that a man who had a permanent inability to copulate, no matter what the reason, could not marry validly, while Bernard of Montemirato went even further to state that the ability to copulate and specifically to inseminate was crucial to a valid marriage (Brundage, 456). However, as we can see from Bernard's opinion, all three theologians probably had the necessity of procreation (rather than sexual fulfillment) in mind when they insisted that a man must be able to have intercourse with his wife.</p>
<p>(A.M.S.) Boccaccio, Giovanni. <em>The Decameron.</em> Trans. G. H. McWilliam. New York: Penguin, 1972.</p>
<p>Brundage, James A. <em>Law, Sex, and Christian Society in Medieval Europe.</em> Chicago: The University of Chicago Press, 1987.</p>
<p>Richards, Jeffrey. <em>Sex, Dissidence and Damnation: Minority Groups in the Middle Ages.</em> New York: Routledge, 1994.</p>

<?php
	include 'sexlawRelatedPages.php';
?>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
