<?php
	$selected = "society";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Society</a></li>
	<li><a href="../">Medieval Sex and Sexuality</a></li>
	<li>Sexual Deviance</li>
</ul>
<h2>Sexual Deviance</h2>
<p>During the second half of the Middle Ages, municipal and royal law became much more comprehensive and well-organized. Because of conflicts between municipal lawmakers and the church, civic law sometimes departed substantially from canonical views. As the court system began enforcing sexual conduct laws more strictly, more and more offenders came before them, and although <a href="fornication-adultery.php">fornication and adultery</a> cases accounted for the vast majority of court business, other more unusual crimes such as incest, sodomy, masturbation and rape were not particularly uncommon (Brundage, 461). In addition, during the <a href="../../plague/">Plague</a> years, the total number of sex crimes in Venice remained the same as it had before, despite a loss of more than one-third of the city's population. This indicates that either the authorities were hunting out offenders more enthusiastically, or people were attempting to escape the harsh reality of the Black Death by leading sexually freer lives (Brundage, 491). The latter seems more likely, and may perhaps even be testified to in the <em>Decameron</em>, considering the strong sexual content of many of the stories told by the <a href="../../brigata/"><em>brigata</em></a> in trying to forget about the Plague.</p>
<p><strong>Incest</strong> was one of the most common sexual offenses, after fornication and adultery. The Fourth Lateran Council had established the &quot;four-degree rule&quot; regarding incest in 1215, which was re-enacted and generally observed by most courts during this time. <a href="sex-spouses.php">Marriage</a> between close relatives (within four degrees) of either blood or marriage was forbidden by law, and the only way couples bound by ties of &quot;cosanguinity or affinity&quot; might wed was with the consent of the Pope himself (Brundage, 434). In addition, there was an apparent &quot;spiritual relationship, both between godparent and child and between godmother and godfather,&quot; and thus marriages between such people were declared incestuous (Brundage, &quot;Sex and Canon Law,&quot; 43). In fact, there are two instances in the <em>Decameron</em> involving sexual intercourse between god-relations: <a href="../../texts/DecShowText.php?lang=eng&myID=nov0703&expand=day07">VII.3</a>, in which Friar Rinaldo sleeps with his godchild's mother, and <a href="../../texts/DecShowText.php?lang=eng&myID=nov0710&expand=day07">VII.10</a>, in which Tingoccio sleeps with the mother of his godchild, then dies and returns from the dead to inform his brother that this act was not a sin. In the following passage, Tingoccio recounts:</p>
<p>My brother, as soon as I arrived down there, I was met by one who seemed to know all of my sins by heart... and I suddenly remembered how I had carried on with my godchild's mother. And since I was expecting to pay a much heavier penalty for this... I began... to tremble all over with fear... I said: &quot;I made love to the mother of my godchild...&quot; He had a good laugh over this, and said: &quot;Be off with you, you fool! There's nothing special down here about the mother of a godchild.&quot; I was so relieved to hear it that I could have wept (547).</p>
<p>In both stories it is clear that the offenders realize they are committing an act which is commonly labeled as a sin, but neither couple is punished in any way for it, just as most of those who fornicate or commit adultery in the <em>Decameron</em> suffer no meaningful penalties whatsoever. It is important to note that incest was more common among the aristocracy than the peasants. For obvious reasons, those who were well off or of noble lineage often wished to marry within their own circles (Brundage, 434).</p>
<p><strong>Sodomy</strong> was also a relatively common offense, but there were some disagreements regarding how to define it. While some thought that sodomy included any &quot;unnatural&quot; use of sperm (such as anal intercourse, masturbation and oral sex), there were others who used a definition of sodomy closer to the one we use today. According to James Brundage, sodomy was viewed as particularly common among the <a href="sex-clergy.php">clergy</a> (who technically had no legitimate outlet for their <a href="sexual-desire.php">sexual desire</a>), and in the cities (472), In general, acts of sodomy involving homosexuality were severely punished by the courts, often by castration or hanging (Brundage, 473). This perception is remarkably more severe than Boccaccio's offhanded remark that Ciappelletto (<a href="../../texts/DecShowText.php?lang=eng&myID=nov0101&expand=day01">I.1</a>) was as fond of women &quot;as dogs are fond of a good stout stick; in their opposite, he took greater pleasure than the most depraved man on earth&quot; (26). Although adultery was not legitimate grounds for the dissolution of marriage, Pope Innocent IV declared that a woman whose husband tried to convince her to consent to anal intercourse might obtain a separation (Brundage, 455).</p>
<p><strong>Masturbation</strong>, sometimes included within the definition of sodomy, was not viewed as a major offense during the earlier Middle Ages, though it began to be later on. Thomas Aquinas considered it one of the most serious sins because it was &quot;against nature&quot; and not for procreation, while in 1388 Archbishop Guy de Roye suggested that it was such a serious sin that it should be dealt with only by bishops (Richards, 31). This change of opinion may have been brought on by the onset of the Plague, which led to general fears about population decline and perhaps caused a general concern about the &quot;wasting of seed&quot; (Richards, 32). In the <em>Decameron</em>, masturbation is only referred to fleetingly, and even then the reference is not direct: &quot;[the abbess] thenceforth arranged for him to visit her at frequent intervals, undeterred by the envy of her fellow nuns, without lovers, who consoled themselves in secret as best they could&quot; (<a href="../../texts/DecShowText.php?lang=eng&myID=nov0902&expand=day09">IX.2</a>, 658).</p>
<p><strong>Rape</strong> and other sexually violent acts were a subject on which canonists and theologians disagreed with municipal law. While the church was very focused on individual consent in all matters involving sexual contact, rarely did the courts punish rapists or those who committed any kind of sexual assault on women. During the later Middle Ages in Venice, rape was neither uncommon nor considered a serious crime, unless it involved children, the elderly, or a victim who was a member of the aristocracy (Richards, 39). As a result of rape, many women lost their social status and marriageability, while their attackers were written off as victims of &quot;youthful male sexuality&quot; (Richards, 40-41). Occasionally, a man could take action against his wife's attacker for &quot;criminal diversion&quot; of his spouse. Thus, her rape was seen as an act against her husband, as she was technically considered his property (Brundage, 471).</p>
<p>There were of course more minor sexually deviant acts committed during this time, some of which incurred punishment and some of which did not. For example, while cross-dressing carried no known penalties under the law (Brundage, 473), contraception was considered highly sinful, as it interfered with procreation and was thus equated with abortion. Like masturbation, <em>coitus interruptus</em> was promoted from a minor to a major sin during the later Middle Ages, and many courts included it under the heading of &quot;sodomy&quot; by the fifteenth century (Richards, 32-33).</p>
<p>(A.M.S.) Boccaccio, Giovanni. <em>The Decameron.</em> Trans. G. H. McWilliam. New York: Penguin, 1972.</p>
<p>Brundage, James A. <em>Law, Sex, and Christian Society in Medieval Europe.</em> Chicago: The University of Chicago Press, 1987.</p>
<p>Brundage, James A. &quot;Sex and Canon Law.&quot; <em>Handbook of Medieval Sexuality.</em> Ed. Vern L. Bullough and James A. Brundage. New York: Garland Publishing, Inc., 1996, pp. 33-50.</p>
<p>Richards, Jeffrey. <em>Dissidence and Damnation: Minority Groups in the Middle Ages.</em> New York: Routledge, 1994.</p>

<?php
	include 'sexlawRelatedPages.php';
?>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
