<?php
	$selected = "literature";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Literature</a></li>
	<li><a href="../">Theoretical Perspectives</a></li>
	<li>The Frame</li>
</ul>
<h2>The Frame</h2>
<p>A number of scholars have written about the so-called <strong>&quot;frame story&quot;</strong> and its strategic narrative and ideological function in the <em>Decameron</em>. According to one critic (<a href="../../bibliography/">Barberi Squarotti</a>, chapter 1: &quot;La cornice del <em>Decameron</em>&nbsp;o il mito di Robinson&quot;), the &quot;frame story&quot; can be considered an earlier version of the &quot;myth of Robinson&quot; (Crusoe); the fiction of the seven young women and three young men who willingly isolate themselves from the city and entertain themselves with storytelling, establishes a narrative myth similar to that of Defoe's 18th-century novel: the re-creation of society out of the ruin and dissolution caused by the plague. &quot;Out of the wreckage of disease-ridden Florence, Boccaccio creates a fiction of perfect order&quot; (<a href="../../bibliography/">Marcus</a>, Introduction, p. 7). The frame story thus also acquires an allegorical value, as a rhetorical device that, starting with the author's introduction, both connects and separates &quot;history&quot; and &quot;fiction&quot; or, using <a href="../../bibliography/">H. Weinrich's</a> terms, the &quot;discussed&quot; world and the &quot;narrated&quot; world. The fact that the 100 stories of the <em>Decameron</em>&nbsp;are not recounted directly by the author but by ten fictional narrators (who also have allegorical names) over ten fictional days, &quot;places them at one more remove from the reader&quot; (Marcus). The ten narrators form a hierarchical yet not authoritarian, pleasure-oriented yet not promiscuous, free yet not anarchic society within the boundaries established by fiction: in other words, the utopian setting of the <em>Decameron</em>. Moreover, within the &quot;frame story&quot; the ten narrators are also the audience, thus acting as intermediaries between the author and our own reception of the narrative.</p>
<p>Their presence makes explicit the process of telling and receiving tales, and is a constant reminder that we are within the double boundaries of a fictional construct -- their presence also forces us to mentally move back and forth across those ideal and invisible boundaries in order to discuss or assess the &quot;meaning&quot; or &quot;message&quot; of a single story or the whole work. Dioneo's privilege of telling the last story of the day and only the story that he likes or wants without obeying the rule of the Day, is the exception that confirms and reinforces the general rule and the reader's awareness of it. The &quot;frame story&quot; can thus be conceived as a control mechanism devised by the author in order to give formal order and structure to the chaotic matter of the narrative (the world as a virtually infinite chain or tangle of stories). It is meant to guide our own <em>reading</em>, by establishing the fiction of &quot;storytelling&quot; as a self-conscious social, oral, conversational, even critical or ritual process. This is fundamentally important because it relates to one of the crucial aspects of the <em>Decameron</em>&nbsp;as a book that designs and contains its own ideal audience and its own interpretive rules (an early example of self-referential literature): that is, the relationship between the &quot;literal&quot; and &quot;metaphorical&quot; or &quot;allegorical&quot; or &quot;figural&quot; meaning of written and spoken words (for example the various levels of meaning of the &quot;<a href="../../themes_motifs/amore/garden.php">garden</a>&quot; as the ideal setting of the frame story and of many of the stories with a sexual or erotic content). The <em>Decameron</em>&nbsp;is as much about society, mores, sexual relationships, religion etc. as it is about storytelling as such, a sort of manual of the art of storytelling (including the art of understanding and interpreting stories). Those sections of the text where the author intervenes in the first person (as opposed to as the narrator) must also be considered in this light. Thus, the author speaks directly in the preface (addressed to an ideal readership of women), in the introduction to the Fourth Day (addressing both his critics and his readers), and in the Conclusion, but he is also present as the editor of his own book (titles, paragraphs, etc.). The entire structure of the <em>Decameron</em>, although linear and self-contained, is potentially similar to a hypertextual system, with the frame story working as the roadmap or the navigating tool for exploring all possible links among the stories themselves, their narrators and their alternative interpretations.</p>
<p>(M.R.) </p>

<?php
	include 'relatedPages.php';
?>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
