<?php
	$selected = "literature";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Literature</a></li>
	<li><a href="../">Theoretical Perspectives</a></li>
	<li>Poststructuralism and a Figural Narrative Model</li>
</ul>
<h2>Poststructuralism and a Figural Narrative Model</h2>
<p>Eugene W. Holland's article, &quot;Boccaccio and Freud: A Figural Narrative Model for the <em>Decameron</em>&quot; (1985), uses literary theory techniques to overturn Tzvetan Todorov's analysis in his structuralist manifesto <em>Grammaire du D&eacute;cam&eacute;ron</em>. Having shown the limits of Todorov's model, Holland goes on to present a new mode of textual analysis based on narrative-level rhetorical structures, and he offers this as an example of figural narrativity.</p>
<p>Holland begins by showing why Todorov uses a grammatical logic to analyze narrative and he examines his general conclusions on literariness. With the advent of poststructuralism, however, Holland is forced to reconsider this model. He cites scholars like Paul de Man on the &quot;tension between grammar and rhetoric,&quot; and Holland shifts his focus from literary language's relationship to grammar to literary language's relationship to the broad category of &quot;rhetoric.&quot; As he writes, &quot;For our appreciation of these tales depends not so much on sentence-level rhetorical features [of the sort that interest de Man], nor on the narrative grammar posited by Todorov, but rather on narrative-level rhetorical structures which escape Todorov's analysis altogether&quot; (86). Holland faults Todorov for his obsessive focus on syntactic units and writes that &quot;to be meaningful, a sentence requires more than merely grammatical constraints, and this is true for stories as well&quot; (86). Holland goes on to argue that Todorov's model isolates and evacuates each story. He claims that Todorov denies the &quot;esthetic&quot; qualities which give tales an &quot;essence&quot; and that his model provides both an endless (hence useless) grammatical frame and a syntactic inflexibility. In doing this, Holland is demonstrating how Todorov's grammatical lens, on both a practical and metaphoric level, fails to account for the dynamism of Boccaccio's prose. Holland claims that &quot;this is precisely the advantage of a figural narrative model: the figure of speech transferred to the narrative level provides those principles of closure and completeness and can thus help us understand why the well-formed tale stands out as distinct from passages of nonliterary prose&quot; (87). The figural model, based around ideas of story-telling and figures of speech, allows for a study of rhetoric. This linguistic examination does not use the rigid model of high or low rhetoric, instead, it searches for the equivalent rhetorical 'grammar' in Boccaccio's tales.</p>
<p>Holland then moves into a discussion of Roland Barthes' &quot;<em>fait divers</em>, or human interest story&quot; as an example of one rhetorical structure. Holland defines this Barthesian mode as either &quot;the repetition of an incident in different contexts or the doubling of a single event seen from two different perspectives&quot; in which &quot;the relation between the two sequences... is always less than the expected causal one&quot; (88). For example, Barthes tells the story of a nurse who steals a baby, not for money (the implied reason), but for love (the striking reason). Holland writes that Barthes attributes our interest to &quot;the fact that the doubling occupies the middle ground between -- but never quites reaches -- the extremes of strict causality on one hand and pure chance on the other&quot; (88). Holland describes these tales as being framed against a &quot;modern sense&quot; of causality, one that is psychicly shared, but he believes that their syntactic structure is accessible through Freudian psychoanalysis.</p>
<p>Holland then applies Barthes' model, his figural embodiment, to Freud's analyses in <em>Jokes and their Relation to the Unconcious</em>, comparing narrative doubling to Freud's study of the double-entendre, or paronomasia. It is worth summarizing at this point that Holland has rejected Todorov's model, mapped his notion of a figural, or rhetorical, model onto Barthes' <em>fait divers</em>, and then, after examining the structural similarities between Holland/Barthes' <em>fait divers</em> and Freud's paronomosia, applied this amalgam to Freud's paradigm. &quot;Paronomastic narrative,&quot; for Holland, implies that &quot;two different points of view converge on a single ambivalent element of the story&quot; (89) -- a narrative pun of sorts. Working off Freud's psychoanalytic account of the pleasure behind paronomasia, the &quot;unexpected economies of psychical expenditure&quot; (89), Holland extends this pleasurable repetition to include his model of narrative paronomasia.</p>
<p>Having laid the groundwork for his argument, Holland begins again by refuting Todorov's claim, that &quot;there is a law such that an object cannot have more than one value at a time&quot; (90). He then argues that a double-entendre, a figure of speech, depends on this playfulness, and that his &quot;narrative paronomasia&quot; also requires this doubling. Holland continues by writing that in his model a &quot;narrative element <em>can</em> have more than one value, and that such polyvocity is in fact crucial to the overall esthetic effect of his kind of tale&quot; (90). It is necessary at this point to recognize that Holland is using the word &quot;figural&quot; to stand in for both the human, rhetorical sense of &quot;figural&quot; (of, relating to, or consisting of human figures: the story-teller), and the &quot;figurative,&quot; or non-literal sense, in which multiple meanings exist. Holland's double meaning is neither coincidental nor misplaced for in his own model the figurative, the pun, serves as the micro version, the psychonalytic template, for the multi-sequenced figural narrative.</p>
<p>Holland then analyzes Frederigo's tale (<a href="../../texts/DecShowText.php?lang=eng&myID=nov0509&expand=day05">V.9</a>) through this model, a tale which Tododorov claims &quot;defies grammatical analysis.&quot; In this instance, Holland argues for the use of a figural, rhetorical narrative, stating that &quot;to the suitor, the hawk symbolizes his former status, provides his sustenance, and becomes the ultimate sacrifice to be made for the woman he loves; to her, its sacrifice as a gift was the utlimate favor to ask in the hope of saving her son&quot; (89). Working off the notion of the pun, Holland psychically describes this narrative using the Freudian notion of the joke. He argues that the &quot;teller must be able to count on setting up an &quot;inhibitory cathexis&quot; in the listener in order to later release it...&quot; (91).</p>
<p>In Peronella's example (<a href="../../texts/DecShowText.php?lang=eng&myID=nov0702&expand=day07">VII.2</a>), the strict causation through Todorov's grammatical model fails to account for, and actually misrecounts, the complex series of sequences which exist simultaniously in the mind of the reader/listener. These complexities, however, are fully embodied in the doubling figure of the vat which Todorov cannot account for because of his decision to read &quot;names&quot; instead of &quot;subjects.&quot; Holland writes:</p>
<p>As we shall see, the vat is the element on which two different interpretations converge: Pironella's and her husband's (93). In line with Barthes' analysis, this convergence is striking: the normally unrelated acts of hiding an illicit lover and making a quick florin are linked by the vat, in a manner well outside the domain of regular causality (93).</p>
<p>Holland goes on to write that:</p>
<p>Just as in a play on words two different meanings are condensed in a single acoustic image [pun, figurative], here in the story two conflicting motives--adultery and industry-- are focused on the vat by Pironella and her hapless husband [Barthesian rhetorical narrative, figural]. This 'multiple use of the same narrative elements' (to paraphrase Freud) contributes to the triumph of the personal initiative over social convention, just as it would in a tendentious joke (94).</p>
<p>Holland goes on to argue that unlike Todorov, the figural model contains the logic of a beginning and end within it, and it explains the general mechanisms of pleasure. Holland finishes by writing:</p>
<p>The striking success of the paronomastic variant explored here leads me to believe nevertheless that a search for the figural deep-structure of other tales might well prove fruitful, and in any case demonstrates the increase in descriptive rigor and explanatory power to be had by adopting a narrative model based on the ambiguities of rhetoric rather than the identities of grammar (95).</p>
<p>Holland believes that the combination of literary analysis (Barthes) with psychoanalysis (Freud) provides an opportunity to overturn structuralist readings (Todorov) with a more poststructuralist (Holland) account of desire and linguistic play. If Barthes' <em>fait divers</em> serves as the springboard for Holland's inquiry, Holland believes that many more figural narratives can be created.</p>
<p>While Holland's creation of a figural narrative model serves both literary and academic ends, there are questions worth raising. First, Holland's criticism draws on a doubling of narrative elements and he presumes that this signification must take place in the object world, hence his frustration with Todorov for assigning the &quot;name&quot; category rather than the &quot;subject&quot; category. This multiplicity, however, also takes place in the realm of the subject world. Todorov acknowledges this in the <em>Grammaire</em> when he writes: &quot;Les travestissements sans r&eacute;cit sont &eacute;galement fr&eacute;quents. Gilette de Narbonne se glisse ainsi dans le lit de son mari qui ne veut pas coucher avec elle, en se pr&eacute;sentant pour une autre (<a href="../../texts/DecShowText.php?lang=eng&myID=nov0309&expand=day03">III.9</a>); de m&ecirc;me, le palefrenier audacieux r&eacute;p&egrave;te sur tous ses camarades la marque qui aurait fait d&eacute;couvrir en lui le coupable, et &eacute;vite par l&agrave;-m&ecirc;me la punition (<a href="../../texts/DecShowText.php?lang=eng&myID=nov0302&expand=day03">III.2</a>) (36).</p>
<p>As such, Gilette and the groom who tricks King Agilulf's wife both double as signifiers, producing two narrative sequences whose irresolvability leads to a humorous end. In these two instances, just as in Holland's examples, the reader is made aware of the various sequences even though all the characters are not. In fact, their (mis)motivations derive from this double sequence, this doubling of objects. Holland would likely contend that Todorov's system fails to adequately account for this (there seems to be no X/Y), but his system does as well.</p>
<p>Secondly, Holland's notion of rhetorical or figural narrative structures relies on a shared, communal psyche in which inhibitions and releases can be successfully transferred. While he clearly accounts for this temporal shift in his notion of story-telling, he fails to fully explicate the lengthy history, from the 14th to the 20th century, which is necessarily involved in this transmutative sequence. Todorov's grammar may be faulty, but it enjoys a universality that a figural narrative cannot.</p>
<p>(J.R.) Holland, Eugene W. &quot;Boccaccio and Freud: A Figural Narrative Model for the <em>Decameron</em>&quot; <em>Essays Volume III: Critical Approaches to Medieval and Renaissance Texts</em>. Pittsburgh: U of Pittsburgh P, 1985; Todorov, Tzvetan <em>Grammaire du D&eacute;cam&eacute;ron</em> Paris: Mouton, 1969. </p>

<?php
	include 'relatedPages.php';
?>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
