<?php
	$selected = "themes_motifs";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Themes &amp; Motifs</a></li>
	<li><a href="../">Amore</a></li>
	<li>Nature as Morality</li>
</ul>
<h2>Nature as Morality</h2>
<p>The reader quickly becomes aware, when reading the <em>Decameron</em>, that Boccaccio is working off some moral base in writing the stories which each of the storytellers tell. In accordance with Medieval literary practice, the stories cannot be regarded as mere entertainment. The attitudes of the storytellers towards their subjects are too pronounced for such a simplistic view, and the treatment of many themes is too thorough to think otherwise. The stories, and the storytellers, appear to follow a moral base or code of some sort which Boccaccio is suggesting to his readers. The difficulty lies in finding what that moral base is, since it is certainly not the general morality of his time. </p>
<p>Arguably, the moral base of the <em>Decameron</em> is Nature. The storytellers strongly suggest this in several cases and from different point of views. Those who oppose themselves to the law of Nature are bound to failure and also perhaps to causing great harm. Here are some examples, not at all exhaustive of this crucial theme: Dioneo, in the <a href="../../texts/DecShowText.php?lang=eng&myID=nov0210&expand=day02">tenth story of the second day</a>, says in his prologue, &quot;I shall show the... foolishness of those who, overestimating their natural powers, resort to specious reasoning to persuade themselves that they can do the impossible, and who attempt to mold people in their own image, thus flying in the face of nature.&quot; He goes on to tell of an old man who cannot sexually satisfy his young wife, a recurrent topic in the <em>Decameron</em>. The old man invents all sorts of reasons why he cannot sleep with her, and she eventually leaves him for another man. When the old man tries to convince her to come back to him, she refuses, saying she is happier with the new man who can sexually satisfy her. According to this (tendentious on Dioneo's part) interpretation of the laws of Nature, a young woman needs to be sexually satisfied and the old man, by failing to do so, quite justly loses her. Even more interesting, however, is the lady's assertion, &quot;As to my honor... I only wish my parents had displayed an equal regard for it when they handed me over to you!&quot; This suggests that the lady's marriage to the old man, because it was a mockery of the laws of Nature, was dishonorable. The laws of Nature are here set up as a dialectical code: that is, a code that is conducive to highlighting contradictions in the social order.</p>
<p>Another example: Neifile, in her prologue to the <a href="../../texts/DecShowText.php?lang=eng&myID=nov0408&expand=day04">eighth story of the fourth day</a>, also brings up the laws of Nature. She begins, &quot;To my way of thinking there are those who imagine that they know more than others when in fact they know less, and hence they presume to set up this wisdom of theirs against not only the counsels of their fellow men, but also the laws of nature. No good has ever come of their presumption, and from time to time it has done an enormous amount of harm.&quot; She then goes on to tell a story about a mother who, by interfering with her son's love life, eventually brings about his death as a result of grief over the loss of his lover. Love, both physical and emotional, is one of the forces of Nature in the <em>Decameron</em>, and to interfere with it is indeed to interfere with the laws of Nature. As Neifile warns, such interference has dire consequences. Nature thus provides a moral code for the <em>Decameron</em> which is strong enough to imply punishment for those who attempt to deviate from it.</p>
<p>Nature, as the morality in the <em>Decameron</em>, is a new type of dialectical morality, and one which imparts greater freedom to its adherents than more traditional moral codes. This is true particularly of women as the collective subject to whom Boccaccio's work is addressed. Pampinea, in the <a href="../../texts/DecShowText.php?lang=eng&myID=nov0110&expand=day01">tenth story of the first day</a>, speaks of ladies who do not talk in the presence of gentlemen, because they think it would not be proper, or pure, of them. She says, &quot;They give the name of honesty to their dull-wittedness, as though the only honest women are those who speak to no one except their maids, their washerwomen, or their pastry cooks. Whereas if, as they fondly imagine, this had been Nature's intention, she would have devised some other means for restricting their prattle.&quot; Here Pampinea uses Nature as a spur to greater power of speech among women. Nature, Pampinea argues, intends women to speak, else, she implies, they would not physically be able to. Since Nature is morality in the <em>Decameron</em>, if Nature intended that women should speak, speak they shall, and any rule to the contrary is wrong. Pampinea imparts real freedom to women by this invocation of Nature. First, it combats the other ever-present and much mocked moral code in the Decameron, that of the hypocritical clergy. The moral code of the clergy, with its assertions of Eve's sin and women's general wickedness, is also meant to make women silent. Pampinea, by using the new moral code of Nature, is able to counter this position. Second, Pampinea's statement allows women to leave the confines of the household, where the maidservant, the washerwoman, and the pastry cook are, to interact with the world outside. Finally, Pampinea's assertion is self-serving since it invites the women of the group to be full participants in the game of language which is such a part of the <em>Decameron</em>.</p>
<p>(M.L.) Hastings, R. <em>Nature and Reason in the</em> Decameron. Manchester: Manchester University Press, 1975.</p>

<?php
	include 'relatedPages.php'
?>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
