<?php
	$selected = "themes_motifs";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Themes &amp; Motifs</a></li>
	<li><a href="index.php">The Eaten Heart</a></li>
	<li><a href="4_1-4_9.php">Filomena's and Filostrato's Tales of the Extracted Heart</a></li>
	<li>Legend of the Eaten Heart: Sources of IV.9</li>
</ul>
<h2>Legend of the Eaten Heart: Sources of IV.9</h2>
<p>The succession of tragic tales of the fourth day is marked by a distinct symmetry of images. In the first and last tale (excluding Dioneo's customary departure from the day's theme) a lover's heart is torn from his body: the dominant metaphor of love is made flesh, tragically literalized. At the end of the first tale, Ghismonda weeps over Guiscardo's heart which has been sent to her in a goblet by Tancredi, bathing it tenderly with her tears in an almost ritualistic act which precedes her suicide by poison. In the tale of Guiglielmo di Rossiglione (<a href="../../texts/DecShowText.php?lang=eng&myID=nov0409&expand=day04">IV.9</a>), the savagery of the day's tales reaches its climax when the heart of his wife's lover is fed to her in a macabre final meal. The image of the eaten heart appears in Italian literature before the <i>Decameron</i>, the most illustrious examples being perhaps the story of Baligante and the count of Arminimonte in the <i>Novellino</i>&nbsp;(LXII), and the enigmatic <a href="vita_nuova.php">third chapter of the <i>Vita Nuova</i></a>&nbsp;in which the poet has a vision in which Love holds Beatrice in his arms and feeds her the poet's heart. While questions of intertextuality among these works remains obscure at best, their shared imagery certainly has deep cultural and anthropological roots. The story of Guiglielmo di Rossiglione, however, does possess a rich and relatively clear line of literary antecedents. Boccaccio cites a Proven&ccedil;al source at the story's opening: &quot;You must know then, that according to the Proven&ccedil;als...&quot;. The written source with which Boccaccio was probably familiar is the biography of Guilhelm de Cabestaing (a troubadour in the service of Raimon of Rossiglione) whose betrayal of his lord leads to the same tragic end described in Boccaccio's novella.</p>
<p>Yet the tale can be traced further, both chronologically and geographically, to an Indian tale. Of the various versions of the story, one runs as follows: king Rasal&uacute; (an ancient national hero of Punjab) weds Koklan, who later accepts the love of Raja Hodi, a neighboring prince. Rasal&uacute; learns of the affair, slays Hoji in an ambush, carries his heart home and serves it to Koklan. When she discovers what she has eaten, she throws herself over a palace wall onto the rocks below. In addition to these general parallels between Boccaccio's novella and the Indian tale, they share some strikingly similar details. When Koklan learns that she has eaten her lover's heart, Rasal&uacute; replies: &quot;He who was your joy in life, his flesh you have eaten&quot;. Guiglielmo di Rossiglione's response is nearly identical: &quot;I do not marvel that what gave you so much pleasure when alive should please you when dead&quot;. The story of Rasal&uacute; thus most likely came from India to Southern France, where it was adapted to local culture. In the biography of Cabestaing, for example, the prince Hoji appears as a troubadour, and the character of Rasal&uacute; (a king) becomes the lord Raimon de Rossilhon. The name <i>Rasal&uacute;</i>, in fact, is associated by some scholars with <i>Rossilhon</i>&nbsp;in Provence.</p>
<p>Boccaccio's alterations of the Proven&ccedil;al version provide some insights into the workings of his designs for the novella. The name Raimon is changed to Guiglielmo in order to provide an identification of the novella's two male protagonists. Their onomastic identity is buttressed by other similarities, which Boccaccio describes in the novella's carefully constructed opening: &quot;...there were once two noble knights of Provence, <i>both</i>&nbsp;with castles and vassals....<i>Both</i>&nbsp;were valiant men at arms and therefore loved each other; and they were wont always to go together to jousts and tourneys and other feats of arms, <i>bearing the same device</i>&quot; (emphasis added). Following the same principle of variation, Boccaccio alters Cabestaing's (Guardastagno's) quality as troubadour, an important feature of the Proven&ccedil;al version. He is given the status of knight, thus Rossiglione's social equal, which redirects the problematic of feudal relations inherent in the tale. One may also speculate, with some caution, that in placing the two protagonists on an equal social footing, Boccaccio is following the model of <i>variatio</i>&nbsp;within the collection of the day's stories, since in the ninth tale's closest counterpart (<a href="../../texts/DecShowText.php?lang=eng&myID=nov0401&expand=day04">IV.1</a>), the social disparity of Tancredi and Guiscardo, plays a central role.</p>
<p>(A. T.) For a careful reconstruction of the relations between the tale of Rasal&uacute;, the Proven&ccedil;al biography, and Boccaccio's novella, see: Mattzke, John. &quot;The Legend of the Eaten Heart.&quot; <i>Modern Language Notes</i>&nbsp;26:1 (1911): 1-8. </p>
		
<?php
	include 'relatedPages.php';
?>
								
<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
