<?php
	$selected = "themes_motifs";
	require '../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../">Main</a></li>
	<li><a href="index.php">Themes &amp; Motifs</a></li>
	<li>Echoes of an Indian Tale in the <em>Decameron</em></li>
</ul>
<h2>Echoes of an Indian Tale in the <em>Decameron</em></h2>
In accordance with the theme of the eighth day, Dioneo narrates a tale involving trickery (<a href="../texts/DecShowText.php?lang=eng&myID=nov0810&expand=day08">VIII.10</a>). He and the rest of the <em>brigata</em> derive great pleasure from witnessing the deception of a cunning person by one who is even more wiley.</p>
His tale begins with Salabaetto, a merchant arriving in Palermo with goods worth about five hundred gold florins. In his travels through the city he meets Jancofiore, a lady who is skilled in using her feminine ways to obtain a man's wealth. After Salabaetto falls in love with her, she tells him of her recent tragic dilemma: her brother in Messina will lose his head if she does not send one thousand gold florins in the next week. Since she cannot possibly collect such a large sum of money in such a short period of time, good-hearted Salabaetto offers her five hundred florins, which she promises to repay him within the next fortnight. After the deceptive woman takes the money, not only does she fail to repay him, but she no longer spends time with him or treats him with the love and hospitality to which he had become accustomed. Salabaetto departs for Naples without his five hundred gold florins, and tells his friend Canigiano about the fate which has befallen him. Following the advice of the shrewd Canigiano, he returns to Palermo, pretending to have with him a much more valuable cargo than before. On hearing this, Jancofiore repays the money she borrowed from him with the intent of making amends in order to gain even more of his riches. He, however, aware of her plan, borrows one thousand gold florins from her and leaves her with his invaluable cargo, which is actually nothing more than water and tow. In an attempt to deceive Salabaetto a second time, Jancofiore herself is deceived by a more cunning plan.</p>
The pattern of trickery presented here is also used in X.57 of the <em>Kath&aacute; Sarit S&aacute;gara</em>, a collection of eleventh-century Indian tales by Somadeva Bhatta.</p>
This story is about a young merchant named Ishvaravarman who falls in love with Sundar&iacute;, a woman who has been taught by her father to gain wealth through the manipulation of her suitors' affections. Much as in Dioneo's tale, once the young lady obtains her objective she abandons the young merchant. After Ishvaravarman returns home, he complains of the deception to his father who takes him to a wise woman learned in the art of trickery. She gives him a monkey who is trained to swallow money and bring up the exact amount upon request. She then instructs him to go back to Sundar&iacute;, who will of course desire the monkey, and to give it to her in exchange for all the wealth in her house. Sundar&iacute;, unaware that the money has been fed to the monkey, readily accepts the offer. Thinking that the monkey is capable of producing an infinite amount of coins at will, she is unaware that Ishvaravarman has only fed him enough money for two days. On the third day, when the monkey no longer has riches to give, Sundar&iacute; angrily strikes the animal who then attacks her and her mother. After beating the monkey to death, they realize that they have been tricked by the young merchant and are left penniless.</p>
The <em>kath&aacute;</em> contains some interesting parallels to Dioneo's tale. In both stories, a woman uses the pretense of love to win the favor of a suitor and then cunningly takes his riches. The disappointed lover then obtains advice from a wise acquaintance, returns to the woman, and deceptively wins back more wealth than he had initially lost. Regardless of the centuries which separate these two stories, it may be valuable to recognize here the repetition and adaptation of inherited motifs of the literary patrimony of the Occident. This is useful for the scholar of the short story tradition insofar as the medieval tradition relied on a variety of literary resources to an extent still not fully appreciated today.</p>
(D. N. &amp; M. H.) Somadeva Bhatta, <em>Kath&aacute; Sarit S&aacute;gara</em> or <em>Ocean of the Streams of Story</em>. C. H. Tawney, tr. vol. 2. Delhi: Munshiram Manoharlal, 1968. 4-10. </p>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../footer.php';
?>
