<?php
	$selected = "themes_motifs";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Themes &amp; Motifs</a></li>
	<li>The Story of Lisabetta (IV.5)</li>
</ul>
<h2>The Story of Lisabetta (IV.5)</h2>
<p>On the fourth day, in which Filostrato decrees the narration of love stories with unhappy endings, Filomena recounts <a href="../../texts/DecShowText.php?lang=eng&myID=nov0405&expand=day04">the story of Lisabetta and her lover Lorenzo</a>, who is killed by the young girl's brothers after their love affair is discovered. Indeed, the most macabre of the ten stories told in this day, Filomena's narrative contains more details of mutilation (the cutting off of Lorenzo's head by Lisabetta for example) and of decomposition than any other novella of Boccaccio's <em>Decameron</em>. The emphasis on Lorenzo's decomposition and decay, mentioned three times, recalls elements of the plague as described by Boccaccio in the introduction. Although no direct mention of the plague appears after the author's lengthy portrayal at the beginning of the work, echoes of the epidemic are present in the novella of Lisabetta and Lorenzo.</p>
<p>Boccaccio explains that, in addition to the population losses from the pestilence inside the city of Florence, the surrounding countryside was affected as well by the plague's destruction. The group escapes from death's catastrophic effects in the urban center to the comfort of their country estates, even as Pampinea recognizes that the workers in the fields are dying along with their urban counterparts. On the first day, Pampinea strictly orders the servants who leave the company to perform household errands to avoid bringing displeasing news back to the <em>brigata</em>. The plague, and therefore death in general, is the unpleasant news which the group would like to ignore. Therefore, the presence of death on the fourth day could be construed as a reminder to the <em>brigata</em>&nbsp;of possible contamination and death.</p>
<p>Various elements of the introduction can be compared with points of Filomena's narrative. In the introduction, Boccaccio describes the Florentines fleeing the city, carrying flowers around with them to mask the stench of corpses and illness, fearing contamination from the decomposing bodies, and burying plague victims in mass graves. Lisabetta's brothers are merchants who left Tuscany, possibly San Gimignano or even Florence, to travel to Sicily. Lorenzo also left Pisa to travel with them. Messina can be taken as a metaphor for Florence and love as a metaphor for the plague. Discovered in the act of love by Lisabetta's brother, Lorenzo is taken outside the city, killed, and buried in an unmarked grave. This scene gains deeper meaning when compared to the portrayal of events in the Proem: &quot;non bastando la terra sacra alle sepolture... si facevano per gli cimiterii delle chiese, poi che ogni parte era piena, fosse grandissime nelle quali a centinaia si mettevano i sopravegnenti... con poca terra si ricoprieno.&quot; Of course Lorenzo's grave is hidden with new dirt and leaves to hide the murder, but anonymous burial in the ground recalls aspects of the plague.</p>
<p>Lorenzo visits Lisabetta in a dream with torn and rotting clothes, alluding to his decomposition, and tells his lover where to locate his body. Lisabetta finds Lorenzo's body, cuts off his head, wraps it in a beautiful cloth, and gives it a loving burial. She plants basil in the pot over Lorenzo's head, an act which calls to mind the Florentines attempts to lessen the fetor of the plague's victims: &quot;portando nelle mani chi fiori, chi erbe odorifere e chi diverse maniere di spezierie... estimando essere ottima cosa il cerebro con cotali odori confortare, con ci&ograve; fosse cosa che l'aere tutto paresse dal puzzo de' morti corpi e delle infermit&agrave; e delle medicine compreso e puzzolente.&quot; When they leave Messina after disposing of Lorenzo's head, Lisabetta and her brothers go to Naples (&quot;niuna altra medicina essere contro alle pistilenze migliore n&eacute; cos&igrave; buona come il fuggir loro davanti&quot;) fearing that the murder might be discovered or possibly &quot;mossi non meno da tema che la corruzione de' morti non gli offendesse.&quot; Lisabetta's brothers want to get rid of her lover without dishonor in the same way that the women of the <em>brigata</em>&nbsp;desire to leave Florence with honor - the same reason Filomena herself gives Pampinea in the Proem for inviting men to accompany them. As opposed to the Florentines who showed little love for their dead and dying during the plague, Lisabetta instead demonstrated an unabated affection for her lover in caring for Lorenzo's remains, however gruesome. Albeit the account of the plague and Filomena's story differ in many ways, similar plague-referential conditions are found in both.</p>
<p>(C.H.)</p>

<?php
	include 'relatedPages.php'
?>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
