<?php
	$selected = "literature";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Literature</a></li>
	<li><a href="../">Literary Relations</a></li>
	<li>More About the Proem: &quot;Messer Decameron Galeotto&quot;</li>
</ul>
<h2>&quot;Messer Decameron Galeotto&quot;</h2>
<p>In a recent contribution to the journal <em>Heliotropia</em>, Italian scholar Marco Veglia addresses the critical issue of the <em>Decameron</em>'s &quot;surname&quot; (or subtitle): Galeotto, Galehaut, or Gallehault, after the name of a famous character of the Arthurian romances, &quot;go-between&quot; in the adulterous love story of Queen Guinevere, King Arthur's wife, with the Knight Lancelot of the Lake. <br />
Veglia's point of departure is the widely accepted interpretation of the reference to Galeotto first proposed by Lucia Battaglia Ricci in her book <em>Ragionare nel giardino</em>, published in the late 1980s: in short, according to Battaglia Ricci, by nicknaming his book Galeotto, Boccaccio provides a subversive parody of Dante's famous verse, pronounced by the adulterous Francesca da Rimini (Francesca da Polenta) in Inf. 5. 137: &quot;Galeotto fu il libro e chi lo scrisse - A Gallehault indeed, that book and he who wrote it, too.&quot; Boccaccio's parodic intent would be also confirmed by his commentary on Francesca's episode in the <em>Esposizioni</em> (Boccaccio's <em>Expositions on Dante's Comedy</em>) in which he questions the circumstances of Francesca's death as recounted by Dante.</p>
<p>In Battaglia Ricci's interpretation, Boccaccio seems to suggest that his own book of one hundred novelle may have the same function that the <em>Book of Galehaut</em> has in Francesca's episode: it is the reading of a crucial passage in the book that induces Francesca and Paolo to kiss and begin their fatal affair, for which they will both be killed and damned forever in the second circle of hell. In short, notwithstanding its solemn title, reminiscent of Biblical commentaries, Boccaccio's <em>Decameron</em> would be really a love manual in disguise, a playful text to be read for pleasure, as a literary text should be (Boccaccio's guide is indeed Ovid and not Virgil). Boccaccio would thus also provide an apology (or defense) of Chivalric literature and Courtly love, condemned by Dante in Francesca's episode.</p>
<p>According to Veglia, Battaglia Ricci's interpretation is based on a misreading of Dante's text: it is not the book of Galehaut (representative of an entire genre) to be condemned by Dante, but the misuse that Francesca and Paolo make of it. In other words, there are good and bad ways to read, or use a literary text - namely a <em>romance</em> - and acting on it, as Francesca and Paolo do, is certainly the wrong way to (mis)read it (the lovers' mistake, indeed, was to stop reading - &quot;quel giorno più non vi leggemmo avante&quot;; &quot;that day we read no more&quot;). Sin is in the eye of the beholder, in this case in the eye of the reader. The same would apply to the <em>Decameron</em>: it is up to its readers to use it properly, as the Conclusions of the Author confirm. The nickname Galeotto simply warns us of a possible improper use. As for Boccaccio's Expositions, they would simply question the accuracy and verisimilitude of the facts narrated by Dante.<br /> 
In sum, according to Veglia, the episode of Francesca in the <em>Comedy</em> is not a repudiation of the Chivalric world and its literature: it is just a critique of a way of reading it as a source of earthly and not spiritual pleasure (love as a source of moral wisdom and a way to transcendence). Coherently with the whole structure of the <em>Comedy</em>, Dante does not want (his readers) to make the same mistake and fall into the same sin that prevented Lancelot (and Francesca) forever to access the vision of God, e.g. in the case of the Knight in the Arthurian cycle, obtain the Graal: they both &quot;subjected reason to the rule of lust&quot; (Inf. 5. 38-39). Dante prefers Perceval to Lancelot as a model. </p>
<p>The mark, or limit (segno) of reason also informs the rhetorical strategy of the <em>Decameron</em>, as the ethical framework of the hundred novelle embodied in the brigata story shows. The pleasure that the young women and men members of the brigata draw from playful storytelling is not the sinful pleasure (<em>diletto</em>) about which speaks Francesca but rather the pleasure (<em>piacere</em>) mentioned by Virgil in his farewell speech to Dante, at the threshold of Eden, in Purg. 27: &quot;Tratto t'ho io qui con ingegno e con arte;/ lo tuo piacere omai prendi per duce&quot; (&quot;I've brought you here through intellect and art;/ from now on, let your pleasure be your guide&quot;). Pleasure as freedom from desire, in other words: as the regained Edenic condition that preludes to Dante's ascent to Paradise. This, according to Veglia, is consistent with what Pampinea states in the introduction to the <em>Decameron</em>, in order to persuade the other women to leave Florence and move to the countryside: abandoning the city ravaged by the plague is the rational thing to do, because &quot;every person on earth has a natural right to maintain, preserve, and defend her life.&quot; The plan is to have &quot;as much fun as possible, feasting and making merry, without ever overstepping the bounds of reason in any way.&quot; According to Veglia, the feasting and merry making of which Pampinea (and Boccaccio) speaks are not those of Inf. 5 but those of Purg. 27. </p>
<p>In conclusion, according to Veglia there is really no tension or contradiction between the title and the subtitle - or the name and the nickname - of Boccaccio's masterpiece: rather, in their coupling is embedded a sophisticated rhetorical strategy aimed to reconcile the two-faced profile of its Author: the Christian humanist, the friend and disciple of Petrarca, on the one hand (<em>Decameron</em>), and the follower of courtly love filtered and &quot;purified&quot; through Dante, on the other (<em>Galeotto</em>) - a double identity which is also linguistic, reconciling the scholarly Latin with the Romanesque vernacular. This is also what makes the unique profile and <em>modernity</em> of Boccaccio, &quot;Sir Decameron Galeotto,&quot; vis a vis the other two literary crowns. <br />
</p>
<p>(M.R.) Marco Veglia, &quot;Messer Decameron Galeotto: Un titolo e una chiave di lettura.&quot;<em> Heliotropia 700/10. A Boccaccio Anniversary Volum</em>e, ed. by Michael Papio, Milano: Edizioni Universitarie di Lettere, Economia e Diritto, 2013, 21-31. Read online (in Italian): <a href="http://scholarworks.umass.edu/heliotropia/vol8/iss1/6/">http://scholarworks.umass.edu/heliotropia/vol8/iss1/6/</a></p>
<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
<p>
  <?php
	include 'relatedPages.php';
?>
</p>
