<?php
	$selected = "literature";
	require '../../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../../">Main</a></li>
	<li><a href="../../">Literature</a></li>
	<li><a href="../../">Literary Relations</a></li>
	<li><a href="decameron.php">The <em>Decameron</em> and the English Romantics</a></li>
	<li>The Romantic Revival of Boccaccio, Part 2</li>
</ul>
<h2>The Romantic Revival of Boccaccio, Part 2 (or, "Why Was the Decameron Popular in the Romantic Period?")</h2>
<p>The attention devoted to the tales of the <em>Decameron</em> among English poets of the Romantic period is indicative of a certain fundamental yet complex relationship between the aspirations and the themes of Boccaccio's text and those of the poetry of that revolutionary generation of writers.</p>
<p>Like the <em>Decameron</em>, Romantic poetry grew from a certain escapism inspired by the societal ills of a plague, in this case the slower and less immediately fatal plague of industrialization. Boccaccio's own purpose in writing is to &quot;offer some solace...to those who stand in need of it&quot;, both to those women whom he specifically identifies and, more implicitly, to Italians suffering in the face of epidemic. Though the tales themselves are not always light-hearted, the actual adventure of the <em>brigata</em> is presented as an idyllic alternative to the grim realities of the age. Even the tragedy of some of the tales is a pleasurable one in that it exists within an imaginary world and provides an intensity of emotion without actual adverse consequences.</p>
<p>Similarly, many of the Romantic poets saw themselves as bards or poet-prophets, writing &quot;to reconstitute the grounds of hope and pronounce the coming of a time in which a renewed humanity will inhabit a renovated earth on which men and women will feel thoroughly at home&quot; (<em>The Norton Anthology of English Literature</em>, vol. 2, p. 6). Writing amidst the political and social upheaval that was the aftermath of the French Revolution, the Romantics used their imaginative vision to construct a renewal of the world, a celebration of life and its myriad intensities. Like Boccaccio, they did not ignore tragedy and pain, but rather observed it as an outlet for passion and sensation.</p>
<p>In his book <em>The Romantic Quest</em>, Hoxie Neale Fairchild presents a definition of Romanticism which combines two of the strongest elements of the movement, medievalism and naturalism. He compares these two tendencies to one another, likening a return to the ballad-makers and storytellers of the past to a return to the most elemental <em>nature</em> of man and the earth. For the Romantics, he claims, medieval writers &quot;lived before science had chilled and mechanized the mind&quot; (<em>The Romantic Quest</em> 238). They celebrated illusion, fancy, passion, and the variety and spontaneity of life. In their writing they enjoyed the natural world yet did not separate it from the supernatural. Most Romantic poets, at times referring specifically to medieval writers and using their works as source material, also demonstrate these inclinations toward, as Fairchild puts it, &quot;realizing the ideal&quot; and &quot;idealizing the real&quot; (ibid. 245).</p>
<p>This perspective presents a clear association between Boccaccio and those Romantic poets whom he inspired to write original escapist, essentialist literature and to retell his tales. The <em>Decameron</em> represents not only a celebration of the natural and supernatural worlds but an implicit association of both these worlds with certain fundamental and intense human emotions. The gardens of the novel both embody and provide background for passion and love, pleasure and profit, providing a connection between Nature and human emotional intensity. The Romantics also used naturalism to this end, often employing landscapes as initiators for profoundly personal expressions of feeling. Boccaccio also exhibits his own &quot;medievalism&quot; or debt to accepted literary tradition in that, with the alternate title of <em>Prince Gallehault</em> and with a number of the tales themselves, he places himself within a prestigious lineage that includes <a href="../proem_ovid.php">Dante and Ovid</a>.</p>
<p>(It is interesting to note that Samuel Taylor Coleridge's poem &quot;<a href="coleridge.php">The Garden of Boccaccio</a>,&quot; a piece <em>specifically</em> about the spirit of Boccaccio and the <em>Decameron</em>, presents a perfect example of the mesh of naturalism and medievalism. It celebrates the natural world as well as the supernatural, and commends &quot;old Boccaccio&quot; for his vitality and his &quot;joyaunce.&quot;)</p>
<p>In a number of ways, the <em>Decameron</em> can actually be seen as an early example of or a precursor to Romanticism in its most basic form. Not only is it clearly a celebration of life in the face of a grim reality, but it is a specifically and carefully constructed celebration. Fairchild distinguishes between &quot;romanticity,&quot; which is in every human, and the practice of Romanticism. He writes:<br/>
&quot;Romanticity demands an intellectual environment in which the Romantic illusion can be enjoyed without the disturbing awareness that it is illusory. ... When the maintenance of illusion entails a conscious effort which is evasive, defensive, anxious, or defiant, then romanticity becomes romanticism&quot; (ibid. 247).<br/>
Although the &quot;effort&quot; specified here is that of the Romantics themselves, its definition also clearly describes the effort of the <em>brigata</em> to maintain their own illusion and, indeed, the parallel effort of the entire <em>Decameron</em>. Thus, at a fundamental level, the <em>Decameron</em> and the Romantic movement both reflect essential attempts &quot;to find some correspondence between reality and desire&quot; (ibid. 250).</p>
<p>A number of relationships do exist among the texts at a surface level, providing other possible reasons for the Romantic fascination with Boccaccio. Much Romantic poetry, like the <em>Decameron</em>, involves an attention to landscape and the natural world, the importance of intense human emotion and passion, particularly when associated with <a href="../../../themes_motifs/">Love</a>, and an attention to strangeness in beauty or to the exotic. Furthermore, the poets' reverence of Boccaccio may have been related to their feeling of detachment from their more recent literary ancestors, whose rigid craft followed different and more scientific sets of rules.</p>
<p>However, the poets of England's Romantic movement did not retell and discuss Boccaccio only in relation to superficial concerns or as a result of their penchant for medieval literature. Rather, their fascination with the <em>Decameron</em> is likely to have resulted primarily from that deeper essential link between the intentions and themes of Boccaccio's text and of their own writing.</p>
<p>(S. K.) Hoxie Neale Fairchild, <em>The Romantic Quest</em>, New York: Columbia University Press, 1931. </p>

<?php
	include 'relatedPages.php';
?>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../../footer.php';
?>
