<?php
	$selected = "arts";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Arts</a></li>
	<li><a href="../cassoni/">Cassoni and the <em>Decameron</em></a></li>
	<li>A Cassone in II.9 (the novella of Bernab&ograve; and Ambrogiuolo)</li>
</ul>
<h2>A Cassone in II.9 (the novella of Bernab&ograve; and Ambrogiuolo)</h2>
<p>The <em>cassone</em> is a key narrative element in several stories of the <em>Decameron</em>.  An example of this is the important role that such a chest plays in Filomena's second story <a href="../../texts/DecShowText.php?lang=it&myID=nov0209&expand=day02" target="_blank">(II.9)</a>, because without its presence in the bedchamber of Zinevra di Genova, the outcome of the entire sequence of events would have been altered.</p>
<p>The story begins when a Genoese merchant, Bernab&ograve; Lomellin, boasts at length of his wife's beauty, virtues, and accomplishments to a group of merchants in Paris.  He emphasizes her fidelity by stating that even if he went away for ten years or more, she would remain faithful to him.  Ambrogiuolo da Piacenza challenges Bernab&ograve's assertion, voicing his doubts that any woman could resist her desires and remain virtuous for such an extended period of time.  After further debate on the issues of human nature and women's chastity, Bernab&ograve; challenges Ambrogiuolo to a bet, offering his own head if his wife proves unfaithful and demanding one thousand gold florins if he is proved right.  The merchant from Piacenza, however, changes the terms of the bet, demanding five thousand gold florins if he succeeds in proving Zinevra's infidelity.  He states his intention of seducing her within three months, during which time Bernab&ograve; must stay away from his home city.  A contract to this effect is drawn up by the merchants, and Ambrogiuolo leaves immediately for Genova.</p>
<p>Upon his arrival Ambrogiuolo gathers information about the lady, and decides to commission a <em>cassone</em> 'made according to his own specifications' to use as a hiding place.  He then bribes an old woman servant of Zinevra's to ask permission for the <em>cassone</em> to stay for a day or two in her bedroom, stating that it is on its way to another place.  That night, once he thought the lady was asleep, Ambrogiuolo pried open the <em>cassone</em> with tools that he had with him and observed the inside of her bedchamber.  Not only did he memorize the details of the furnishings in the room, he also saw a mole below the lady's left breast.  He removed a purse, some rings, and a long cloak from another <em>cassone</em> (the term used by Boccaccio is <em>'forzier')</em> in the bedroom to use as further proof of Zinevra's 'infidelity.'</p>
<p>On the morning of the third day, the old woman has the <em>cassone</em> removed and Ambrogiuolo pays her off, returning to Paris to claim his prize money.  Upon his arrival he finds Bernab&ograve; and the other merchants who had witnessed the wager, and announces that he has proof of his own victory.  He then proceeds to describe Zinevra's bedroom, and shows them the trinkets of hers that he had taken.  At first Bernab&ograve; suspectes that Ambrogiuolo had come about this knowledge by paying off one of her servants, as was indeed the case, but when the merchant was able to tell Bernab&ograve; the precise location of his wife's mole, the Genoese admitted his defeat and paid over the five thousand florins.</p>
<p>The result of this trick was that Bernab&ograve; flew into a rage and journeyed immediately home to Genova.  Before he had arrived, he decided to send one of his servants ahead, instructing him to fetch his wife and murder her on the way to their country estate.  However, the lady was so terrified when the servant got out his dagger to kill her for no apparent reason that she convinces him to let her go free.  She gives him her outer garments, so that he can pretend to have carried out his duty, and she sought refuge in the nearby cottage of an old woman.  Zinevra dresses up like a sailor and becomes a cabin boy on a Catalan ship, on which she traveled to Alexandria, under the assumed name of Sicurano da Finale.  Zinevra/Sicurano is then referred to by Boccaccio with masculine pronouns and she assumed male characteristics during this phase of cross-dressing.  Over the course of his adventures as a sailor he meets up with Ambrogiuolo da Piacenza, who recounts to him of his conquest of Donna Zinevra of Genova.  Zinevra/Sicurano then understands why her husband had wanted her killed, and she sets out to see that Ambrogiuolo be punished for his lies.  She arranged things so that both Ambrogiuolo and Bernab&ograve, who by this time had been reduced to poverty, appeared before the Sultan, and Ambrogiuolo was pressured to tell the truth about how he had won the five thousand florins.</p>
<p>Sicurano/Zinevra berates both men to the Sultan, Ambrogiuolo for his lies, and Bernab&ograve; for believing another man's lies over his own wife.  However, before revealing the truth, Sicurano/Zinevra gets an assurance from the Sultan that only Ambrogiuolo will be punished for his treachery, thus ensuring freedom for the husband that she has evidently decided to forgive.  After revealing her true identity, Zinevra is awarded all of Ambrogiuolo's riches, thus she and Bernab&ograve; are able to return to a lavish lifestyle in Genova. If it had not been for his plan to hide in a <em>cassone</em>, Ambrogiuolo would not have succeeded in winning the wager and would have escaped a gruesome death.</p>
<div class="image_center">
	<img src="../images/toscani_cassone.jpg"  alt="Photo of cassone panel depicting novella II.9" />
	<span>Cassone panel depicting the first part of II.9, Giovanni di Francesco Toscani, attributed, c.1425, National Gallery of Scotland, Edinburgh</span>
</div>

<p>Not only does the narrative of this story depend on a <em>cassone</em>, this novella also inspired at least one <em>cassone</em> painter in the fifteenth century, Giovanni di Francesco Toscani, to depict the story on a pair of marriage chests.  The first half of this pair, in the collection of the National Gallery of Scotland in Edinburgh, depicts the main events of the first part of the story.  Like most <em>cassone</em> panels of this period, the different scenes painted on this panel, when read from left to right, create a continuous narrative flow.  At the far left we see the merchants in discussion around a table, and to their right is Ambrogiuolo bribing Zinevra's maid.  Moving right again we see a man carrying a <em>cassone</em> into the lady's house, and at the far right we see him emerging from this <em>cassone</em>, observing the lady under her bedsheets, and reentering the chest.  The second half of this pair, the location of which is unknown at this time, depicts the final events of the novella.<sup><a href="#1">1</a></sup></p>
<p>Before beginning her story, Filomena tells the brigata that her novella provides proof of the proverb that 'a dupe will outwit his deceiver' and that it will 'teach you to be on your guard against deceivers.'  Beyond serving as a general warning against deception, the moral of this story is that husbands should trust in their wives' fidelity and honesty.  This moral is consistent with the purpose of <em>cassone</em> imagery-to inspire husband and wife to lead moral lives and maintain happy marriages and households.  However, it is unusual that the message of this story seems to be directed towards the husband, who usually commissioned such painted chests, rather than for the wife, who was normally the primary student of lessons painted on <em>cassoni</em>.
<p>(C.C.)</p>

<hr />

<ol class="footenotes">
	<li name="1">The second cassone was sold at Phillips Auctioneers, London in July 1999.&nbsp;<a href="#top1">&#8617;</a></li>
</ol>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
