<?php
	$selected = "arts";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Arts</a></li>
	<li><a href="../cassoni/">Cassoni and the <em>Decameron</em></a></li>
	<li>What are cassoni?</li>
</ul>
<h2>What are cassoni?</h2>
<p><strong>(Excerpted from Caroline S. Cook's senior honors thesis:<em> &quot;Sheba and Solomon as Bride and Groom: The Cassone in Fifteenth Century Florence,&quot; </em>Brown University, April 2001)</strong></p>
<p>This is the story of decorated wooden boxes that played an important role in the society of early modern Italy.  These boxes, known today as <em>cassoni</em> (marriage chests)<a name="top1"></a><sup><a href="#1">1</a></sup>,  had several utilitarian and symbolic functions within Italian culture from medieval times until as late as the seventeenth century.  Up until the early sixteenth century the terms <em>forziere</em> or <em>cassa</em>, rather than <em>cassone</em>, were generally used to refer to these objects. However, it was in fifteenth-century Florence that these chests were transformed from simple wooden objects into ornately gilded, painted, and carved containers imbued with symbolism.  <em>Cassoni</em> served a wide variety of functions within the society of Renaissance Florence. In private homes, <em>cassoni</em>were used as seats, tables, makeshift beds, as well as a serving as a container for belongings such as clothing, linens, and other personal objects.  They were an essential piece of virtually every household's furniture, and even families of limited means would have had at least one such chest.  Beyond the domestic sphere, <em>cassoni</em> were also used as file-cabinets, for storing documents in city government buildings, or as makeshift closets, holding clerical vestments in churches.<a name="top2"></a><sup><a href="#2">2</a></sup>  However, perhaps the most public usage of <em>cassoni</em> was in the role that they played in the often lengthy and complex series of marriage rites that were practiced in fifteenth-century Florence.</p>

<div class="image_center">
	<img src="../images/cassone2b.jpg" width="190" height="145" alt="Drawing of a cassone" />
	<span>Drawing of a typical fifteenth century cassone</span>
</div>

<p>The <em>cassoni</em> of Renaissance Italy have been divided into three main categories, according to the method of their decoration.  There were those inlayed with designs and images, the <em>intarsia</em> technique, those decorated with sculptural reliefs in gesso, the <em>pastiglia</em> technique, and those adorned with painted panels, which seem to have been the most popular in the quattrocentro.  An analysis of the narratives painted on the front panels of <em>cassoni</em> reveals the many layers of symbolic meaning held in these objects.  The <em>cassoni</em> panels serve as visual texts that have much to tell regarding attitudes about the role of marriage and the status of women in fifteenth-century Florentine society. The original function of <em>cassoni</em> within Renaissance Italian marriage rituals was to avoid the ostentatious display of wealth that occurred when the various pieces of the bride's dowry were carried in full public view from her father's house to that of her new husband in the marriage procession.<a name="top3"></a><sup><a href="#3">3</a></sup>  However, <em>cassoni</em> quickly became lavishly decorated objects in their own right, thus becoming symbols of wealth for the families that commissioned their decoration.</p>

<div class="image_center">
	<img src="../images/cassone_1.jpg" width="190" height="124" alt="Drawing of a portable cassone" />
	<span>Portable cassoni or coffers were often transported like this</span>
</div>

<p>A pair of chests would have been commissioned by the groom or his family, or, more rarely, by the bride's father, for the bride on the occasion of a marriage between members of important and wealthy Florentine families.  The primary utilitarian function of the <em>cassone</em> within the marriage ritual in the first half of the fifteenth century was to transport the girl's <em>donora</em>, the collection of linens, clothes and objects known today as a trousseau, from her father's house to that of her husband.  In this way, <em>cassoni</em> took on the important and symbolic role of transporting the bride's share of her own family's patrimony, in the form of her dowry, from the house of her birth to that of her new husband.  Since the dowry was effectively a daughter's inheritance, in most cases she would have no legal right to her family's wealth after that point,  its transferal to her husband's household was symbolic of the severing of her familial ties.<a name="top4"></a><sup><a href="#4">4</a></sup></p>

<p><em>Cassoni</em> participated in marriage processions, which grew increasingly expensive and formal over the course of the fifteenth century, not simply as objects being carted from one location to another, but instead as protagonists, accompanying the bride in the absence of her father.<a name="top5"></a><sup><a href="#5">5</a></sup>  The marriage chests were tangible reflections of the wealth, power, and influence of the two families that were being united in an important alliance known as a <em>parentado</em>. The creation of new such <em>parentadi</em> through marriages, with women effectively serving as a sort of 'social glue,' was an essential way for groups of men to ally themselves with one another for business and political purposes.<a name="top6"></a><sup><a href="#6">6</a></sup>  These alliances also served to counter-balance the financial difficulties that often arose when fathers had to accumulate the cash resources for their daughters' dowries.  As the marriage chest made its way through the city along with the rest of the wedding procession, the citizens of Florence effectively became an audience to the often theatrical display of the bride, her family, and her (usually exclusively) female companions as they were escorted from her home by the groom and his entourage, usually exclusively male.</p>

<p>The display of wealth was strictly regulated by Florentine sumptuary laws, which reflected the growing republican sentiments of the city.  These sumptuary laws placed limitations on other aspects of wedding pageantry by regulating the sum of money that could be spent on the dress of the bride as well as limiting the number of courses that could be served in a wedding feast.<a name="top7"></a><sup><a href="#7">7</a></sup>  Elaborate marriage processions stopped about 1470, partly in response to these sumptuary laws and also due to changes in custom.<a name="top8"></a><sup><a href="#8">8</a></sup> <em>Cassoni</em> were still in use after this change, but instead of participating in the bride's transition from the home of her birth to that of her husband, they would have been waiting in a newly redecorated nuptial chamber for her when she arrived.<a name="top9"></a><sup><a href="#9">9</a></sup></p>

<p>Over the course of the fifteenth century, while the <em>cassone</em> retained its functional capacity as a container for clothes and linens, it also acquired the role of a status symbol, promoting the image of the father or groom who had commissioned the chest or chests.  This heightened status meant that some of the most well-known quattrocento painters, not simply unidentified craftsmen or painters, created and decorated these objects.  Giorgio Vasari explicitly writes of the popularity of <em>cassoni</em> in his biography of Dello Delli:</p>

<blockquote>The citizens in those times used to have in their apartments great wooden chests in the form of a sarcophagus, with the covers shaped in various fashions, and there were none who did not have the said chests painted...And for many years this fashion was so much in use that even the most excellent painters exercised themselves in such labours, without being ashamed, as many would be to-day, to paint and guild such things.<a name="top10"></a><sup><a href="#10">10</a></sup></blockquote> 

<p>Indeed, modern attributions have confirmed that artists considered by scholars to be noted players in the chronology of so-called 'monumental art,' such as Paolo Uccello, Domenico Veneziano, Masaccio, Benozzo Gozzoli, and Sandro Botticelli also carried out commissions for <em>cassoni</em> panels, or related forms of secular art like <em>deschi da parto</em> (birth trays) or <em>spalliera</em> panels (wainscoting).<a name="top11"></a><sup><a href="#11">11</a></sup></p>

<h3 class="break" name="house">Cassoni in the Renaissance household</h3>

<div class="image_left">
	<a href="pappagalli.php"><img src="../images/pappagalli.gif" height="120" width="136" align="left" alt="Interior of the Sala dei Pappagalli"></a><br />
	Click for larger image.
</div>
<p>For the first time, during the fifteenth century, whole rooms were redecorated at one time, becoming in effect a single visual unit made up of painted ceilings, walls, and decorated furniture.<a name="top12"></a><sup><a href="#12">12</a></sup>   The Sala dei Pappagalli in Palazzo Davanzati, now the Museo della casa fiorentina antica, is a good example of such a room where <em>cassoni</em> are integrated into the decorative scheme. Workshops like that of Apollonio di Giovanni and Marco del Buono played an important role in this decorative trend not only because of the large output of <em>cassoni</em>, but also because of his painting of ceilings, walls, and <em>spalliera</em> panels, the first objects painted to be viewed at eye-level in a secular context.<a name="top13"></a><sup><a href="#13">13</a></sup></p>

<p>Leon Battista Alberti coined the term <em>masserizia</em>, originally meaning 'savings,' to refer to all household objects, and charged it with moral meaning, emphasizing the necessity for the preservation of household possessions as symbols of the reputation of the family and the bonds of affection that held it together.<a name="top14"></a><sup><a href="#14">14</a></sup>  By the mid-fifteenth century, many Florentines had opened accounts in their ledgers for the specific purpose of keeping track of the acquisition of household objects, referred to universally as <em>masserizia</em>.<a name="top15"></a><sup><a href="#15">15</a></sup> The records, inventories, and accounts left over by many bankers, merchants, and heads of household reveal the important role that the consumption of objects, especially those bought for these household interiors, played in Renaissance Florence. The meticulous nature of these records also points to a growing 'spirit of possessiveness' that characterized Florentine society at this time.<a name="top16"></a><sup><a href="#16">16</a></sup>  The economic significance of the purchase of objects for the <em>palazzo</em> explains the Florentine's heightened interest in recording such expenditures.  In fact, the acquisition of furniture for the bridal chamber was often not only the largest single purchase of a Florentine man, excluding the construction of a palace or villa, but was also usually his first time as a patron of the arts.<a name="top17"></a><sup><a href="#17">17</a></sup>  Therefore, these objects symbolized the independence of an up and coming Florentine man, and sometimes signaled his formation of an autonomous household and his emancipation from his father.<a name="top18"></a><sup><a href="#18">18</a></sup>  The purchase of extravagant <em>cassoni</em>, marriage beds, <em>deschi da parto</em> and <em>spalliere</em>, were all essentially displays of wealth that solidified the <em>parentado</em> alliance between the groom and his family and the family of the bride.</p>

<p>It was inside the private domestic world that most middle and upper class Florentine women found themselves during this period.  Because of the restrictions placed on women at this time, the only arena that they could really call their own was the domestic one.  Husbands and fathers built the family <em>palazzi</em>, conducted their business out in the city, probably participated in civic government, and traveled to other cities on business bringing home objects for their houses from wherever they had been.<a name="top19"></a><sup><a href="#19">19</a></sup>  At different times it became fashionable, for instance, to own some of the best silk from Lucca, the finest ceramic work from Spain, glasswork from Venice, or even a painting or tapestry from the Low Countries.  Because they possessed the economic control of the household, men were almost always the commissioners of objects of art and architecture. Men ordered, paid for, and perhaps even determined the pictorial subject matter of <em>cassoni</em> and <em>deschi da parto</em>, secular objects made exclusively for the use of women. Therefore, a woman, especially a young bride in the home of her parents-in-law, would not have had much control over the only space that could even vaguely be deemed 'hers.' However, Thornton attributes the upper-class Renaissance woman with more decision-making power, at least in terms of her own domestic realm, than do most other scholars.  He speaks of women in courtly circles independently commissioning household objects and decorations and tellingly ends his book The Italian Renaissance Interior, 1400-1600 with a section entitled 'Women's Influence,' in which he asserts that women had a profound, if less obvious, affect on the household environment.<a name="top20"></a><sup><a href="#20">20</a></sup> It is unfortunate that there are few records that reveal or prove the initiatives and actions of women at this time.  Widows, however, present an anomalous example of wealthy women who can be documented as having shaped and changed their own world, in the domestic sphere and beyond.</p>

<p><em>Cassoni</em> occupied a central place in the household of a wealthy Florentine family during the fifteenth century.  They served as tangible symbols of marriage alliances, which themselves played a fundamental role within Florentine society on many levels.  However, over the course of the fifteenth century these objects also gained a status far beyond that of a functional household object.  They became visual evidence of the wealth, power and prestige of the Florentine families who possessed them.</p>



<hr />

<ol class="footenotes">
	<li><a name="1"></a>Thornton, Peter. &quot;Cassoni, Forzieri, Goffani, and Cassette: Terminology and Its Problems.&quot; <em>Apollo </em>120 (1984) 247. The term <em>cassone</em> was rarely used before 1500; instead, <em>forziere</em> was the commonly used term in the 1400s.&nbsp;<em><a href="#top1">&#8617;</a></em></li>
	<li><a name="2"></a>Faenson, Liubov. <em>Italian Cassoni from Soviet Museum Collections</em>. (Leningrad: Aurora Art Publishers, 1983) 7.&nbsp;<em><a href="#top2">&#8617;</a></em></li>
	<li><a name="3"></a>Witthoft, Brucia. "Marriage Rituals and Marriage Chests in Quattrocento Florence." <em>Artibus et Historiae</em> 5 (1982), 51.&nbsp;<em><a href="#top3">&#8617;</a></em></li>
	<li><a name="4"></a>Hughes, Diane Owen. 'From Bride-Price to Dowry in Mediterranean Europe,' <em>Journal of Family History</em> 3 (1978): 279 and Klapisch-Zuber, Christiane. &quot;The Griselda Complex: Dowry and Marriage Gifts in the Quattrocento.&quot; in <em>Women, Family and Ritual in Renaissance Italy</em>. trans. Lydia Cochrane. (Chicago and London: Univerity of Chicago Press, 1985) 216.&nbsp;<em><a href="#top4">&#8617;</a></em></li>
	<li><a name="5"></a>Witthoft, 47. &quot;The girl's father did not accompany her on the trip to her new house...a symbol of forcible abduction.&quot;&nbsp;<em><a href="#top5">&#8617;</a></em></li>
	<li><a name="6"></a>Gregory, Heather. &quot;Daughters, Dowries and the Family in Fifteenth-Century Florence.&quot; <em>Rinascimento</em> 27 (1987), 231. <em><a href="#top6">&#8617;</a></em></li>
	<li><a name="7"></a>Hughes, Diane Owen.  &quot;Sumptuary laws and Human Relations in Renaissance Italy.&quot; In <em>Disputes and Settlements: Law and Human Relations in the West</em>. John Bossy, ed.  (Cambridge: Cambridge University Press, 1983) 74. <em><a href="#top7">&#8617;</a></em></li>
	<li><a name="8"></a>Klapisch-Zuber, 219.&nbsp;<em><a href="#top8">&#8617;</a></em></li>
	<li><a name="9"></a>Baskins, Cristelle. <em>Cassone Painting, Humanism and Gender in early modern Italy.</em> (Cambridge: Cambridge University Press, 1998) 4 and Ellen Callmann. &quot;Apollonio di Giovanni and Painting for the Early Renaissance Room.&quot; <em>Antichit&agrave; viva</em> 27 no. 3-4 (1988).&nbsp;<em><a href="#top9">&#8617;</a></em></li>
	<li><a name="10"></a>Vasari, Giorgio. <em>Lives of the Painters, Sculptors and Architects.</em> trans. Gaston du C. de Vere. (New York: Alfred A. Knopf, 1912) 267.&nbsp;<em><a href="#top10">&#8617;</a></em></li>
	<li><a name="11"></a>Ferrari, Maria Luisa. <em>Cassoni Rinascimentali.</em> (Milan: Arti Grafiche Ricordi, 1964) 3.&nbsp;<em><a href="#top11">&#8617;</a></em></li>
	<li><a name="12"></a>Callmann 1988, 5.&nbsp;<em><a href="#top12">&#8617;</a></em></li>
	<li><a name="13"></a>Callmann 1988, 13.&nbsp;<em><a href="#top13">&#8617;</a></em></li>
	<li><a name="14"></a>Goldthwaite, Richard. <em>Wealth and the Demand for Art in Italy 1300-1600</em>. (Baltimore: Johns Hopkins University Press, 1993) 210-11 and Alberti, Leon Battista. <em>The Family in Renaissance Florence</em>. trans. Renee Neu Watkins (Columbia: University of South Carolina Press, 1969), Book Three.&nbsp;<em><a href="#top14">&#8617;</a></em></li>
	<li><a name="15"></a>Goldthwaite 1993, 211.&nbsp;<em><a href="#top15">&#8617;</a></em></li>
	<li><a name="16"></a>Ibid., 210.&nbsp;<em><a href="#top16">&#8617;</a></em></li>
	<li><a name="17"></a>Ibid., 228.&nbsp;<em><a href="#top17">&#8617;</a></em></li>
	<li><a name="18"></a>Lydecker, John Kent. <em>The Domestic Setting of the Arts in Renaissance Florence</em> (Baltimore: Johns Hopkins University Press, 1987) 145.&nbsp;<em><a href="#top18">&#8617;</a></em></li>
	<li><a name="19"></a>Callmann, Ellen. <em>Beyond Nobility: Art for the Private Citizen in the Early Renaissance</em> (Allentown, PA: Allentown Art Museum, 1980) ix.&nbsp;<em><a href="#top19">&#8617;</a></em></li>
	<li><a name="20"></a>Thornton 1991, 358.&nbsp;<em><a href="#top20">&#8617;</a></em></li>
</ol>

<p><a href="bibliography.php"><em>Bibliography</em></a></p>

<p>(C. C.)</p>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
