<?php
	$selected = "plague";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Plague</a></li>
	<li>Causes</li>
	<li>Plague Historians in Lab Coats</li>
</ul>
<h2>Plague Historians in Lab Coats</h2>
<p>In his review article, &quot;Plague Historians in Lab Coats,&quot; published in 2011 in the journal <em>Past and Present</em>, Lester K. Little states that &quot;the moment seems particularly opportune to take stock of the[...] rapidly changing developments in our understanding of plague’s lengthy history.&quot; The word plague, Little writes, &quot;really does refer to a specific disease, commonly called bubonic plague or in scientific parlance Yersinia pestis.&quot; In modern times, &quot;the single most important advance in ... plague studies took place in 1894 in Hong Kong:... Alexandre Yersin, a Swiss-born naturalized French citizen who had distinguished himself by his work on diphtheria at the [Louis] Pasteur Institute, had abandoned a promising career in Paris to serve as a medical officer in Indo-China.&quot; He received the posthumous honour of identifying, and naming, the plague pathogen: Yersinia Pestis. Yersin and his scientists competitors confidently asserted &quot;that so many earlier epidemics&quot; such as, for example, the fourteenth-century pandemic, also consisted of plague. Questioning this assertion, Little writes: &quot;the question should no longer have been whether what we can see before us under a microscope is the same disease as the ones we can read about in historical accounts, but whether past epidemics, or some or any part of them, were the same as what we now have indisputably before us.&quot; The issue, in other words, is whether we can identify pre-laboratory diseases with diseases for which microbiological advances have identified an agent in laboratory. Citing another historian of the plague, Andrew Cunningham, Little writes: &quot;The new cause-identified disease, differs so fundamentally from the old symptom-defined disease that historians inevitably err when they attempt to identify pre-laboratory diseases as if they were laboratory diseases.&quot; In other words, the scientific paradigm shift of the late nineteenth century would establish &quot;an unbridgeable gap between past plague and our plague.&quot; (p. 270)</p>
<p>Outbreaks of disease believed to be plague can be grouped into two major historically documented pandemics (in addition to the Asian pandemic that led to the identification of the pathogen): (1) the Plague of Justinian (or Justinianic Pandemic), 541–750, (named after the Roman emperor in whose reign it broke out and spread through much of the Middle East and Europe); and (2) the Black Death, &quot;a name that many historians restrict to the massive mortality throughout Europe between 1347 and 1353 but is better understood as a pandemic that began in Central Asia in the 1330s, subsequently spread through Europe and the Middle East starting in the late 1340s, and made frequent returns in those regions for over four centuries.&quot; (p. 271) &quot;An investigation undertaken in 1898 first in Bombay and then in Saigon by Paul Simond, another Pasteur disciple, identified the principal vector of Yersinia pestis to be a flea, Xenopsylla cheopis, whose preferred host is the black rat, Rattus rattus.&quot; Now, major breakthroughs in molecular biology late in the twentieth century provided the tools for constructing the evolutionary history of plague and made possible &quot;to tie distinct strains of plague to each of the three pandemics&quot;; finally, in 2001 &quot;a large consortium of English scientists produced the first complete genome ...of Yersinia pestis.&quot; (p. 272). End of story? Hardly.</p>
<p>Historians had already questioned the scientific narrative underlying the history of Y. P. In the 1980s, an entomologist, Graham Twigg, &quot;found that what he knew of the physiology of Xenopsylla cheopis [the flea] did not match up, particularly on grounds of climate and temperature, with what he had read about the Black Death in England.&quot; Another historian  (who taught also at Brown for a period), David Herlihi, in his book The Black Death and the Transformation of the West (1997), &quot;agreed with many of Twigg’s reservations about the prevailing view, having been particularly struck by the absence of any mention of rats in the Continental sources that he knew so well.&quot; Demographic historians expressed other reservations and soon alternative theories started to take shape, such as those which proposed anthrax as an alternative to Y. P. for the Black Death (Twigg), and those that pointed to a now-extinct ebola-like haemorrhagic disease (Scott and Duncan). </p>
<p><strong>New developments: Forensic Medicine and the Plague Wars</strong></p>
<p>In 1998, a group of five molecular biologists at the Faculty of Medicine in Marseille, published a paper entitled: &quot;Detection of 400-year-old Yersinia pestis DNA in Human Dental Pulp: An Approach to the Diagnosis of Ancient Septicemia.&quot; As Little writes: The hypothesis of the Marseille scholars was that the dental pulp of unerupted teeth would be a lasting refuge of Y. P. and would be a suitable material on which to base molecular detection of the bacterium.&quot; (p. 274) Thanks to the discovery of two mass graves at two different sites of urban development in Provence, both used according to historical records to bury victims from plague quarantine hospitals, and to a later discovery of remains from a fourteenth-century site in Montpellier, these scientists were able to identify aDNA (ancient DNA) of Y.P. and concluded that indeed the Black Death was Y.P. However, in the year 2000, Science magazine published a letter by an Oxford scientist, entitled &quot;Ancient DNA: Do It Right or Not at All,&quot; that radically questioned the findings for lack of controls. Soon a fierce competition among teams of microbiologists trying to confirm or debunk the findings of the Marseille group erupted. A German team, based in Munich, confirmed to have found evidence of Y.P. in remains they examined from regions for which, however, no historical records of the presence of Y. P. exist, complicating the issue even further. The German team also extended the time of their findings back several centuries, thus affecting also the so-called Justinian plague. Another German team, based in Tübingen, shifted the scientific procedures of the search for evidence of Y.P. from the trace of pathogens to the trace of antigens in the remains they analyzed from a mortuary chapel in Stuttgart which had experienced plague epidemics from the start in 1348-49. &quot;The antigen approach appears again, and again successfully, in an investigation published in 2009 concerning putative plague victims of the late sixteenth and early seventeenth centuries from sites both in and near Poitiers&quot; (in France). (p. 280). </p>
<p>&quot;Such was the state of things in the autumn of 2010 when an international group directed from Mainz took the path of widespread co-operation, lucid explanation of context, acknowledgement and inclusion of dissenting views, and integration of different methods of research. They examined teeth and bones from seventy-six skeletons from putative plague pits at five sites, dated from the fourteenth to the seventeenth centuries on the basis of carbon-14 dating and/or archaeological evidence. The sites chosen were Hereford in south-western England, Saint- Laurent-de-la-Cabrerisse in south-western France, Bergen op Zoom in the Netherlands, Augsburg in Germany, and Parma in Italy.&quot; (p. 281) In short, the authors  &quot;claim to have confirmed that Y. P. caused the Black Death and later epidemics all over Europe in the course of four centuries, and to have found that at least two variants of the pathogen had found their way into Europe. Another international study followed, a historical geography that traces Y. P. from its origins to all the various places on earth where it is now known to be present (this required scientists to work in parallel, adopting rigorously similar procedures in various countries, given strict prohibitions against shipping samples of Y. P. across borders). What we learn from their results is that the place where all this began was China, although the authors qualify the location in these notably cautious phrases: ‘Y. P. probably evolved in China’, and Yersinia’s global evolutionary history originated ‘in the vicinity of China’. (p. 282) We are thus reaching a kind of problematic consensus (no absolute certainty) about the geographical origins of the plague:</p>
<p>&quot;There is no contradiction between this conclusion and the texts that document the beginnings of the three great world pandemics of plague. The entire modern world witnessed the diffusion of the third pandemic by steamship from Hong Kong to major ports all over the globe between 1894 and 1900, so there is doubt about where that one started. The linking of Eurasia from the Pacific Ocean to the Black Sea by the Mongols in the thirteenth century guaranteed the rapid spread of the second pandemic from Central Asia to the Middle East and Europe in the 1330s and 1340s. Surely there is no necessary connection, and least of all a contradiction, between where plague first appeared and where these two pandemics first broke out... As for where the first pandemic spread to, multiple sources document its eastward movement across Mesopotamia and into Persia. But a few historians tell us that the Justinianic Pandemic reached all the way to China in the year 610, and some have maintained that this marked the moment when plague made its first appearance in that land.... We cannot dismiss the possibility that the Plague of Justinian spread from the Mediterranean region to China, but this source (an encyclopedic compendium of medical knowledge) surely offers no proof of such an assertion&quot; (284)</p>
<p>The scientific search for the actual cause of contagion for Y.P. is, however, still on (various experiments about different types of carrier for the pathogen, different types of human and animal fleas, have reopened the case). We can however draw a methodological lesson from all this: &quot;the days of diagnosing past illnesses solely upon the basis of written sources are numbered if not entirely gone. And so, too, given that laboratory and ecological studies have implicated many other mammal and flea species in maintaining plague transmission, plague historians can henceforth safely retire their exclusive fixation upon Rattus rattus and Xenopsylla cheopis. But, even while these venerable orthodoxies of plague history are being dismantled in scientific laboratories, historians still have much to contribute, because epidemiological analysis of past epidemics based upon written accounts and records, rather than being replaced by laboratory identification ... and experimentation, is more important than ever precisely because it can now be done in tandem with biomedical science.&quot; (p. 286)</p>
<p>Lester Little concludes: &quot;What we can assuredly affirm is that we have been witnessing for over a decade an ongoing drive by molecular biologists, geneticists and entomologists that furthers a tradition started by pioneers of medical microbiology over 115 years ago. Even while having what some of them may consider more pressing issues on their minds, they have been solving historical problems that we historians working in our standard nineteenth century ways have been incapable of solving.&quot; (p. 290)</p>
<p>(M.R.) Lester K. Little, &quot;Plague Historians in Lab Coats,&quot; Past and Present, no. 213 (November 2011) pp. 267-290.</p>
<!-- End -->
<!-- Bottom links -->
<?php
	include 'relatedPages.php';
?>
	
<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>