<?php
	$selected = "plague";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Plague</a></li>
	<li><a href="http://www.brown.edu/Departments/Italian_Studies/dweb/plague/causes/sci_causes.php">Causes</a></li>
	<li>A Plague on Bohemia. Mapping the Black Death</li>
</ul>
<h2>&quot;A Plague on Bohemia. Mapping the Black Death&quot; (Excerpts)</h2>
<p><strong>Introduction</strong>.</p>
<p>The Black Death itself —understood conventionally as the initial epidemic of 1347–52 — seems to have left Bohemia unscathed. This historiographical essay challenges that consensus, both by offering a new evaluation of the fourteenth-century evidence and by tracing the process by which the consensus developed. The aim is not simply to clear up a curious but ultimately marginal detail in the story of the Black Death. The implications of the case of plague in Bohemia extend beyond regional history or the history of the Black Death. This is a story that leads us in several directions. To tell it, we must confront the influential role of popular history in shaping the questions and assumptions of scholars; the failure of English-language studies to integrate the results of continental plague scholarship; the challenges of extracting mortality estimates from patchy medieval sources; and even the struggle to place the Black Death within broader historical narratives. Furthermore, the story of Bohemia’s experience of the Black Death invites us to explore the power of cartography to convey historical arguments. After all, the most influential account of plague in Bohemia has been told by a map.</p>
<p><strong>The Power of A Map</strong></p>
<p>Élisabeth Carpentier’s penetrating 1962 <em>Annales</em> article remains a monument in the study of the Black Death. While drawing together many strands of previous scholarship, she identified central questions to be addressed by future studies, especially local studies. She also offered a ‘kind of film of the plague’s march’ across Europe in the form of a <a href="../../images/plague/carpentier1.jpg" target="_blank">map</a>. Two prominent features of her map catch the eye: first, the wavy lines tracking the disease’s inundation of the Continent in six-month increments; and second, a few blessed cities and regions that were, according to the map’s legend, ‘partly or entirely spared by the plague’. These include the cities of Milan, Nuremberg and Liège, small regions in the Pyrenees and the Low Countries, and a large part of east Central Europe. A more complete map, Carpentier suggested, would depict the uneven mortality that later local studies would presumably uncover. The influence of Carpentier’s map has been astounding.</p>
<p>[In his essay, Mengel goes on to list all the influential publications about the history of the plague that have reproduced and relied upon Carpentier's map, then moves on to analyze other attempts by historians to map the Black Death].</p>
<p>Ernst Buchholz’s 1956 <a href="../../images/plague/buchholz1.jpg" target="_blank">map</a>, reprinted in 1965, used arrows to show the spread of the disease from city to city and also indicated the month and year of its arrival at each location. A few later map-makers did follow the cartographic strategies of Martin and Buchholz in order to represent the transmission of disease from point to point. Like maps of military campaigns, their arrows and dates trace the plague’s conquest of Europe one city at a time. These maps offer no indication that the mortality rate might have varied across the vast majority of Europe’s area that falls under the epidemic’s coloured or shaded sway. No one, in other words, has provided the more detailed map of varying Black Death mortality which Carpentier proposed.</p>
<p><strong>The Bohemia exception: Rats and Comets</strong></p>
<p>Writing the following year (1963) in the pages of the same journal, the Czech historian Frantisek Graus objected to the misleading impression of certainty communicated by Carpentier’s map. In other words, Graus objected to the map’s unspoken but unavoidable claim that the kingdom of Bohemia experienced the Black Death in a qualitatively different way than the rest of Europe did, a claim that called for some explanation: Graus crammed the footnotes of his dense, five-page article with fourteenth-century evidence of plague in the Bohemian kingdom. Together these and other sources point not to one unique epidemic but instead to periodic outbreaks of disease (pestilencia) in Bohemia both before and after 1348, including a ‘magna pestilencia’ in 1380. For Graus, there was no special Bohemian experience crying out for historical interpretation. Graus’s other conclusion adumbrated a larger argument about the historical significance of the Black Death itself. For him the Black Death was no isolated phenomenon, but rather one of an entire series of late medieval epidemics (of various, unspecified diseases), famines and other disasters. His carefully supported claims about the Black Death in Bohemia should have shaped any subsequent discussion. Instead they have been largely ignored, particularly by anglophone scholars.</p>
<p>Sir Fred Hoyle, the provocative British astronomer, invoked the [...] supposed exceptional character of Bohemia in support of an entirely different thesis. Hoyle and his collaborators reproduced Carpentier’s map to support their theory that the pathogen responsible for bubonic plague was introduced separately to numerous regions — not by rats, but by comets. Bohemia and places like Milan and Liège (similarly singled out on Carpentier’s map) were thus spared the bubonic plague simply because comet-borne pathogens inevitably miss a few ‘odd spots’. Despite its eccentricity, Hoyle’s hypothesis perfectly illustrates the nearly universal tendency to treat Carpentier’s map as if it transparently presented raw data. The same is true even of the maverick scholars who have challenged the best-established modern thesis about the medieval epidemic — that the Black Death was an epidemic of bubonic plague, the disease caused by the bacterium Yersinia pestis.</p>
<p>Ole Benedictow’s 2004 book now threatens this consensus, but not on the basis of Graus’s evidence. Benedictow’s<em> The Black Death, 1346–1353: The Complete History</em> stands out both for its unusually broad geographical survey of the Black Death in Europe and for its maximizing interpretation of the disease’s force. The Oslo professor estimated that 60 per cent of Europeans died in the Black Death. To illustrate this, Benedictow offered a bold new map. Even more than that of Carpentier, his map presents a Europe inundated by waves of plague: from Central Asia to Europe, no region or city escapes the bright colours indicating the year of the plague’s arrival.</p>
<p><strong>The Case of Bohemia</strong></p>
<p>What more can be said about Bohemia’s experience with plague? For this, we must turn to the Czech scholarship — first by considering more closely Graus’s own sources, and then by surveying the evidence which Czech scholars have introduced more recently.</p>
<p>The best known example (that cited by Benedictow) comes from Francis of Prague, who chronicled Bohemia’s miraculous escape from the plague in 1348:</p>
<blockquote>
  <p>At that time [1348], certain students who were travelling from Bologna towards (versus) Bohemia saw that few humans remained alive in the cities and fortified towns. In some, all were dead. In many houses, those who survived were so overcome by the disease that one could not carry a drink of water to another nor care for another in any way. Thus they withdrew in great torment and anguish . . . And in many places, the air became further infected from the rotting of corpses, becoming a greater threat than spoilt food, as no one survived to bury them. Of these students, only one returned to Bohemia. His companions died along the way. (Francis of Prague, <em>Chronicon Francisci Pragensi</em>, ed. Jana Zachová, <em>Fontes rerum bohemicarum / Prameny deˇjin cˇesky´ch, new ser.</em>, i , Prague, 1997, 205).</p>
</blockquote>
<p>The chronicler’s point is clear: Italy and parts of Austria suffered horribly in 1348 while Bohemia, after an initial scare, narrowly escaped the same fate. Yet that is not the end of Francis’s testimony. In his account of the events of 1350, he reports that the same plague (epydimia sive pestilencia) which devastated many lands in that year also ‘took place’ (locum habebat) in Bohemia. In otherwords, the epidemic which historians single out as the Black Death reached Bohemia in precisely the year we would expect — not in 1348, but in 1350. Here, however, the expected tales of the kingdom’s suffering are nowhere to be found. Again Francis chooses to describe only the mortality in foreign lands. A later chronicler and canon of Prague cathedral, Benes Krabice of Weitmil, provides no more clarity. According to Benes, that year’s epidemic was worldwide and lasted for fourteen years ‘in Bohemia as well as in other parts of the world’. Carpentier and other scholars have long warned against the exclusive reliance on narrative sources — precisely the type of sources used by Graus — to gauge reliably the impact of an epidemic. Like many other regions, Bohemia has few extant fourteenth-century sources suited to quantitative studies of plague mortality. The most promising are the Libri confirmationum, which record the establishment and transfer of parish benefices within the Prague archdiocese: the historical demographer Eduard Maur used the <em>Libri confirmationum</em> to evaluate the impact of various pestilential outbreaks mentioned in the narrative sources. A series of approximations and borrowed multipliers eventually brought Maur to the conclusion that the archdiocese of Prague lost approximately 30 per cent of its parish clergy and therefore, he reckoned, 15 per cent of its entire population in 1380. Even Bohemia’s worst brush with the plague in 1380 left no sign of the kind of demographic catastrophe associated with cities such as Florence. The picture sketched by Graus more than forty years ago remains valid. The Black Death reached Bohemia. At least parts of Moravia suffered significantly. For the kingdom as a whole, the 1380 plague epidemic proved far more damaging. Yet, as subsequent local studies have emphasized, even that epidemic’s effects were far from uniform.</p>
<p><strong>The Meaning of the Black Death</strong></p>
<p>The act of cartographic representation itself attributes an importance to the Black Death which Graus denied. After all, the mere presence of a map of the Black Death in numerous historical atlases, even atlases of world history, confers immense historical significance on this event. The idea of the Black Death as a mighty agent in European history can be traced in part to Justus Friedrich Carl Hecker’s 1832 book <em>Der schwarze Tod im vierzehnten Jahrhundert</em>. Just as our own increasing attentiveness to climate change is now stimulating awareness of the environment as a historical factor, Hecker’s book reflected a growing nineteenth-century interest in epidemiology that was partly inspired and then bolstered by that century’s cholera and typhoid outbreaks. Long before McNeill’s Plagues and Peoples sought to ‘bring the history of infectious disease into the realm of historical explanation’, Hecker asked what difference the Black Death made in European society. </p>
<p>For Hecker the epidemic itself was a central manifestation of something larger, ‘a consequence of violent commotions in the earth’s organism’ — an environmental crisis, we might say — marked by the earthquakes, locust-plagues and floods which medieval chroniclers almost invariably associated with the epidemic. The Black Death in turn led directly, Hecker argued, to the penitential flagellant movement as well as renewed persecutions of Jews. Even more significant were the effects on human morality, for ‘such a state of excitement’ naturally compels ‘nations either [to] attain a higher degree of moral worth, or sink deeper in ignorance and vice’. Subsequent authors made his point more explicit: the moral crisis of the Black Death gave birth to the Reformation (or at least the Renaissance) and brought the Middle Ages to an end. Faye Getz has described Hecker’s account of the Black Death’s causes and effects as ‘gothic epidemiology’, evocative of the dark, powerful and morbidly fascinating villains of the nineteenth century gothic novel. Despite general agreement that the Black Death must have had a deep and broad impact, direct evidence has proved elusive. If anything, places with high mortality rates often demonstrated a remarkable resilience. Life went on, with fewer changes than we might expect.</p>
<p>(M.R.) David Mengel, &quot;A Plague on Bohemia. Mapping the Black Death,&quot;<em> Past and Present</em>&nbsp;no. 211 (May 2011), 3-34.</p>
<!-- End -->
<!-- Bottom links -->
<?php
	include 'relatedPages.php';
?>
	
<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>