<?php
	$selected = "society";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Society</a></li>
	<li><a href="index.php">Societal Structure and the New Urban Economy</a></li>
	<li>Medieval Merchant Culture</li>
</ul>
<h2>Medieval Merchant Culture</h2>
<p>The 13th and 14th centuries saw a tremendous growth in commercial activity, and a consequent restructuring of society, away from the feudal system. Changing attitudes towards trade and the merchant class marked this period. The merchant himself changed in his attitude towards his work, in his duties and abilities, and in his educational background. All of this, combined with the Church's criticism of commerce and usury, created a multi-layered complex of attitudes towards those who made their living by buying and selling goods or dealing with money. Boccaccio reflects these changes in several of his novellas, as he portrays merchants as victims of the times, and also as heroes on the forefront of social change.</p>
<p>The old, feudal model of society was dominated by the concept that there were three divinely ordained orders: knights, clergy, and peasants. Each of these groups had a role to play, either defense of the realm, maintenance of the soul of society, or the growing of essential foodstuffs. The merchant, as a class, was discriminated against for not contributing to these essential duties, but rather for aiming to get rich himself. His pursuit of gain was considered against the laws of God, because he was not a producer of real goods, but rather a resaler, or a usurer. Although medieval society increasingly came to rely upon the merchant's services in distributing and obtaining items not produced locally, he was nonetheless considered a parasite and a sinner, barely tolerated for his questionable contribution to society's output. The objection to the presence of commerce and banking in early medieval times was spearheaded by the clergy, who thundered against the sinful nature of their calling. No sin was worse than that of the usurer, no activity more repugnant to the Lord. But by the time of Boccaccio, the merchant's place in society was much more secure, his numbers had proliferated, his standing in society backed up by land and power, and his services accepted as essential to urban life. They were still hated, especially during certain periods when they were blamed for natural occurrences, thought to be God's punishment for the excesses of greed and usurious activity, but their numbers had grown so large, and their services so essential, that they were not in danger of extinction.</p>
<p>The merchant, during this transitional period, had to contend for respect and honor with the nobility and the knighthood, that traditional order that stood at the head of medieval civic society. The knighthood's pre-eminence had been guaranteed by the vital role they played in the period of feudal wars that accompanied the chaos of early medieval politics. The nobility cultivated a disdain for the petty details of moneymaking and money-saving, which were the domain of the merchant. The nobility prided themselves on their ability to spend, to be showy and magnanimous. These qualities were directly at odds with the careful attention to profit and loss which characterized the commercial man. By Boccaccio's era, however, the merchant class was very rich, often intermarrying with impoverished members of the nobility, and they held positions of power in civic government. But they never completely overcame the general contempt for the way in which they acquired their wealth.</p>
<p>As commercial activity grew and developed in complexity, new methods of tracking and distributing information grew at the same time. <a href="../institutions/schooling.php">Education</a>, no longer solely an avocation of the aspiring clergyman, became the means by which a new generation of merchants increased their ability to think and count. The need for current, up-to-date information about distant parts of Europe and the world required that letters be sent back and forth with increasing volume. Coupled with the need to hear and report news, was the need to record and compute numbers, reflecting more complicated transactions and banking instruments, such as bills of credit, interest rates, and exchange rates. Merchants left a large body of literature of their own, as they wrote about current events, family histories, and economic changes and fluctuations. The mental world of the merchant reflected their difficult and ambivalent place in society. The derision leveled at the merchant by clergy and others had an effect, and often merchants left instructions in their wills to repay those to whom they had lent money and charged interest, or to the poor of the city, in reparation. The traditional role of the merchant in popular literature reflected their lost status, whereby in the <em>exempla</em>&nbsp;(short moral tales) they are subjected to a variety of tortures in hell, or dreams, as a result of their evil way of life. In spite of this prejudice, merchants dressed more elaborately, were housed more elegantly, and enjoyed greater entertainment than most of their fellow citizens. They had officially entered medieval society, by Boccaccio's time, and ceased to be merely on the margins.</p>

<?php
	include 'relatedPages.php';
?>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
