<?php
	$selected = "literature";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Literature</a></li>
	<li>La novella tra Testo e Ipertesto: il Decameron come modello: Notes</li>
</ul>

<!--note 1-->
<h2>La novella tra Testo e Ipertesto: il Decameron come modello: Notes</h2>
<p><a name="eco"></a><a href="novella1.php#eco">*</a> Umberto Eco, &quot;Dieci modi di sognare il Medioevo&quot;, in: <em>Sugli specchi e altri saggi</em>, Milano, Bompiani, 1985, p. 89.</p>
<p><a name="01"></a><a href="novella1.php#01">1.</a> Cos&igrave; Michelangelo Picone, nell'Introduzione a <em>Il racconto</em>, a cura di M. Picone, Bologna: Il Mulino, 1985, p. 52.</p>
<p><a name="02"></a><a href="novella1.php#02">2.</a> Cos&igrave; Franco Fido nella voce &quot;Architettura&quot; del <em>Lessico critico decameroniano</em>, a cura di Renzo Bragantini e Pier Massimo Forni, Torino: Bollati Boringhieri, 1996, una limpida radiografia dell'edificio decameroniano, p. 14.</p>
<p><a name="03"></a><a href="novella1.php#03">3.</a> Richard Lanham, <em>The Electronic Word. Democracy, Technology and the Arts</em>, Chicago-London, Univ. of Chicago Press, 1993.</p>
<p><a name="04"></a><a href="novella1.php#04">4.</a> <em>Lessico</em>, cit. p. 8.</p>
<p><a name="05"></a><a href="novella1.php#05">5.</a> Non va ovviamente trascurato il fatto che si tratta della presentazione di un <em>lessico</em>, ossia appunto di uno strumento critico che non solo si articola a partire da una forma specifica di consultazione e di &quot;uso&quot; ma rimanda a sua volta ad una specifica genealogia epistemologica: non all'enciclopedismo delle <em>Summae</em>&nbsp;medievali, ma a varianti &quot;minori&quot; del progetto enciclopedico moderno, quali il <em>dictionnaire portatif</em>&nbsp;di Voltaire o l'<em>Handlexicon</em> di Gottsched, per giungere fino a pi&nbsp; rec05&quot;&gt;enti (meno portatili e maneggevoli) esemplari tardo-moderni di progetto editoriale &quot;enciclopedico&quot; (es. <em>Enciclopedia</em>&nbsp;Einaudi). Per la teoria della convergenza il rimando &egrave; a: <em>Hypertext: The Convergence of Contemporary Critical Theory and Technology</em>, Baltimore and London: Johns Hopkins University Press, 1992, trad. it. di Bruno Bassi, Bologna: Baskerville, 1993 (una nuova edizione italiana, con l'aggiunta di una prefazione d'autore, &egrave; imminente presso la Bruno Mondadori editore). Per una prospettiva italiana sia consentito limitarsi a citare gli interventi di Mario Ricciardi, in particolare: &quot;Studi umanistici e nuove tecnologie&quot;, in: <em>Oltre il testo: gli ipertesti</em>, a cura di M. Ricciardi, Milano: Angeli, 1994, pp. 9-40 e l'introduzione al volume <em>Lingua Letteratura Computer</em>, a cura di Mario Ricciardi, Torino: Bollati Boringhieri, 1996.</p>
<p><a name="06"></a><a href="novella1.php#06">6.</a> Claude Cazal&eacute; B&eacute;rard, <a href="http://www.univ-lille3.fr/www/credo/boccace/hyperdec.html"><em>Hyperdecameron</em></a> (broken link), la definisce &quot;un nouveau type d'&eacute;dition critique multidimensionnelle et multim&eacute;dia&quot;.</p>
<p><a name="07"></a><a href="novella1.php#07">7.</a> Per una presentazione iniziale di tale progetto, nelle sue caratteristiche di strumento didattico per il lavoro ermeneutico-interpretativo <em>sul</em>&nbsp;testo e ri-costruzione di contesti molteplici <em>intorno al</em>&nbsp;testo di Boccaccio, sia consentito rinviare a: Massimo Riva, &quot;Il Decameron come ipertesto&quot;, scritto in collaborazione con un gruppo di dottorandi della Brown University (Giorgio Melloni, Michael Papio, Sergio Parussa, Giuliana Picco e Giuseppe Strazzeri) e contenuto nel volume <em>Lingua Letteratura Computer</em>, cit., pp.117-136.</p>

<!--note 2-->
<h2>Notes for Page II</h2>
<p><a name="08"></a><a href="novella2.php#08">8.</a> <em>Lessico</em>, cit., p. 419: &quot;Dalla sua prima trasmissione attraverso lettori affascinati e copisti per passione nella societ&agrave; mercatantesca &shy; e non amanuensi di professione e centri culturali ecclesiastici o laici &shy; fino all'identificazione dell'autografo scrutato e non riconosciuto per due secoli da grandi studiosi e filologi &shy; da 	Salvini e Manni e Zeno a Biadene e Tobler e Hecker e Massera e Barbi &shy; il <em>Decameron</em>&nbsp;sembra avere riflesso lungo quasi sei secoli e mezzo la sua estrosit&agrave; e la sua singolarit&agrave; letteraria nelle sue vicende testuali, sino a sfiorare il giallo ecdotico&quot;. </p>
<p><a name="09"></a><a href="novella2.php#09">9.</a> P. M. Forni, <em>Forme complesse nel D.</em>, Firenze, Olschki, 1992. </p>
<p><a name="10"></a><a href="novella2.php#10">10.</a> Cfr. ad es. Raul Mordenti, &quot;Il D.: una lettura tra semiologia 		e filologia&quot;, in <em>Il testo ritrovato: Forme poetiche e classici a scuola</em>, a cura di Francesco Gnerre, Ravenna: Longo, 1987, pp. 43-72.</p>
<p><a name="11"></a><a href="novella2.php#11">11.</a> Nel momento in cui anche la filologia prende atto, attraverso gli ausili dell'elettronica, che &quot;il Testo letterario trattato con la macchina per essere &laquo;compreso&raquo; deve necessariamente essere scomposto e ricomposto, tipologizzato per categorie informative, &laquo;decostruito&raquo;: deve dunque sempre pi&ugrave; essere reso omogeneo ai molteplici &laquo;testi&raquo; che formano l'universo comunicativo, rinunziare ad essere &laquo;Testo&raquo; per assumere il ruolo di &laquo;discorso&raquo; e rompere ogni rapporto con l'Autore&quot; (Roberto Antonelli, &quot;Interpretazione e critica del testo&quot;, in: <em>Letteratura Italiana</em>, a cura di Alberto Asor Rosa, IV, <em>L'Interpretazione</em>, p. 242), l'apporto della filologia come disciplina di lavoro e abitudine intellettuale risulta al contempo (e paradossalmente) pi&ugrave; labile e pi&ugrave; prezioso. Si vedano le osservazioni equilibrate di Corrado Bologna sulla &quot;qualit&agrave; inderogabilmente storicistica&quot; della &quot;costituzione del testo&quot;: &quot;Il testo ?nel-tempo, come l'edizione che lo <em>(ri)costituisce</em>, appunto...&quot; (&quot;Costituire&quot;, in: <em>Il testo letterario. Istruzioni per l'uso</em>, a cura di Mario Lavagetto, Bari: Laterza, 1996, p. 20). Dal canto suo, Raoul Mordenti (sulla scorta della nozione &quot;diasistemica&quot; dell'apparato come &laquo;luogo del virtuale&raquo; di Cesare Segre) prende atto che &quot;non si pu&ograve; fare a meno di domandarsi se la tecnologia informatica, e le possibilit&agrave; che le sono connesse di un passaggio continuo ed utile fra testo ed apparato, non fondi a sua volta una diversa scala di valori e di obiettivi per la scienza filologica, sostituendo alla fissit&agrave; del Testo con la T maiuscola la plurale mobilit&agrave; di tanti e diversi testi diasistema&quot; (citato da Cazal&eacute; B&eacute;rard). </p>
<p><a name="12"></a><a href="novella2.php#12">12.</a> C. Segre, &quot;Leggere i testi del Medioevo&quot;, in: <em>Notizie dalla crisi. Dove va la critica letteraria?</em>, Torino, Einaudi, 1993, pp. 297-309. </p>
<p><a name="13"></a><a href="novella2.php#13">13.</a> Alla &quot;visualizzazione&quot; come categoria centrale della rivoluzione tecnologica in corso si rifa' il recente rapporto del Massachusetts Institute of Technology (1995) sulle nuove &quot;tecnologie educative avanzate&quot;. Sia consentito anche qui di rinviare a: Massimo Riva: &quot;Per una comunit&agrave; della formazione letteraria: il WWW e la nuova italianistica&quot;, negli atti del convegno <em>Internet: ricerca e/o didattica</em>, organizzato dal Bollettino '900 e dal dipartimento di Italianistica dell'Universit&agrave; di Bologna, e tenutosi nel novembre del 1996, di prossima pubblicazione. </p>

<!--note 3-->
<h2>Notes for Page III</h2>
<p><a name="14"></a><a href="novella3.php#14">14.</a> &quot;...un exemple d'hypertexte pr&eacute;-informatique assez satisfaisant et par cons&eacute;quent un type de document qui s'adapte particuli&egrave;rement bien &agrave; un traitement hypertextuel, en raison de la riche typologie des &eacute;critures, de la diversit&eacute; et de l'absence d'homog&eacute;n&eacute;it&eacute; des contenus, des formes et modes de pr&eacute;sentation ou de classification; en raison de l'absence de corr&eacute;lation s&eacute;quentielle et de chronologie entre les fragments, qui les rend disponibles pour un multiplicit&eacute; de parcours de lecture et de traitement. Les <em>Zibaldoni</em>&nbsp;constituent, en effet, une &laquo;encyclop&eacute;die provisoire&raquo;&quot;. </p>
<p><a name="15"></a><a href="novella3.php#15">15.</a> Questo tipo di lettore sembra ricorrere pur sempre al principio d'Autore (e all'Opera vista come produzione-proiezione di una sua virtuale <em>forma mentis</em>) per legittimare-razionalizzare l'uso dei nuovi strumenti a sua disposizione: &quot;Les <em>Zibaldoni</em>&nbsp;constituent, en fait, le laboratoire &agrave; partir duquel Boccace va forger une oeuvre originale, le <em>D&eacute;cam&eacute;ron</em>, qui emprunte certes &agrave; la <em>Divine Com&eacute;die</em> l'id&eacute;e d'une structure fortement architectur&eacute;e comme un microcosme&agrave; l'image du monde, mais aussi &agrave; ses &laquo;carnets de notes&raquo; ou &agrave; ses&laquo;livres-archives d'auteur&raquo;, comme les nomme A. Petrucci, leurouverture &agrave; la multiplicit&eacute; des parcours et des lectures&quot; (ancoraClaude Cazal&eacute; B&eacute;rard). Viene fatta salva, come si vede, in questeparole, anche la &laquo;libert&agrave;&raquo; del lettore, una volta salvaguardatoper&ograve; il diritto d'Autore (e l'arbitrato del lettore professionale).Scrive ancora Cazal&eacute; B&eacute;rard: &quot;Le syst&egrave;me narratif du <em>D&eacute;cam&eacute;ron</em>&nbsp;constitue par lui-m?me un syst&egrave;me narratif en r&eacute;seau pre-&eacute;lectronique:sa structure de type encyclop&eacute;dique (soit comme r&eacute;pertoire decas humains &laquo;narrativis&eacute;s&raquo;, de mod&egrave;les et de formes narratives, soumises &agrave; plusieurs crit&egrave;res d'organisation, explicites ou implicites)pr&eacute;voit des parcours multiples de lecture, au de l&agrave; des parcoursfix&eacute;s par les r&egrave;gles narratives d&eacute;clar&eacute;es (souvent transgress&eacute;esau niveau m?me de la fiction)...&quot; </p>
<p><a name="16"></a><a href="novella3.php#16">16.</a> Una definizione questa per altri versi adottata da Luca Toschinel suo intervento in <em>The future of the Book</em>, Berkeley: University of California Press, 1996 e nel volumeche accompagna il CD-Rom, &quot;La famiglia dell'antiquario&quot; di C.Goldoni in edizione elettronica, Venezia, Marsilio, 1996. </p>
<p><a name="17"></a><a href="novella3.php#17">17.</a> C'&egrave; chi, d'altra parte, come Bernard Cerquiglini (<em>&Eacute;loge de la variante. Histoire critique de la philologie</em>, Paris, Seuil, 1989, p. 25 e 54) nega addirittura che l'autoresia un'idea medievale, insistendo (secondo una prospettiva definibilepost-freudiana) sull'idea di una essenziale &quot;varianza&quot; che caratterizzerebbela dinamica profonda della letteratura del Medioevo volgare (cfr.le osservazioni in proposito di C. Bologna, cit., p. 17 e nota&shy; su Cerquiglini &shy; e alla pagina seguente, in riferimento a Contini,sull'irriducibile condizione temporale del nesso Autore-Testo).Rimane a nostro avviso il fatto che trattare il mezzo informaticocome puramente tale, un neutro strumento al servizio della formatrascendentale dell'Opera o della mente trascendentale del critico(in diretta empatia ecdotica con l'Autore, faticosamente e meritoriamenteacquisita grazie alla familiarit&agrave; con le tracce, tendenzialmentetutte le tracce lasciate da Lui) come un attrezzo insomma chenon incide n&eacute; sulla &laquo;forma&raquo; della prima n&eacute; sulla de-formazione(professionale) della seconda, impedisce di vedere che proprioquesto &egrave; invece il caso. Impedisce soprattutto di vedere che nel<em>Decameron</em>&nbsp;sono virtualmente presenti non uno ma molteplici &quot;ipertesti&quot;.</p>
<p><a name="18"></a><a href="novella3.php#18">18.</a> Ancora Landow, in un suo pi? recente intervento (&quot;What's a Criticto Do? Critical Theory in the Age of Hypertext&quot;, introduzionea <em>Hyper/Text/Theory</em>, a cura di G. Landow, Baltimore and London: Johns Hopkins UniversityPress, 1994, pp. 36-37), delinea per il critico (ma anche peril didatta) della letteratura il compito di utilizzare la parolaelettronica, il nuovo ambiente della scrittura e della lettura,per portare alla luce aspetti meno immediatamente evidenti, divenutiuna &quot;seconda natura&quot; o addirittura reificati e mistificanti dellacultura basata sulla stampa, ivi incluse la teoria e le pratichedi una conservazione o custodia (sia fisica che simbolica) dell'integrit&agrave;e &quot;alterit&agrave;&quot; del testo o del suo &quot;messaggio storico&quot;, pratichea loro volta formatesi in epoche in cui predominavano tecnologiedi produzione, riproduzione e diffusione dell'informazione (dinuovo, lettura e scrittura) oggi, secondo alcuni, tendenzialmenteobsolete. </p>

<!--note 4-->
<h2>Notes for Page IV</h2>
<p><a name="19"></a><a href="novella4.php#19">19.</a> U. Eco, <em>Semiotica e filosofia del linguaggio</em>, Torino, Einaudi, 1984, p. 111. </p>
<p><a name="20"></a><a href="novella4.php#20">20.</a> Per un bilancio critico sul concetto di enciclopedia nell'operadi Eco si rimanda al saggio di Patrizia Violi, &quot;Le molte enciclopedie&quot;, in: <em>Semiotica: storia, teoria, interpretazione. Saggi intorno a Umberto Eco</em>, Milano: Bompiani, 1992, pp. 99-113 (la citazione &egrave; a p.103).</p>
<p><a name="21"></a><a href="novella4.php#21">21.</a> U. Eco, <em>Arte e bellezza nell'estetica medievale</em>, Milano: Bompiani, 1987, p. 195. . </p>
<p><a name="22"></a><a href="novella4.php#22">22.</a> Sia sufficiente rinviare qui, per il tardo Medioevo, agli studi di Armando Petrucci, di cui basti citare, oltre ai contributial volume II, <em>Produzione e Consumo</em>, della Letteratura Italiana Einaudi, 1983: &quot;Lire au Moyen Age&quot;, &laquo;M&eacute;langes de l'Ecole fran?aise de Rome&raquo;, XCVI (1984); &quot;Storiae geografia delle culture scritte (dal sec. XI al sec. XVIII)&quot;, in Letteratura Italiana, <em>Storia e Geografia</em>, II, 2, Torino, Einaudi, 1988, pp. 1193-1292; Paul Saenger, &quot;Leggerenel Tardo Medioevo&quot;, in <em>Storia della lettura</em>, a cura di G. Cavallo e R. Chartier, Bari, Laterza, 1995, pp. 118-154; Malcom Parks, <em>Scribes, Scripts and Readers. Studies in the Communication, Presentation and Dissemination of Medieval Texts</em>, London, Hambledon Press, 1991; e J.K. Hyde, <em>Literacy and Its Uses. Studies on Late Medieval Italy</em>, a cura di D. Walley, Manchester, Manchester Un. Press, 1992.</p>
<p><a name="23"></a><a href="novella4.php#23">23.</a> Nel nuovo <em>scriptorium</em>&nbsp;o laboratorio del critico infatti sono la &quot;forma visuale&quot; dell'ipertesto (Michael Joyce) e il modello cognitivo-percettivo cui tale forma si ispira che diventano specularmente cruciali.Questa visualizzazione del testo (consustanziale soprattutto all'atto della lettura &quot;silenziosa&quot;) attraversa, a partire dal laboratorio autoriale, le varie forme della sua materializzazione nella scrittura manoscritta, a stampa, fino a giungere all'ambiente multimediale, non-lineare del testo elettronico, in cui lettura e scrittura, parola e immagine si combinano in forme nuove. Di Joyce, cui si deve la distinzione fondamentale tra ipertesto &quot;esplorativo&quot; e &quot;costruttivo&quot; &egrave; da vedere <em>Of two Minds. Hypertext Pedagogy and Poetics</em>, Ann Arbor, Univ. of Michigan Press, 1995. </p>
<p><a name="24"></a><a href="novella4.php#24">24.</a> &Egrave; questo, in sintesi, il principio che guida la costruzione del nostro ipertesto ermeneutico-<em>didattico</em>, il <em>Decameron Web</em>. Per la cui <em>ratio</em> organizzativa si rimanda ancora ai nostri interventi citati alle note 5 e 7. Sul ruolo innovativo e costruttivo dell'&quot;individuale&quot; (o di una soggettivit&agrave; semiosica) nella &quot;riorganizzazione dei repertori dell'enciclopedia&quot; si veda l'importante saggio citatodi P. Violi (p. 108 sgg.) </p>

<!--note 5-->
<h2>Notes for Page V</h2>
<p><a name="25"></a><a href="novella5.php#25">25.</a> M. Picone, &quot;Il significato di un convegno sull'enciclopedismo medievale&quot;, in: <em>L'Enciclopedismo medievale</em>, a.c. di M. Picone, Ravenna, Longo, 1994, p. 21: &quot;Del resto, il titolo stesso, <em>Decameron</em>, &egrave; un ammicco ironico all'<em>Hexameron</em>, che non &egrave; tanto l'omonima opera di Sant'Ambrogio, quanto una delle strutture fondamentali di cui si servono le enciclopedie medievali&quot;. </p>
<p><a name="26"></a><a href="novella5.php#26">26.</a> Suggestivo sarebbe qui seguire la pista di un confronto con Dante &quot;personaggio mancato del <em>Decameron</em>&quot; (per riprendere il titolo di un noto intervento di Franco Fido), proprio a partire dalla strategica rubrica proemiale, dal riferimento simultaneo alla tradizione cortese e al Dante sdoppiato &quot;personaggio-testimone&quot; di <em>Inf. V</em>, da leggersi come l'episodio di Dante e Francesca, rispettivamente &quot;ascoltatore interessato&quot; e narratrice, rivisitato (parodicamente?) da Boccaccio, nel Proemio: ove l'Autore si identifica/dissimula, per antonomasia, con il Libro che porge alle sue lettrici ideali, specularmente rovesciando la dinamica empatica e pietosa dell'episodio dantesco. Meno cogente, pur se non trascurabile, in questa prospettiva 	il nesso intertestuale con il sonetto proemiale del <em>Canzoniere</em>&nbsp;petrarchesco. In questo fitto intreccio, sembra emergere decisamente il profilo di &quot;anti-modello&quot; <em>parodico</em>&nbsp;del <em>Decameron</em>. Da vedere innanzitutto, per una prospettiva complessiva sulle forme e tecniche della &quot;transazione&quot; culturale instaurate dal <em>Decameron</em>, Francesco Bruni, <em>Boccaccio. L'invenzione della letteratura mezzana</em>, Bologna, Il Mulino, 1990. Inoltre, pi? specificamente per il tema accennato: Claude Cazal&eacute; B&eacute;rard, &quot;Dante e Boccaccio: due strategie del narrare d'amore&quot;, &laquo;Rassegna Europea della Letteratura Italiana&raquo;, III, 1994. Per una rivalutazione complessiva del rapporto con la tradizione cortese, si rinvia a Daniela Delcorno Branca, <em>Boccaccio e le storie di Re Art?</em>, Bologna, Il Mulino, 1991. Per una rassegna critica sulla &quot;fittissima trama&quot; del rapporto &quot;parodico&quot; tra Commedia divina ed umana, nell'ambito della vena parodica generale della cultura medievale, si cfr. (sullo sfondo aperto da Vittore Branca, <em>Boccaccio medievale</em>, Firenze, Sansoni, 1990, pp. 343-sgg.), oltre le puntualizzazioni recenti di Carlo Delcorno nella voce Ironia/parodia del <em>Lessico</em>, cit., pp. 171-sgg., le dettagliate analisi di A. Bettinzoli, &quot;Per una definizione delle presenze dantesche nel &laquo;D.&raquo;, &laquo;Studi sul B.&raquo;, XIV, pp. 209-240. Per una ulteriore focalizzazione retrospettiva sul rapporto Dante-Boccaccio, sono da vedere gli interventi di Robert Hollander a cominciare da: &quot;Boccaccio's Dante: Imitative Distance&quot;, &laquo;Studi sul B.&raquo;, 1981-82, , 13, pp. 169-198. </p>
<p><a name="27"></a><a href="novella5.php#27">27.</a> Sul nesso tra &quot;sistema del sapere&quot; (enciclopedico) e &quot;istanze narrative&quot; si &egrave; concentrata Claude Cazal&eacute; B&eacute;rard in un ricco e complesso intervento: &quot;Sistema del sapere e istanze narrative nella novellistica toscana medievale&quot;, in: <em>L'Enciclopedismo medievale</em>, cit., pp. 329-359. Identificate tre categorie della &quot;secolarizzazione&quot; narrativa rispetto al sistema del sapere medievale (trapianto, sia strutturale che linguistico, assimilazione e trasformazione), e rammentato, sulla scorta di M. Picone, come &quot;la novella nasca nell'intercapedine tra sistema enciclopedico e produzione letteraria come messa in opera originale dei tratti oppositivi: come forma breve ma tendente all'organicit&agrave;, come finzione ma con pretesa di autenticit&agrave;, come genere minore ma assunto a trattare i <em>magnalia</em>, come messa in discussione ed estremo ricettacolo dell'umana sapienza&quot; (p. 344), la Cazal&eacute; B&eacute;rard argomenta che col suo <em>Centonovelle</em> &quot;Boccaccio capovolge i rapporti: non pi? un sistema del sapere entro il quale si fanno strada istanze narrative, bens? un sistema narrativo fatto lievitare da istanze conoscitive&quot; (p. 348). Ne risulterebbe, nel testo, una costruzione <em>en ab&icirc;me</em>, a livelli concentrici, giocati tutti sulla tensione strutturale e auto-referenziale (paradigmatico-sintagmatica) tra narrazione e commento. &quot;Boccaccio assomma dunque nel D. l'esperienza del romanziere e del poeta con quelle del chiosatore e del compendiatore di materie storiche e allegoriche...L'opera di Boccaccio segna forse il momento limite delle potenzialit&agrave; inventive del sistema enciclopedico medievale quando trapassano nella creativit&agrave; letteraria&quot; (p. 349 e 358). Come si vede, si tratta di una prospettiva ancora sostanzialmente gravitante sull'Autore, il quale (nel Proemio a <em>Genealogie</em>, Lib. XIV) affiderebbe al lettore professionale anche un mandato euristico, una sorta di motore di ricerca: &quot;&egrave; proprio B. a definire i tre tempi del motore grazie al quale sistema del sapere e sistema narrativo si danno reciprocamente impulso: <em>raccogliere, ordinare, interpretare</em>&quot;. </p>
<p><a name="28"></a><a href="novella5.php#28">28.</a> <em>Grammaire du D.</em>, The Hague, 1969, p. 78. Al di l&agrave; dei suoi limiti, ormai datati e legati alle strutture stesse della &quot;grammatica&quot; narrativa da lui congegnata, ci pare che si potrebbe forse rilanciare (in questa chiave) l'idea di Todorov del <em>Decameron</em>&nbsp;come sistema (o modello) complesso dello &quot;scambio falsato&quot;. Ripensato, per&ograve;, secondo un'ottica semiologica sensibile alla dinamica o dialettica (gi&agrave; da tempo individuata all'interno della stessa cultura medievale) di modelli e antimodelli. Il riferimento implicito &egrave; al saggio di Maria Corti, &quot;Modelli e antimodelli nella cultura medievale&quot;, &laquo;Strumenti Critici&raquo;, febbraio 1978, pp. 3-sgg. che si rifaceva a sua volta alla lezione (cos&igrave; rilevante per gli studi recenti sul capolavoro di Boccaccio) di M. Bakhtin. </p>
<p><a name="29"></a><a href="novella5.php#29">29.</a> Ancora Michelangelo Picone, nel <em>Lessico critico</em>, alla voce Autore/narratori, insiste su di un rapporto di &quot;specularit&agrave;&quot; (ancorch&eacute; &quot;prismatica&quot;) tra il primo e i secondi come elemento portante, nella struttura dell'opera, di una &quot;profonda unit&agrave;&quot; e anche di una &quot;latente fedelt&agrave;...allo <em>spirito</em>, se non alla <em>lettera</em>, della <em>Commedia</em>&quot; dantesca (<em>Lessico</em>, cit., p. 36 e 39). A parte il generico monito che &quot;the unity
 we find in literary texts is impregnated with the identity that finds that unity&quot; (Norman Holland, &quot;Unity Identity Text Self&quot;, PMLA, 90 (1975), pp. 813), queste affermazioni sono da temperare con quanto lo stesso Picone sostiene in un altro intervento, &quot;Per una lettura ludica del D.&quot;, in: <em>Passare il tempo: la letteratura del gioco e dell'intrattenimento dal XII al XVI secolo</em>, a cura di E. Malato e M. Picone, Roma, Salerno ed., 1993, vol. I, pp.109-110: &quot;...queste due opere...non fa[nno] altro che riproporre, in misura ovviamente ingigantita, l'opposizione, tipica della cultura medievale, fra <em>seria</em>&nbsp;e <em>ludicra</em>. Se infatti la <em>Commedia</em>&nbsp;si pone come la summa della tradizione allegorica, tesa a ritrovare la verit&agrave; finale dell'uomo e del suo destino, il D., dal canto suo, rappresenta il punto di approdo della tradizione giocosa (dalla <em>comoedia elegiaca</em>&nbsp;al <em>fabliau</em>&nbsp;) il cui obiettivo &egrave; quello di manifestare la verit&agrave; mondana e terrena dell'uomo e della sua storia&quot;. Sul <em>ludus Ciappelletti</em>, v. pp. 126-sgg. Su Griselda e la lunga teoria delle interpretazioni (sulle quali non ci dilunghiamo in questa sede) si rimanda alla bibliografia a cura di V. Branca nell'edizione Einaudi, cit. pp. CXX, sgg. </p>
<p><a name="30"></a><a href="novella5.php#30">30.</a> Al di l&agrave; della possibilit&agrave; di precisare al massimo la natura semiotica di questa dialettica (ricorrendo magari all'opera di illustri &quot;modellizzatori&quot; alla Todorov o alla Greimas, tra modello &quot;costituzionale&quot; e anti-modello &quot;attanziale&quot;, per ricorrere alla terminologia di quest'ultimo) concordiamo qui pienamente con la posizione espressa da Franco Fido tanto nella voce Architettura del <em>Lessico</em>, cit., che nella sua precedente raccolta di studi decameroniani: <em>Il regime delle simmetrie imperfette</em>, Milano, Angeli, 1988, pp. 7-8. Da vedere anche: G. Mazzacurati, &quot;La regina e il buffone: ordo e varietas nella costruzione del D.&quot;, in <em>All'ombra di Dioneo. Tipologie e percorsi della novella da Boccaccio a Bandello</em>, Firenze, La Nuova Italia, 1996, pp. 37-43. E pi? in generale lo studio ancora pieno di stimoli di Mario Baratto, <em>Realt&agrave; e stile nel D.</em>, Roma, Editori Riuniti, 1984, sulla &quot;bipolarit&agrave;&quot; centrifuga dell'organismo decameroniano (pp. 12-sgg.). Va rammentato poi ancora il contributo di P. M. Forni, citato alla nota 10. Per una prospettiva pi? direttamente legata alle forme o tecniche culturali di &quot;transazione&quot; tra Autore e Lettore si rinvia ancora al gi&agrave; citato studio di Bruni. </p>
<p><a name="31"></a><a href="novella5.php#31">31.</a> E. Grimaldi, <em>Il privilegio di Dioneo. L'eccezione e la regola nel sistema 'Decameron'</em>, Napoli, Edizioni Scientifiche Italiane, 1987. </p>
<p><a name="32"></a><a href="novella5.php#32">32.</a> &quot;Indugiare nel bosco&quot;, in: U. Eco <em>Sei passeggiate nei boschi narrativi</em>, Milano, Bompiani, 1994, p. 159. </p>

<!--note 6-->
<h2>Notes for Page VI</h2>
<p><a name="33"></a><a href="novella6.php#33">33.</a> D'altra parte, basta scorrere il <em>Motif Index of the Italian Novella in prose</em>&nbsp;di Rotunda (Bloomington, 1942) o anche <em>The D.: Its Sources and Analogues</em>&nbsp;di A.C. Lee (New York, 1909), aggiundovi magari, sullo sfondo, la morfologia proppiana (o l'<em>Index of Folk Literature</em>&nbsp;dello Stith Thompson), per afferrare la strategia &quot;intertestuale&quot; (la ri-combinazione di racconti e tradizioni esistenti) che &egrave; fondamentale non solo per comprendere la logica compositiva del D. ma anche il &quot;modello culturale&quot; che esso delinea, una serie di procedimenti che l'ipertesto consente di visualizzare meglio (o altrimenti) che non la struttura &quot;chiusa&quot; del Libro a stampa. Che questa ricombinazione e tensione, <em>interna</em>&nbsp;al Libro e alla sua unit&agrave; formale e simbolica, sia profondamente radicata nella cultura medievale pu&ograve; essere confermato tanto dalla lettura di C.S. Lewis &quot;The Influence of the Model&quot;, <em>The Discarded Image</em>, Cambridge, 1964 che di Curtius (si veda la recente edizione italiana a.c. di R. Antonelli de <em>Letteratura europea e Medio Evo latino</em>, Firenze, La Nuova Italia, 1992). </p>
<p><a name="34"></a><a href="novella6.php#34">34.</a> Per una sottile ed esauriente analisi di questo aspetto si rimanda alla voce <em>Realt&agrave;/verit&agrave;</em>&nbsp;di Pier Massimo Forni, nel <em>Lessico</em>, cit., pp. 300-sgg. </p>
<p><a name="35"></a><a href="novella6.php#35">35.</a> Ad es., in anni recenti, Christopher Nissen, &quot;Ethical Modes in Boccaccio's D.&quot; &laquo;RLA&raquo;, 1989, 1, pp. 191-96 e, soprattutto, ci pare, V. Kirkham, <em>The Sign of Reason</em>, Firenze, Olschki, 1993. Pier Massimo Forni, pur soffermandosi con intelligenti osservazioni sugli aspetti ludici dell' &quot;intrattenimento Decameroniano&quot; (in <em>Passare il tempo: la letteratura del gioco e dell'intrattenimento dal XII al XVI secolo</em>, cit., vol. II, pp. 529-540, ribadisce invece nella voce gia' citata del <em>Lessico</em>: &quot;Si potranno discutere le componenti ludiche e parodiche dell'operazione, comunque la novella decameroniana assume regolarmente i connotati retorici di testo esemplare&quot; (p. 304). E pi? in generale (sulla questione, qui evocata, del realismo): &quot;&Egrave; assai importante, addirittura decisivo... che il realismo boccacciano sia valutato sullo sfondo di quei cruciali mutamenti di pensiero, e anzi di visione del mondo divulgatisi nel corso del Duecento... Parlare di un realismo di Boccaccio dipendente da un realismo dantesco ignorando la comune matrice del realismo francescano-tomista non ha molto senso...&quot; (p. 313). Lo stesso Forni, nelle stesse pagine, sottolinea per&ograve;, sia pure en passant, la natura &quot;felicemente centrifug(a), gioiosamente impersonale&quot; del <em>Centonovelle</em>&nbsp;rispetto &quot;alla natura essenzialmente, sia pure diversamente, centripeta...delle monumentali opere in volgare delle altre due corone, la <em>Commedia</em>, appunto, e i <em>Rerum vulgarium fragmenta</em>&quot; (p. 315). </p>
<p><a name="36"></a><a href="novella6.php#36">36.</a> Si confronti, per l'altro volto di questa identit&agrave; autoriale, la <em>Conclusione</em>&nbsp;del D., pp. 1255-56 (&quot;Senza che alla mia penna non dee essere meno d'auttorit&agrave; conceduta che sia al pennelo del dipintore...) e si ricordi, soprattutto, l'interpretazione pasoliniana della novella, con la sostituzione autoriale di cui parliamo (una delle tante suggestioni dell'<em>interpretazione</em>&nbsp;&shy; pi? che semplice adattamento &shy; in un medium differente, della diegesi decameroniana). Sulla feconda &quot;mislettura&quot; pasoliniana del D. da vedere, di recente, il capitolo dedicato al D. da M. Marcus in <em>Filmmaking by the Book: Italian Cinema and Literary Adaptation</em>, Baltimore, Johns Hopkins U. P., 1993. Cfr. anche le puntualizzazioni di Pamela Stewart, &quot;Giotto e la rinascita della pittura: D. VI.5&quot;, in Yearbook of Italian Studies, 1983, 5, pp. 22-34. E Paul Watson, &quot;The Cement of Fiction: G. B. and the Painters of Florence&quot;, &laquo;MLN&raquo;, 1984, Jan., 99-1, pp. 43-64. </p>
<p><a name="37"></a><a href="novella6.php#37">37.</a> Oltre che ai noti studi di Almansi (sulla &quot;menzogna narrativa&quot;) e Mazzotta (sulla &quot;marginalit&agrave; della letteratura&quot;), per un recente intervento, in area americana e da una prospettiva &quot;postmodernista&quot;, eccentrica rispetto agli studi boccacciani maggiori, e discutibile ma sintomatica nel contesto del nostro discorso sulla ricezione contemporanea del D., si rimanda a Bennet Schaber, &quot;The Aesthetics of Deception: Giotto in the Text of Boccaccio, in: <em>Postmodernism across the Ages</em>, a cura di B. Readings &amp; B. Schaber, Syracuse, NY, Syracuse U.P., 1993, pp. 47-62. </p>
<p><a name="38"></a><a href="novella6.php#38">38.</a> Si pu&ograve; apparentare, in qualche modo, la costruzione del mondo (possibile) decameroniano alla &quot;rivoluzione&quot; post-occamistica nella mentalit&agrave; trecentesca, alla percezione di un universo composito (o discreto) di discontinuit&agrave; che si sostituisce a quella &quot;piramidale&quot; averroistica ancora sostanzialmente alla base della cosmologia dantesca? &quot;...c'&egrave; un passaggio dalla visione dell'essere conchiuso nella sua realt&agrave; all'uomo poeta, che vuol dire creatore. All'uomo che non ha da contemplare un ordine dato, da attuare un'essenza eterna, ma che ha dinanzi infinite possibilit&agrave;. Il mondo, lungi dall'essere fisso entro forme cristallizzate, &egrave; plasmabile in guise sempre nuove, e non c'&egrave; necessit&agrave; che non s'incrini, non forma che non si trasformi; e libert&agrave; d'uomo indica un essere il cui volto non &egrave; mai definito...&quot; (Eugenio Garin, <em>Medioevo e Rinascimento</em>, Bari, Laterza, 1976, p. 36). &quot;Confesso nondimeno le cose di questo mondo non avere stabilit&agrave; alcuna ma sempre essere in mutamento...&quot; (Conclusione dell'Autore, ed. Branca, cit. p. 1261). E tra le cose del mondo va annoverata anche la &quot;lingua mortale&quot; del poeta.</p>
<p><a name="39"></a><a href="novella6.php#39">39.</a> V. Branca, &quot;B. visualizzato. I. Interpretazioni visuali del D. II. Un primo elenco di codici illustrati di opere del B.&quot; &laquo;Studi sul B.&raquo;, XV, pp. 87-148. </p>

<!--note 7-->
<h2>Notes for Page VII</h2>
<p><a name="40"></a><a href="novella7.php#40">40.</a> <em>La tecnica di composizione della novella</em>, tr. Raoul Precht, Roma-Napoli: Edizioni Theoria, 1984, p. 27.</p>
<p><a name="41"></a><a href="novella7.php#41">41.</a> Questa polarit&agrave; tra brigata e &quot;libert&agrave;&quot; del lettore &egrave; alla base del design del nostro ipertesto costruttivo: il lettore attivo, empirico fa per cos&igrave; dire ingresso nel &quot;mondo commentato&quot; del <em>Decameron</em>, &quot;impersonando&quot; criticamente uno dei membri della brigata, nella loro duplice funzione di narratori/ascoltatori (ricettori) del testo. </p>
<p><a name="42"></a><a href="novella7.php#42">42.</a> Auerbach op. cit. pp. 81-7. Ci&ograve; sembrerebbe suggerire che un modello Auerbachiano (ragionato secondo una prospettiva semiologica) sia preferibile a modelli &quot;grammaticali&quot; di tipo Proppiano, Greimasiano o Todoroviano. &Egrave;, crediamo, una prospettiva non lontanissima da quella espressa in pi? luoghi da Cesare Segre, di un &quot;modello semiotico-culturale&quot; di ampio respiro (si veda, tra i molti rimandi possibili, <em>Semiotica filologica</em>, Torino, Einaudi, 1979) aperta per&ograve; al rapporto dialogico interattivo del testo col lettore contemporaneo. Ma la cosa va naturalmente approfondita e, soprattutto, verificata in via sperimentale; per un recente contributo al dibattito non esaurito sul Boccaccio di Auerbach, si pu&ograve; vedere: Albert R. Ascoli, &quot;Boccaccio's Auerbach: Holding the Mirror Up to Mimesis&quot;, &laquo;Studi sul B.&raquo;, 1991-92, 20, pp. 377-97. </p>
<p><a name="43"></a><a href="novella7.php#43">43.</a> F. Fido, &quot;Arch.&quot;, <em>Lessico</em>, cit. , p.32. Si paragoni questa visuale con quella enunciata eloquentemente dal Foscolo, non a caso nell'ambito delle sue riflessioni &quot;sperimentali&quot; (cfr. il riferimento alle &quot;osservazioni&quot; di Galileo da cui prende le mosse) sulla traduzione dell'<em>Iliade</em>, alle prese dunque con una &quot;rappresentazione&quot; o &quot;modellizzazione&quot; funzionale di un classico: &quot;Quella osservazione delle intarsiature di Galileo, ch'io stimo pi? di molte teorie rettoriche, mi fece germinare nella mente un'idea che se non fosse nuova per avventura, riescir&agrave; nuovamente e chiaramente a quanto io credo spiegata. Ed &egrave; che tanto in prosa, quanto in versi lo scrittore deve esattamente osservare il <em>Disegno</em>&nbsp;del pensiero; n&eacute; io intendo il disegno generale dell'opera che altri chiamer&agrave; architettura o economia, o franciosamente <em>piano</em>, bens&igrave; il disegno di ogni pensiero partitamente prima considerata ogni parola con l'altra e per conseguenza ogni idea destata da ogni parola, e poi ogni gruppo di minime idee, con le altre vicine; e poi tutto il pensiero prodotto dalle idee riunite; e quindi il periodo, e un periodo con l'altro; in guisa che ne risulti  una progressione di membri e di suoni [...] e il tutto abbia una variet&agrave; di suoni, di tinte, e di passaggi di luce e di chiaroscuro, che non &egrave; infine del conto se non quell'incantesimo che produce l'armonia, quell'arte che &egrave; s&igrave; difficile nell'architettura, che costituisce la perfezione della pittura, e delle arti belle, e che la Natura ha con s&igrave; divina potenza sparse sovra le cose del'universo...&quot; (<em>Opere</em>, ed. naz., vol. III, t. I, pp. 232-33). Ove il concetto finale &quot;pittorico&quot; di arte ispirata (o dettata) da Natura ci riconduce alla discussione sul Boccaccio &quot;giottesco&quot;. </p>
<p><a name="44"></a><a href="novella7.php#44">44.</a> In questa chiave potrebbe essere anche riletta (come &egrave; stato fatto) la novella performativa di Madonna Oretta. Anche l'incompiuto d'autore (si pensi alla novelletta delle &quot;papere&quot; che introduce la seconda parte del Libro), alluderebbe cos&igrave; ad un ruolo (inter)attivo  della lettrice modello. </p>

<!--note 8-->
<h2>Notes for Page VIII</h2>
<p><a name="45"></a><a href="novella8.php#45">45.</a> Per una discussione di questi rapporti si veda la voce Filoginia/Misoginia, di Cazal&eacute; B&eacute;rard nel <em>Lessico</em>, cit. pp. 116-141.</p>
<p><a name="46"></a><a href="novella8.php#46">46.</a> Si veda la recente e intelligente lettura di Marco Veglia (Novella VI, 9) in: <em>Breviario dei classici italiani. Guida all'interpretazione di testi esemplari da Dante a Montale</em>, a cura di G.M. Anselmi, A. Cottignoli, E. Pasquini, Milano, Bruno Mondadori, 1996, pp. 44-56. E Robert Durling, &quot;Boccaccio on Interpretation: Guido's Escape&quot; in <em>Dante, Petrarch, Boccaccio: Studies in the Italian Trecento in Honor of Charles S. Singleton</em>, a cura di Aldo S. Bernardo, Binghampton, NY, Medieval &amp; Renaissance Texts and Studies, 1983, pp. 273-304. </p>
<p><a name="47"></a><a href="novella8.php#47">47.</a> Cfr. Antonio D'Andrea. <em>Le rubriche del Decameron</em>, &laquo;Yearbook of Italian Studies&raquo; [1973-1975], pp. 41-67. </p>
<p><a name="48"></a><a href="novella8.php#48">48.</a> Non &egrave; questo forse che la critica stessa ha copiosamente praticato con innumerevoli letture di singole novelle? Sono, da questo punto di vista, paragonabili le une alle altre pratiche critiche come quella ad esempio tipizzata dalla <em>Lectura Dantis</em> (consuetudinariamente basata sull'unit&agrave; dei canti)?</p>

<!--note 9-->
<h2>Notes for Page IX</h2>
<p><a name="49"></a><a href="novella9.php#49">49.</a> <em>Teoria della prosa</em> (1924), Torino, 1976, pp. 92-93. </p>
<p><a name="50"></a><a href="novella9.php#50">50.</a> Cfr. ancora Franco Fido, <em>Lessico</em>, cit., p.32: &quot;Al centro di questo sistema, i novellatori del D. producono dicendo le loro storie, come i narratori di Conrad, un evento letterario, e al tempo stesso sono prodotti da altri eventi, in ultima istanza dall'evento storico della peste...&quot;</p>
<!--END of notes-->

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
