<?php
	$selected = "literature";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Literature</a></li>
	<li>La novella tra Testo e Ipertesto: il <em>Decameron</em> come modello VIII</li>
</ul>
<h2>La novella tra Testo e Ipertesto: il <em>Decameron</em> come modello VIII</h2>
<p><strong>VIII.</strong> Tutto dunque si ridurrebbe cos&igrave; al rapporto (&quot;segreto&quot;) tra l'Autore e le sue &quot;carissime donne&quot; (<a name="45"></a><a href="note1.php#45">45</a>)? Ma si pu? davvero ipotizzare (e realizzare ipertestualmente) un anti-modello non-lineare dell'edificio decameroniano che, appartenendo esclusivamente ai piani segreti del Lettore, prenda forma <em>indipendentemente</em>&nbsp;dal disegno d'Autore? Una lettura &quot;post-calviniana&quot; del <em>Decameron</em>&nbsp;parrebbe forse autorizzarlo: non &egrave; un caso che tra la &quot;pluralit&agrave; delle immagini&quot; del <em>Centonovelle</em>&nbsp;Calvino scegliesse proprio quella (performativa) dell'agile salto cavalcantiano, per illustrare, o addirittura modellizzare, la &quot;leggerezza&quot; intrinseca ad ogni &quot;universo&quot; narrativo. Mentre &egrave; facile prendere questa immagine ad analogia dell'assenza di gravit&agrave; di un universo ipertestuale, non va dimenticato che quell'immagine va &quot;letta&quot; secondo l'esegesi &quot;autentica&quot; di Betto Brunelleschi, la quale sembra da parte sua confermare piuttosto, con l'agilit&agrave; abduttiva di un Lettore modello, la <em>gravitas</em>&nbsp;del messaggio/monito cavalcantiano (<a name="46"></a><a href="note1.php#46">46</a>).</p>
<p>&Egrave; l'Autore stesso d'altra parte (quali che siano i suoi impliciti o &quot;segreti&quot; motivi) a concedere ai suoi destinatari anche la libert&agrave; di schermirsi, di essere &quot;padroni a casa (loro)&quot;, sottraendosi al compito di una &quot;lettura modello&quot;: &quot;Tuttavia che va tra queste leggendo, lasci star quelle che pungono e quelle che dilettano legga: elle, per non ingannare alcuna persona, tutte nella fronte portan segnato quello che esse dentro dal loro seno nascoso tengono&quot; (ed. Branca, p. 1259). Proprio l'impalcatura &quot;paratestuale&quot; delle rubriche (studiata da D'Andrea) (<a name="47"></a><a href="note1.php#47">47</a>) consente cos&igrave; di visualizzare una dialettica improntata alla molteplicit&agrave;, alla scelta, alla libert&agrave; del lettore empirico, controbilanciata dalle giunture e gli incastri testuali della cornice. Mentre &egrave; difficile balzare <em>in medias res</em>&nbsp;nella lettura di un canto della <em>Commedia</em>, senza porsi il problema dell'orientamento, del <em>quo tendas</em>&nbsp;anagogico, del punto del viaggio in cui si va ad approdare (l'enciclopedia cosmologica della <em>Commedia</em>) &egrave; pensabile invece entrare nel palazzo-giardino del <em>Decameron</em>&nbsp;per molteplici ingressi laterali, per la porticina di una qualunque novella (rubrica), senza vertigini o spaesamento eccessivi (e le competenze del lettore &quot;comune&quot; sono di regola sufficienti a cogliere almeno i nessi se non i molteplici sensi della narrazione in corso). In termini ipertestuali, l'autore ci fornisce cos&igrave;, a cominciare dalle rubriche (le singole voci della sua enciclopedia narrativa), un sistema aperto di navigazione.</p>
<p>Il <em>Decameron</em>&nbsp;risulterebbe dunque paradossalmente &quot;sgangherabile&quot; per lo stesso principio per cui si tiene insieme, tale sgangherabilit&agrave; risiedendo proprio nella sua frantumazione in singole novelle, micro-universi narrativi i quali contengono, a loro volta, l'abbrivio a molteplici &quot;navigazioni&quot; (e interpretazioni) possibili, moltiplicati viaggi testuali, ivi compresi gli itinerari che li collegano tarsversalmente alle altre novelle della stessa giornata o delle altre giornate, dello stesso narratore/narratrice, di altri membri della brigata e cos&igrave; via, addirittura, al di l&agrave; dei confini del Testo, indietro ai repertori delle fonti o delle tipologie narrative e avanti, via esplorando, all'Enciclopedia virtuale della Letteratura, alla Biblioteca o iper-Biblioteca virtuale del Sapere ecc. ecc (<a name="48"></a><a href="note1.php#48">48</a>) ... </p>
<p>&Egrave; una fondamentale cooperazione (se non una univoca intesa) tra Testo e Lettore (empirico) che l'architettura di un ipertesto ispirato al <em>Decameron</em>&nbsp;deve dunque tentare, a nostro avviso, di mettere in atto o in cantiere: una cooperazione che, mentre da un lato rispetti i modelli culturali, l'enciclopedia che sottende o informa il suo oggetto, non trascuri nemmeno le ragioni costruttive, specifiche delle proprie parziali e locali &quot;competenze&quot;. Certo, una lettura arbitrariamente &quot;locale&quot; o deliberatamente parziale, oltre che trasversale, rischia di mancare proprio il gioco di sottili rimandi interni che solo una lettura lineare e integrale dell'Opera consente di ricostruire, a partire dall'ordo autoriale; ma anche questa, a ben guardare, non pu? fare a meno dell'apporto di un lettore mentalmente e culturalmente aperto all'esplorazione multidirezionale del testo. In un certo senso questo &egrave;, come si diceva, <em>virtualmente</em>&nbsp;previsto dalla stessa <em>Intentio Operis</em> (e non &egrave; forse questo che la critica decameroniana ha fatto e continua a fare con i suoi ripetuti e non esauriti esercizi di ricostruzione/interpretazione dell'architettura complessa del D.?)</p>

<?php
	include 'relatedPages.php';
?>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
