<?php
	$selected = "literature";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Literature</a></li>
	<li>La novella tra Testo e Ipertesto: il <em>Decameron</em> come modello IV</li>
</ul>
<h2>La novella tra Testo e Ipertesto: il <em>Decameron</em> come modello IV</h2>
<p><strong>IV.</strong> Pare allora utile soffermarsi innanzitutto sulla nozione di &quot;enciclopedia&quot; sottoposta, in un'epoca di vorace &quot;pluralismo enciclopedico&quot; come l'attuale, a molteplici sollecitazioni: a) come categoria storica che interessa pi&ugrave; di una formazione culturale ma che pure viene a caratterizzarsi per differenza &quot;epistemologica&quot; tra l'una e l'altra formazione storica; e b) come modello semiotico meta-storico; come scrive Eco, &quot;un'ipotesi regolativa in base alla quale, in occasione delle interpretazioni di un testo (sia esso una conversazione all'angolo della strada o la Bibbia [o il <em>Decameron</em>]), il destinatario decide di costruire una <em>porzione</em>&nbsp;di enciclopedia concreta che gli consenta di assegnare o al testo o all'emittente una serie di competenze semantiche&quot; (<a name="19"></a><a href="note1.php#19">19</a>). Da sottolineare, in quest'ultima citazione, l'enfasi sulla <em>decisione costruttiva</em>&nbsp;del destinatario: poich&eacute; solo di queste &quot;enciclopedie locali e parziali... &egrave; possibile la rappresentazione&quot; (<a name="20"></a><a href="note1.php#20">20</a>). Ci pare, questo, un punto essenziale proprio in relazione alla costruzione o progettazione di un ipertesto <em>del</em>&nbsp;o <em>intorno</em>&nbsp;al <em>Decameron</em>&nbsp;.</p>
<p>Nella progettazione <em>concreta</em>&nbsp;di un ipertesto vengono infatti a confluire sia l'ipotesi &quot;regolativa&quot; enciclopedica, sia la decisione costruttiva <em>del destinatario</em>&nbsp;di assemblare un'enciclopedia locale e parziale che, <em>nei meccanismi</em>&nbsp;del proprio assemblaggio, rifletta, per approssimazione, tanto la &quot;grammatica&quot; o l' &quot;enciclopedia&quot; sottesa al Testo (le competenze linguistiche e semantiche necessarie ad interpretarlo <em>correttamente</em>&nbsp;se non &shy; cosa implausibile &shy; <em>esaustivamente</em>&nbsp;) quanto le ragioni (o i motivi) del <em>proprio</em>&nbsp;assemblare. Va sottolineato ancora come non si tratti qui soltanto di una questione &quot;tecnica&quot; ma di una vera e propria mossa epistemologica che mette a confronto i nostri modelli culturali con quelli implicati da o embricati all'oggetto che ci proponiamo di studiare. La nozione stessa di &quot;enciclopedia&quot; risulta infatti al centro di un fondamentale mutamento di paradigma, tra Medioevo ed Et&agrave; Moderna, schematizzato 		cos&igrave; (come &egrave; noto) da Umberto Eco: </p>
<blockquote>Ma &egrave; la nozione di enciclopedia come regesto del sapere che dopo Dante muta. Non &egrave; che al Rinascimento e alle epoche successive manchi la nozione di enciclopedia del sapere &shy; anzi, l'enciclopedismo rinascimentale e barocco &egrave; pi&ugrave; vorace e totalitario di quello medievale, perch&eacute; invade anche i territori della nuova scienza. Ma per quanto riguarda il filone neoplatonico ed ermetico, che &egrave; quello che influenzer&agrave; gran parte dell'estetica moderna, l'enciclopedia non pu&ograve; pi&ugrave; essere n&eacute; chiusa n&eacute; univoca, n&eacute; garantita da un'autorit&agrave; , come avveniva per la chiesa medievale. Se il mondo &egrave; infinito e se tutti gli esseri possono apparentarsi secondo una rete continuamente mutevole di simpatie e somiglianze, l'interrogazione della foresta simbolica del mondo rimarr&agrave; perennemente aperta. E quanto pi&ugrave; sar&agrave; aperta, tanto pi&ugrave; sar&agrave; difficile, sfuggevole, misteriosa, riservata a pochi. Il didascalismo scolastico usava e legittimava le allegorie per <em>spiegare</em>&nbsp;meglio un mistero a tutti, anche agli indotti. Il simbolismo rinascimentale ricorre a geroglifici esotici e a lingue ignote per celare al volgo delle verit&agrave; che sono comprensibili solo all'iniziato... Ci vuole poco a trasferire questa nozione della lettura dell'universo nella nozione di lettura aperta dei testi poetici e delle opere d'arte in generale. N&eacute; sar&agrave; arbitrario osservare che queste idee sono contemporanee al profilarsi del principio protestante della libera interpretazione delle Scritture, e quindi alla nascita dell'ermeneutica moderna (<a name="21"></a><a href="note1.php#21">21</a>)... </blockquote>
<p>C'&egrave; da chiedersi intanto in che misura a questo fondamentale mutamento di paradigma (che conduce sino a quella che Eco stesso ha chiamato la &quot;semiosi illimitata&quot; che caratterizzerebbe la cultura cosiddetta &quot;postmoderna&quot;) abbia contribuito, con maggior peso di quanto non si sia intuito o spiegato finora, anche il processo tecnologico, a cominciare dalla &quot;rivoluzione gutenberghiana&quot;. Lettura aperta o libera interpretazione (per adottare i termini di Eco) e trasformazioni nelle tecniche e pratiche del leggere e dello scrivere (antecedenti all'avvento della stampa ma &quot;codificate&quot; nel &quot;paradigma&quot; tipografico) sembrano andare (o rinforzarsi) di pari passo (<a name="22"></a><a href="note1.php#22">22</a>). Oggi siamo forse in grado di apprezzare meglio, retrospettivamente, questo intreccio tra modelli culturali da un lato e strumentazione tecnica dall'altro. Proprio ora che, come si diceva, la rivoluzione tecnologica sembra fornirci gli ausil&icirc; necessari ad una visualizzazione di tipo nuovo del &quot;modello&quot; decameroniano, sembra cruciale tener conto del fatto che tale visualizzazione implica anche l'incorporazione (e visualizzazione) dei nostri stessi strumenti critici, dei nostri modelli ermeneutici applicati al testo, in questo caso ad un testo &quot;medievale&quot; (<a name="23"></a><a href="note1.php#23">23</a>).</p>
<p>A differenza che in un ipertesto d'Autore, in un ipertesto del Lettore la prospettiva del lettore professionale e quella del lettore non professionale, &quot;comune&quot;, vengono a misurarsi e intersecarsi (o controllarsi, o falsificarsi) a vicenda, ma non gerarchicamente, in una forma nuova della comunicazione letteraria consentita, stimolata o favorita dai nuovi ambienti &lt;?&gt;&gt; della lettura/scrittura 		elettronica. Se il testo &egrave; sempre il centro di gravit&agrave; di questa 		comunicazione &egrave; per&ograve; concepibile una sua estensione o propensione 		virtuale, centrifuga, quella che rifacendoci ancora alla terminologia di Eco, potremmo chiamare una <em>Intentio Operis Virtualis</em>, non data una volta per tutte o virtualmente depositata nella &quot;forma&quot; archetipica (o enciclopedica) &quot;meta-storica&quot; dettata dall'Autore o dall'Opera (o dalla nostra formalizzazione di quest'ultima) ma perennemente in progresso (o in processo), sollecitata ad esistere dalla libert&agrave; (e dall'empiria stessa) del lettore <em>empirico</em>, dalla costruzione (sempre parziale e locale) di un' &quot;enciclopedia&quot;, o di un apparato interpretativo, che non pu&ograve; non variare insieme alle coordinate temporali, culturali, psicologiche, alle specifiche competenze semantiche di chi va costruendolo (<a name="24"></a><a href="note1.php#24">24</a>). </p>
<p>Per inciso, crediamo che questo modello (o anti-modello) di ipertesto del Lettore non sia del tutto alternativo all'altro, l'ipertesto d'Autore, al contrario: che si tratti di due ipotesi complementari di impostazione e progettazione ipertestuale, allo stato attuale delle cose destinate (se non a integrarsi a vicenda) a intrecciare un fecondo e serrato dialogo a distanza (una distanza del tutto relativa, vista la possibilit&agrave; pressoch&eacute; istantanea di collegamenti, ibridazioni e &quot;sconfinamenti&quot; creativi tra un modello e l'altro). &Egrave; nostra convinzione, infatti, che un ipertesto del Lettore, sommariamente descritto sopra nei suoi principi ispiratori, lungi dal tradire il suo soggetto-oggetto (il testo di Boccaccio), possa anzi riflettere una rinnovata fedelt&agrave; tanto al suo significato &quot;storico&quot; di testo &quot;medievale&quot; che alla sua natura &quot;comunicativa&quot;, meta-storica di opera narrativa. </p>

<?php
	include 'relatedPages.php';
?>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
