<?php
	$selected = "literature";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Literature</a></li>
	<li>La novella tra Testo e Ipertesto: il <em>Decameron</em> come modello V</li>
</ul>
<h2>La novella tra Testo e Ipertesto: il <em>Decameron</em> come modello V</h2>
<p><strong>V.</strong> Tra testo e ipertesto, la <em>novella</em>&nbsp;decameroniana (con la sua carica di notizia o informazione e novit&agrave;, o innovazione, da una parte e di<em> finzione e simulazione narrativa</em>&nbsp;dall'altra) forma genetica di una pi&ugrave; generale economia delle forme simboliche nella societ&agrave; mercantile al suo nascere, sollecita dunque oggi pi&ugrave; che mai, nell'et&agrave; di un'economia mercantile e discorsiva ormai dispiegata (se non addirittura &quot;totalitaria&quot;), il gioco dell'interpretazione. Vale dunque la pena di ritornare al tema centrale del nostro intervento: il modello (o antimodello) decameroniano, alla luce del dibattito teorico e critico pi&ugrave; recente. E ripartiamo dalla questione dell'enciclopedismo: &egrave; certamente lecito domandarsi, a questo proposito, che posto occupi il <em>Decameron</em>&nbsp;nel macro-processo descritto da Eco, se e quanto esso partecipi della dinamica sopra delineata.</p>
<p>Opera, come si &egrave; gi&agrave; ripetuto pi&ugrave; volte, &quot;modellizzante&quot; quant'altre mai, nell'architettura del <em>Decameron</em>, nella codificazione della <em>narratio brevis (novella)</em>&nbsp;da esso operata, enciclopedismo medievale e apertura &quot;moderna&quot; si confrontano (e si scontrano) gi&agrave;, trovando un equilibrio che non pare affatto azzardato definire, alla luce dell'evoluzione successiva della novellistica, irripetibile. Se, infatti, come 		ha scritto Michelangelo Picone, il &quot;<em>Decameron</em>&nbsp;sembra strutturarsi come l'inversione parodica dell'<em>ordo</em>&nbsp;enciclopedico [medievale], rinvenibile nelle raccolte di <em>exempla</em>&nbsp;o nei trattati di predicazione, che sono stati il suo antimodello&quot;, come lo stesso titolo (o nome proprio) dell'opera segnala (<a name="25"></a><a href="note1.php#25">25</a>), non va, in tale inversione parodica, sottovalutata (ed anzi va rivalutata in pieno) la strategia retorica ammiccante nel sottotitolo, la cognominazione &quot;prencipe Galeotto&quot;. Perch&egrave; se il nome del Libro rimanda ad un <em>ordo</em>&nbsp;autoriale (pur se parodico), il cognome apre invece la via ad un <em>ordo</em>&nbsp;o ad un antimodello (anch'esso parodico?) che gravita decisamente <em>dal lato del Lettore, o meglio delle Lettrici</em>, &quot;destinatarie&quot; della <em>finzione narrativa</em>&nbsp;(<a name="26"></a><a href="note1.php#26">26</a>).</p>
<p>Soffermiamoci allora un po' pi&ugrave; da vicino su questa duplice strada apertaci <em>simultaneamente</em>&nbsp;dal testo per il suo attraversamento, la sua interpretazione, il suo &quot;uso&quot; e &quot;consumo&quot; &quot;performativi&quot; e, nel nostro caso, la sua visualizzazione o &quot;rappresentazione&quot; enciclopedica e ipertestuale (<a name="27"></a><a href="note1.php#27">27</a>). Se, infatti, di &quot;inversione parodica&quot; si tratta, che non si tratti di una <em>semplice</em>&nbsp;inversione fa subito testo la pluricommentata novella d'esordio 		di Ser Cepparello/San Ciappelletto, <em>falsario</em>: in cui, tra &quot;ribaltamento&quot; parodico di modelli culturali tradizionali e attuazione &quot;performativa&quot; di pulsioni avvertite come radicalmente trasgressive (per dirla con Todorov, le pulsioni &quot;demoniache&quot; di uno &quot;scambio falsato&quot;), &egrave; di fatto l'ambiguit&agrave; (o polisemia) del messaggio poi a prevalere (<a name="28"></a><a href="note1.php#28">28</a>). Il che rende vano, a nostro avviso, ogni tentativo di fare ad esempio del <em>Decameron</em>&nbsp;un testo <em>semplicemente</em>&nbsp;speculare (o &quot;inverso&quot;) alla <em>Commedia</em>&nbsp;dantesca (lungo il vettore &quot;orrido cominciamento&quot;-&quot;dilettevole&quot; e &quot;utile&quot; e &quot;salvifica&quot; conclusione), per deciderne cos&igrave;, una volta per tutte, l'<em>ordo</em>, il codice, la somma (o <em>summa</em>) delle competenze necessarie ad una interpretazione (o lettura) corretta o autentica. Il che ha delle conseguenze determinanti sulla natura del modello comunicativo che il <em>Decameron</em>&nbsp;incarna o, meglio ancora, si presta a rappresentare.</p>
<p>Non a caso, Boccaccio rinuncia di fatto a collocare preliminarmente il suo &quot;anti-eroe&quot;, (Cepparello, il peggior uomo che mai vivesse, artista della falsificazione e della inversione) in paradiso o all'inferno, lasciando al lettore l'improba decisione (o almeno un minimo dubbio). Ambiguit&agrave; rinforzata, a ben guardare, dal &quot;motto malizioso e equivoco&quot; (Branca) con cui Dioneo licenzia alla brigata (e alle donne) l'ultima delle cento novelle (l'<em>exemplum</em>&nbsp;di santit&agrave; di un Giobbe al femminile, Griselda) e riconfermata ulteriormente dal senso complessivo della Conclusione dell'Autore (e non a caso accomiatandosi il Libro ribadisce tanto il proprio nome che il proprio cognome, ripetendo cos&igrave; un'ultima volta la strategica, autoriflessiva presenza del &quot;paratesto&quot; -- una sorta di auto-modellizzazione testuale -- nella propria conchiusa struttura) (<a name="29"></a><a href="note1.php#29">29</a>). &Egrave;, insomma, la stessa architettura complessa del Testo (l'intervento modellizzante della scrittura, dell'<em>imprint</em>&nbsp;o disegno autoriale) ad offrirci due (o molteplici, secondo l'angolo visuale del Lettore) vie, <em>simultaneamente</em>&nbsp;inerenti al suo statuto <em>narrativo</em>, come inscindibile unit&agrave; di modello/anti-modello, <em>ordo e transgressio</em>&nbsp;(<a name="30"></a><a href="note1.php#30">30</a>).</p>
<p>Non &egrave; tanto al &quot;privilegio di Dioneo (<a name="31"></a><a href="note1.php#31">31</a>)&quot; o agli interventi di commento (diretti o indiretti) dell'Autore inframmezzati alla compagine narrativa che si fa qui implicito riferimento, quanto ad un'altra interessante questione sollevata da Eco in una delle sue passeggiate harvardiane, laddove introduce la categoria della &quot;sgangherabilit&agrave;&quot; di un'opera: &quot;L'immenso, millenario successo della <em>Bibbia</em>&nbsp;&egrave; dovuto alla sua sgangherabilit&agrave;, visto che &egrave; opera di diversi autori. La <em>Divina Commedia</em>&nbsp;non &egrave; per nulla sgangherata, ma a causa della sua complessit&agrave; ... risulta sgangherabile al punto tale che i suoi fanatici la usano persino come riserva di giochi enigmistici...Ma se Dante &egrave; sgangherabile, il <em>Decameron</em>&nbsp;non lo &egrave;, ogni novella va presa nella sua integrit&agrave;&quot; (<a name="32"></a><a href="note1.php#32">32</a>). Questa non-sgangherabilit&agrave; del <em>Decameron</em>&nbsp;sembrerebbe un ostacolo alla sua visualizzazione in un ipertesto &quot;decostruzionista&quot; che faccia lecita la <em>libido</em>&nbsp;di un (qualsiasi) Lettore empirico. D'altra parte, &egrave; significativo il fatto che Eco la collochi al livello della novella (e non dell'Opera nel suo insieme, inclusa la cornice). In ogni caso, la struttura o l'architettura <em>intrinseca</em>&nbsp;dell'opera e il modello comunicativo (di comunicazione letteraria) che essa ispira sembrano, , condizionare qualsiasi tentativo di modellizzazione che noi, con qualsiasi mezzo, intendiamo fornirne.</p>

<?php
	include 'relatedPages.php';
?>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
