<?php
	$selected = "literature";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Literature</a></li>
	<li>La novella tra Testo e Ipertesto: il <em>Decameron</em> come modello VII</li>
</ul>
<h2>La novella tra Testo e Ipertesto: il <em>Decameron</em> come modello VII</h2>
<p><strong>VII.</strong> Per tornare, allora, all'aspetto architettonico del modello-antimodello decameroniano, &egrave; nell'opposizione strategica tra cornice e novelle che sembra giocarsi (come &egrave; stato dibattuto a lungo dalla critica) la dialettica tra ordine autoriale e libert&agrave; del Lettore, la sgangherabilit&agrave; o non-sgangherabilit&agrave; virtuale dell'Opera, necessariamente condizionando cos&igrave; anche il modello di ipertesto che andiamo a costruire. A questo proposito va dunque fatto di chiedersi se il piano (o <em>blueprint</em>&nbsp;) architettonico dell'edificio decameroniano fornisca un disegno <em>univoco</em>&nbsp;di visualizzazione dinamica o lasci invece al lettore lo spazio di una decisione costruttiva. Risaliamo allora, tra le tante formulazioni a nostra disposizione, ad una definizione della critica, quella, illustre, di Auerbach, trascelta qui tra le molte possibili appunto perch&egrave; sembra porsi, tra l' altro, il problema cruciale del rapporto, cui si faceva cenno pi&ugrave; sopra, tra forme narrative e quella che 		Auerbach definiva &quot;forma sociale&quot; e che noi potremmo forse ribattezzare &quot;modello culturale&quot; nella &quot;edificazione&quot; dell'opera: </p>
<blockquote>La cornice del <em>Decameron</em>&nbsp;pu&ograve; essere compresa nel modo pi&ugrave; semplice proprio a partire dal concetto di forma sociale. Cos&igrave; diventa anche evidente perch&egrave; Boccaccio lasci in penombra le caratteristiche dei narratori e le loro reciproche relazioni. Se queste fossero chiare, non pi&ugrave; di cornice si tratterebbe, ma di racconto a s&egrave; stante; agli stessi partecipanti, del resto, esse debbono sembrare cangianti e misteriose; la brigata dei giovani eleganti vive del segreto e della confusione (<a name="40"></a><a href="note1.php#40">40</a>).</blockquote>
<p>Non &egrave; precisamente questo velo, questo &quot;segreto&quot; (pi&ugrave; che &quot;confusione&quot;) che avvolge l'elemento strutturalmente portante dell'architettura decameroniana a consentire l'esplicarsi combinatorio (avrebbe forse detto Calvino) delle singole novelle e a dare cos&igrave; spazio virtuale ad una libera (ri)lettura individualizzata tanto delle novelle che, al limite, dell'opera nel suo complesso (<a name="41"></a><a href="note1.php#41">41</a>)? C'&egrave;, inoltre, un altro punto sollevato da Auerbach che ci pare, a questo proposito, rilevante (su di un altro livello): nella sua codificazione della novella, Boccaccio instaurerebbe il principio di una &quot;pluralit&agrave; delle immagini&quot; (Auerbach usa qui ad illustrazione le novelle di Ciappelletto e Andreuccio), grazie alla quale si generano racconti dalle molteplici sfaccettature, conferendo all'intreccio e al &quot;discorso&quot; una funzione determinante rispetto alla <em>fabula</em>&nbsp;che pone tutti gli elementi in un rapporto gerarchico per cos&igrave; dire mono-figurale, in relazione ad un singolo evento monolitico. Questa &quot;pluralit&agrave; delle immagini&quot;, elemento secondo Auerbach centrale e non pre-esistente, dell'innovazione boccacciana, che libererebbe il genere della novella dalla &quot;semplice immagine&quot; esemplificata nell'aneddoto, l'<em>exemplum</em>, la predica e cos&igrave; via, della narrativa precedente (ripresa dopo di lui dai motti e le facezie di un Poggio o dallo stesso Sacchetti) pu&ograve; essere messa in rilievo solo attraverso una modellizzazione o visualizzazione ipertestuale che non insista univocamente sugli elementi strutturali dell'ordo autoriale, ma lasci, di nuovo, spazio al dispiegarsi di un &quot;principio di indeterminazione&quot;, dipendente dalla sagacia e ingegno e &quot;varianza&quot; interpretativa di un lettore empirico, il quale (nella tensione con il Lettore Modello &quot;prefigurato&quot; nel testo) faccia cos&igrave; salvi anche quei margini di ambiguit&agrave;&quot;comunicativa&quot; ed esuberanza semantica, altrimenti soggiogati o neutralizzati da una lettura talvolta troppo &quot;professionale&quot; (<a name="42"></a><a href="note1.php#42">42</a>).</p>
<p>Il modello comunicativo cos&igrave; embricato nell'opera schiuderebbe dunque la via ad una fruizione, se non del tutto &quot;aperta&quot;, almeno polisemica. Se la simbologia del Libro-Universo, nella <em>Commedia</em>, si esplica al massimo grado nella visione-intuizione puntiforme e unitaria (una visione Autoriale, al confine dell'indicibile) di &quot;ci&ograve; che per l'universo si squaderna&quot; (Par. XXXIII, 87), essa sembra invece diffrangersi nel D. in una auto-rappresentazione del libro (della sua intima struttura o &quot;impaginazione&quot;) non tanto come semplice, artificiale o anonimo (<em>Novellino</em>&nbsp;) contenitore meccanico della molteplicit&agrave; del mondo umano, aperto a una infinita molteplicit&agrave; di possibili letture (e riletture), ma piuttosto &quot;uno scheletro e un guscio tratti dalla natura&quot;, in cui strutture simmetriche fisse e simmetrie imperfette si armonizzano a vicenda, provocando un effetto simile a quello che si prova &quot;davanti a certe forme vegetali o biologiche, una foglia o una conchiglia&quot; (<a name="43"></a><a href="note1.php#43">43</a>). (Dove andrebbe forse sottolineato l'effetto <em>illusionistico</em>&nbsp;all'occhio umano di certe sorprendenti simmetrie &quot;naturali&quot;).</p>
<p>E' ipotizzabile allora che anche il Lettore Modello del <em>Decameron</em>, in quanto lettore di <em>finzioni narrative, in fabula</em>&nbsp;s&igrave; , ma com-partecipe, coadiutore di un modello non univoco, secolarizzato di &quot;comunicazione&quot; letteraria, non possa non essere un lettore proditoriamente <em>ambiguo</em>, secondo l'inversione parodica operata dall'omaggio proemiale del &quot;libro Galeotto&quot; alle Donne melanconiche. Che il messaggio &quot;didascalico&quot; dell'enciclopedia narrativa decameroniana, di quel raffinato &quot;manuale&quot; performativo, di comportamento e interpretazione (<em>sub specie ludica</em>&nbsp;) del Mondo narrato che il <em>Decameron</em>&nbsp;rimane per noi sia, parodicamente, anch'esso affidato alla libera scelta di una (sconosciuta) Lettrice futura (<a name="44"></a><a href="note1.php#44">44</a>)?</p>

<?php
	include 'relatedPages.php';
?>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
