<?php
	$selected = "literature";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Literature</a></li>
	<li>La novella tra Testo e Ipertesto: il <em>Decameron</em> come modello VI</li>
</ul>
<h2>La novella tra Testo e Ipertesto: il <em>Decameron</em> come modello VI</h2>
<p><strong>VI. </strong>Il confronto con la <em>Commedia</em>&nbsp;resta di grande suggestione proprio per una riflessione sul rapporto fondamentale che intercorre tra forme narrative e modelli culturali, riflessione che deve stare alla base di qualsiasi modellizzazione &quot;enciclopedica&quot; (esplorativa o costruttiva) del <em>Decameron</em>&nbsp;entro i nuovi <em>media</em>&nbsp;della scrittura-lettura. Tra parentesi, non &egrave; affatto un caso che queste due opere siano quelle che, a giudicare almeno dal fiorire dei progetti informatici intorno ad esse, pi&ugrave; accendono l'immaginazione tecno-culturale contemporanea. <em>Commedia</em>&nbsp;e <em>Decameron</em>&nbsp;ci presentano infatti due &quot;mondi&quot; possibili della (nostra rappresentazione retrospettiva della) cultura medioevale, due modi diversi di &quot;sognare&quot;, oggi, il Medioevo.</p>
<p>Vale allora, a rischio di essere banali, ripetere che, mentre la compagine narrativa della <em>Commedia</em>, incentrata com'&egrave; sul personaggio/Autore, si regge sul vettore &quot;dinamico&quot;, lineare, ascendente e edificante del &quot;viaggio&quot; (e della perigliosa navigazione, pensiamo ovviamente al &quot;doppio&quot; di Ulisse), quella del <em>Decameron</em>&nbsp;gravita invece, auto-referenzialmente, sull'attivit&agrave; (il passatempo) ciclico del narrare (e del leggere e del commentare-interpretare ci? che &egrave; narrato). Questa strutturazione, se da una parte sembra paradossalmente pi&ugrave; statica, affidata com'&egrave; alla &quot;fissit&agrave;&quot; allegorico-iconografica, sospesa tra narrazione e commento, della &quot;cornice&quot; (una parentesi &quot;paradisiaca&quot; e &quot;atemporale&quot; nel tempo calamitoso della pestilenza) e alla sua separatezza dal Mondo narrato propriamente detto, brulicante, proteico e &quot;carnevalesco&quot; delle cento novelle, dall'altra pu? alludere ad un dinamismo &quot;centrifugo&quot; interno non pi&ugrave; vincolato all'identificazione unitaria tra (Autore) Narratore(personaggio)-Lettore (<a name="33"></a><a href="note1.php#33">33</a>). Si potrebbe infatti aggiungere che proprio la struttura o l'architettura portante del <em>Decameron</em>, apparentemente statica, &quot;visualizza&quot; quella che sembra una caratteristica fondamentale dei possibili mondi o universi ipertestuali: l'atomizzazione in unit&agrave; discrete e la loro multiconnettivit&agrave; trasversale (<em>multidirezionale</em>) a partire da una struttura funzionale di collegamento. </p>
<p>Ovviamente, il <em>Decameron</em>&nbsp;mentre conduce avanti il processo di secolarizzazione gi&agrave; avviato dalla <em>Commedia</em>, muta anche (inverte?) la direzione, il vettore della <em>verosimiglianza</em>, considerata qui non tanto dal punto di vista o entro il codice di un sistema di retorica o poetica autoriale (<a name="34"></a><a href="note1.php#34">34</a>), ma secondo la specifica angolatura della comunicazione e ricezione del messaggio contenuto nel testo. Mentre il sistema allegorico della Commedia presenta (se non altro al lettore moderno, che pu? non condividerne in via di principio le competenze culturali e &quot;enciclopediche&quot;) l'<em>inverosimile</em> come &quot;luogo e forma della verit&agrave;&quot; (teologico-filosofica), il sistema narrativo del <em>Decameron</em>&nbsp;ci presenta invece il <em>verosimile</em>&nbsp; come &quot;luogo e forma della finzione narrativa&quot;. Detto altrimenti, mentre nell'enciclopedia della <em>Commedia</em>&nbsp;l'allegoria &egrave; la chiave, e il velo, della verit&agrave;, in quella del <em>Decameron</em>&nbsp;essa ha la funzione principale di proteggere lo spazio della <em>finzione</em>. Da questo punto di vista, sembra di poter dire che, laddove il vettore fondamentale della <em>Commedia</em>&nbsp;(con tutta la ricchezza delle sue tensioni interne, tra esoterismo ed essoterismo) rimane in fondo quello del &quot;didascalismo scolastico&quot; che, come dice Eco, &quot;usava e legittimava le allegorie per <em>spiegare</em>&nbsp;meglio un mistero a tutti, anche agli indotti&quot; (il che non impedisce agli accoliti di Dante di &quot;sgangherarne&quot; il sistema per i propri giochi iniziatici), il vettore principale del <em>Decameron</em>&nbsp;sembra anticipare invece performativamente, attraverso l'elemento <em>ludico</em>&nbsp;della finzione, un'agnostica attitudine &quot;moderna&quot; che lungi dal ricorrere, come il simbolismo rinascimentale, &quot;a geroglifici esotici e a lingue ignote per celare al volgo delle verit&agrave; che sono comprensibili solo all'iniziato&quot;, sollecita invece il lettore a un salutare e vitale esercizio ingegnoso di interpretazione del mondo umano (troppo umano) in cui, semmai, &quot;geroglifici iniziatici&quot; e &quot;lingue ignote&quot; sono parodicamente insinuati o smascherati come strumenti di interessati o passionali inganni (il che non impedisce affatto di trovare, anzi, a chi lo volesse, racchiuso nell'unit&agrave; dell'Opera, un &quot;superiore&quot; messaggio etico, intonato ai modelli culturali che la improntano) (<a name="35"></a><a href="note1.php#35">35</a>).</p>
<p>Se, insomma, per ricorrere ad una esemplificazione figurativa, il Giotto di Dante &egrave; forse ancora quello di Assisi, il Giotto di Boccaccio ci pone non a caso davanti agli ironici dilemmi dell'apparenza e della simulazione (l'inganno <em>a</em>-morale della natura e dell'arte) mentre suggerisce, a chi voglia leggere oltre, una <em>mimesis</em>&nbsp;e una &quot;lettura dell'universo&quot; dei segni che non pu? non definirsi, col riso scrosciante che l'accompagna, tanto parodica che, aporeticamente, &quot;moderna&quot;:</p>
<blockquote>...Giotto, ebbe uno ingegno di tanta eccellenzia, che niuna cosa d&agrave; la natura, madre di tutte le cose e operatrice col continuo girar de' cieli, che egli con lo stile e con la penna o col pennello non dipignesse s&igrave; simile a quella, che non simile, anzi pi&ugrave; tosto dessa paresse, in tanto che molte volte nelle cose da lui fatte si truova che il visivo senso degli uomini vi prese errore, quello credendo esser vero che era dipinto. E per ci?, avendo egli quell'arte ritornata in luce, che molti secoli sotto gli error d'alcuni, che pi&ugrave; a dilettar gli occhi degli ignoranti che a compiacere allo 'ntelletto de' savi dipignendo, era stata sepulta...&quot; (VI, 5, ed. Branca, p. 737).</blockquote>
<p>Se, in questo passo, al nome di Giotto sostituiamo (<a name="36"></a><a href="note1.php#36">36</a>) quello di Boccaccio stesso, le considerazioni fatte sopra sul rapporto simmetrico-asimmetrico o di modello-antimodello tra <em>Commedia</em>&nbsp;divina e Commedia umana, sistema (enciclopedico-allegorico) dantesco e sistema (enciclopedico-novellistico) boccacciano, consapevolmente (parodicamente?) fondato sulla dialettica tra <em>mimesis</em>&nbsp;e finzione, &quot;diletto&quot; e &quot;intelletto&quot; risultano arricchite di ulteriore complessit&agrave; (<a name="37"></a><a href="note1.php#37">37</a>). Che non si pretende certo di risolvere qui (<a name="38"></a><a href="note1.php#38">38</a>). Val soltanto la pena di indicarle anche in funzione di quella feconda prospettiva critica sul rapporto parola-immagine che fa capo agli studi, intensificatisi di recente, sul &quot;Boccaccio visualizzato&quot;, cui il medium elettronico potr&agrave; per sua natura dare, in un futuro speriamo imminente, impulsi imprevedibili (<a name="39"></a><a href="note1.php#39">39</a>).</p>

<?php
	include 'relatedPages.php';
?>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
