<?php
	$selected = "literature";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Literature</a></li>
	<li>La novella tra Testo e Ipertesto: il <em>Decameron</em> come modello II</li>
</ul>
<h2>La novella tra Testo e Ipertesto: il <em>Decameron</em> come modello II</h2>
<p><strong>II.</strong> Partiamo da una facile constatazione, quella che, per tutto il Novecento almeno, il <em>Decameron</em>&nbsp;&egrave; stato un testo di straordinaria suggestione e fertilit&agrave;, secondo una duplice prospettiva: in quanto &quot;grammatica&quot; di forme diegetiche (ovvio il richiamo ai contributi &quot;narratologici&quot; di Viktor Sklovskij e Tzvetan Todorov) e in quanto &quot;enciclopedia&quot; narrativa della cultura medievale (altrettanto ovvio il richiamo ai lavori di Vittore Branca). Possiamo aggiungere che entrambe queste prospettive (variamente intersecantesi nella storia della critica decameroniana) si sono intrecciate ad una vicenda filologica tra le pi&ugrave; avvincenti (tanto da sfiorare un autentico &quot;giallo ecdotico&quot;, come scrive ancora Vittore Branca nel <em>Lessico</em>) (<a name="08"></a><a href="note1.php#08">8</a>). Pi&ugrave; di recente l'attenzione di critici e studiosi sembra essersi focalizzata, oltre che sulla &quot;forma-novella&quot;, su quello che, con Forni (<a name="09"></a><a href="note1.php#09">9</a>), potremmo definire lo &quot;statuto testuale&quot; o il &quot;modello complesso&quot; del <em>Decameron</em>, (il rapporto microtesti-macrotesto, o novelle-cornice entro il &quot;sistema enciclopedico&quot; dell'opera ecc.), diffrangendosi poi ulteriormente su di un duplice versante: quello che potremmo chiamare dei moduli o modelli di produzione retorica e quello, pi&ugrave; ampio, definibile invece della ricezione del testo, sulle tracce di una dinamica significativamente prefigurata (o, addirittura, modellizzata) nel testo stesso di Boccaccio, a partire (per intendersi) dall'identificazione &quot;retorica&quot;, nel <em>Proemio</em>, di uno specifico gruppo di &quot;lettori ideali&quot; (le donne melanconiche).</p>
<p>L'avvento dei nuovi strumenti e del nuovo paradigma &quot;elettronico&quot; 		costituiscono a nostro avviso un'occasione di ulteriore verifica (o rilancio) di queste prospettive di fondo, offrendo al contempo un test fertile di conseguenze per il lettore contemporaneo (professionale e non). Intanto, come si diceva, la stessa vicenda filologica sta per arricchirsi di un nuovo capitolo. La codificazione ipertestuale del <em>Decameron</em>&nbsp;a partire dalla edizione elettronica di una costellazione (da rendere accessibile in rete) di testi &quot;preparatori&quot;, manoscritti e <em>Zibaldoni</em>, autentici &quot;libri-archivi d'autore&quot; (secondo l'espressione di Armando Petrucci ripresa da Claude Cazal&eacute; B&eacute;rard) offre un primo terreno di dibattito: che cosa comporta, quali sono le modalit&agrave;specifiche di tale codificazione, quali le operazioni implicite di lettura, i modelli semiologici che vengono per cos&igrave; dire &quot;incorporati&quot; in un testo all'atto della sua codifica, sono tutti quesiti che la filologia informatica deve porsi con rinnovata consapevolezza teorica (e tecnica) ma che tuttavia (come &egrave; sempre avvenuto nel vasto universo della letteratura) non esauriscono lo spettro pi&ugrave; ampio delle questioni all'ordine del giorno (<a name="10"></a><a href="note1.php#10">10</a>). &Egrave; ormai chiaro infatti che il lavoro filologico-informatico in corso consente tanto di gettare nuova luce, una luce retrospettiva, sul passaggio (non indenne) del testo in tutte le sue fasi di &quot;produzione&quot; o &quot;costituzione&quot;, entro vari &quot;paradigmi&quot; (da quello chirografico a quello tipografico per giungere infine a quello elettronico o &quot;compugrafico&quot;) e dunque attraverso vari stad&icirc; di &quot;concretizzazione&quot; (per adottare la terminologia della scuola di Costanza), quanto di stimolare un'autoriflessione radicale della filologia stessa quale &quot;sistema ermeneutico totale&quot; (<a name="11"></a><a href="note1.php#11">11</a>). Non a caso, in un capitolo del suo <em>Notizie dalla crisi</em>, nell'ambito di una discussione del libello di Paul Zumthor, <em>Parler du Moyen Age</em>, lo stesso Cesare Segre ribadisce quanto l'obiettivo ermeneutico gadameriano della &quot;fusione di orizzonti&quot; (del testo e del lettore) debba avvalersi, pi&ugrave; di quanto non ne venga ostacolato, di un'idea della comunicazione letteraria &quot;messa in forma che sia consumabile oggi&quot; ed ogni ponte ecdotico lanciato sui baratri dell'alterit&agrave; culturale medioevale (o sulle infide paludi di una inafferrabile <em>mouvance</em> dei testi) sia destinato a munirsi di una prospettiva semiologica ben radicata nel presente (<a name="12"></a><a href="note1.php#12">12</a>). =</p>
<p>Proprio in questa luce pare cruciale tornare a riflettere sul &quot;modello decameroniano&quot;, e tanto pi&ugrave; nel momento in cui il mezzo elettronico ci fornisce gli strumenti cognitivi e pragmatici di una sua inedita &quot;concretizzazione&quot; (codificazione, rappresentazione e visualizzazione comunicativa) appunto &quot;consumabile oggi&quot; (<a name="13"></a><a href="note1.php#13">13</a>). </p>

<?php
	include 'relatedPages.php';
?>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
