<?php
	$selected = "literature";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Literature</a></li>
	<li>La novella tra Testo e Ipertesto: il <em>Decameron</em> come modello III</li>
</ul>
<h2>La novella tra Testo e Ipertesto: il <em>Decameron</em> come modello III</h2>
<p><strong>III. </strong>Nel gi&agrave; citato intervento su Internet, volto a presentare i criteri di un'edizione ipertestuale guidata da una <em>intentio</em>&nbsp;critico-filologica, l'universo discorsivo, o se si vuole, l'archivio d'autore che fa capo al nome di Giovanni Boccaccio viene differenziato rispetto a quello che fa capo a Dante, perch&egrave; esso presenterebbe le caratteristiche di un &quot;sistema&quot; dialettico-retorico (interpretativo-narrativo) non pi&ugrave; rigorosamente finalizzato alla persuasione e sottostante il controllo di un principio di autorit&agrave; ma al contrario finalizzato alla creazione e &quot;fabbricazione&quot; di <em>finzioni</em>. Gli <em>Zibaldoni</em>&nbsp;di Boccaccio (<em>Laurenziano</em>&nbsp;XXIX-8 e <em>Magliabechiano</em>&nbsp;II-327, Banco Rari 50) e la <em>Miscellanea</em>&nbsp;(<em>Laurenziana</em>&nbsp;XXXIII-31), verrebbero cos&igrave; a costituire &quot;un esempio di ipertesto pre-informatico&quot;, o una sorta di &quot;enciclopedia provvisoria&quot; disponibile ad una &quot;molteplicit&agrave; di percorsi di lettura e di trattamenti&quot; (<a name="14"></a><a href="note1.php#14">14</a>). C'&egrave; tuttavia da chiedersi quanto questo modello di ipertesto sia condizionato, oltre che oggettivamente dallo stato degli &quot;archivi-libri d'autore&quot; a nostra disposizione, anche dall'ottica specifica in cui si colloca il lettore professionale, il lettore-filologo (<a name="15"></a><a href="note1.php#15">15</a>). Per il quale, l'acquisizione delle nuove categorie ipertestuali da una parte conduce a &quot;visualizzare&quot; lo stesso sistema compositivo autoriale come gi&agrave; obbediente a una &quot;forma&quot; o una &quot;logica&quot; ipertestuale &shy;un Ipertesto d'Autore (<a name="16"></a><a href="note1.php#16">16</a>)&shy; anche se di ipertesto &quot;pre-informatico&quot; si tratta (nozione in s&egrave; problematica, se non, a prima vista, addirittura paradossale), dall'altra consente di riattualizzare il principio d'Autore (storicizzato criticamente come &quot;enciclopedico&quot;) a criterio legittimo della informatizzazione in corso. L'evidente circolarit&agrave; dell'argomento &egrave;, a nostro avviso, un prodotto diretto della convergenza di cui parliamo e dev'essere quindi attentamente vagliato come tale: una sorta di riformulazione (entro il nuovo paradigma tecno-culturale) del circolo ermeneutico (<a name="17"></a><a href="note1.php#17">17</a>). </p>
<p>Il problema &egrave; dunque formulabile cos&igrave;: la formalizzazione e rappresentazione del testo consentita dal mezzo elettronico ci consente di farne emergere (per cos&igrave; dire) le strutture compositive profonde e latenti? O non &egrave; piuttosto un &quot;transfert&quot;, una proiezione nella struttura del testo dei nostri modelli di formalizzazione e rappresentazione, allo stato attuale delle conoscenze e dati appunto gli strumenti che utilizziamo? Rinunciando a fornire una prematura risposta a questi pur fondamentali quesiti, rimane tuttavia da chiedersi se l'Ipertesto d'Autore sia l'unico ipertesto pensabile a partire dal <em>Decameron</em>. Ad un modello di ipertesto d'Autore, quale quello delineato sopra, viene infatti ad opporsi, nel panorama teorico contemporaneo, un &quot;anti-modello&quot;, un ipertesto <em>del Lettore</em>, in cui a predominare non &egrave; tanto la ricostruzione di una ipotetica <em>intentio Auctoris</em>&nbsp;ma semmai la tensione dinamica tra il Lettore Implicito o Ideale o Modello incorporato nel Testo (il <em>Lector in Fabula</em>) e il lettore empirico contemporaneo (apprendista, dilettante, <em>bricoleur</em>...), svincolato da ogni &quot;tradizione&quot;, con le sue istanze vagamente anarchiche e non sussumibili o riducibili interamente al funzionamento virtuale di <em>un</em>&nbsp;Testo (in questo caso il <em>Decameron</em>) ma nomadicamente predisposto (e in ci&ograve; facilitato dai nuovi strumenti e ambienti della lettura/scrittura elettronica) allo sconfinamento o all'attraversamento di svariati (virtualmente 		&quot;infiniti&quot;) &quot;domin&icirc;&quot; o &quot;mondi&quot; testuali (<a name="18"></a><a href="note1.php#18">18</a>). Tale lettore &egrave; dunque animato, nella migliore delle ipotesi, da un istinto &quot;enciclopedico&quot; del tutto asistematico che trova riscontro nell'enciclopedia &quot;rizomatica&quot; del sapere contemporaneo di cui le reti telematiche sarebbero una eloquente &quot;concretizzazione&quot;.</p>

<?php
	include 'relatedPages.php';
?>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
