<?php
	$selected = "brigata";
	require '../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../">Main</a></li>
	<li><a href="index.php">Brigata</a></li>
	<li><a href="filostrato.php">Filostrato</a></li>
	<li>Nightingales and Filostrato's Apologia</li>
</ul>
<h2>Nightingales and Filostrato's Apologia (V.4)</h2>
<p>Fiammetta's succession of Filostrato as ruler of the <em>brigata</em>&nbsp;on day V marks the continuation of an exchange between the two narrators which can be read in their respective tales of the fourth day. Several critics have seen Fiammetta's tale of Tancredi and Ghismonda (<a href="../texts/DecShowText.php?lang=eng&myID=nov0401&expand=day04">IV.1</a>) as an encoded critique of Filostrato's rule over the <em>brigata</em>, an attack which does not go unanswered by Filostrato. By concluding his tale of Guiglielmo di Rossiglione (<a href="../texts/DecShowText.php?lang=eng&myID=nov0409&expand=day04">IV.9</a>) with a more savage variation of the imagery used by Fiammetta in her tale (the lover's excised heart), he provides a biting if indirect response to Fiammetta's implicit censure of his rule.</p>
<p>When Filostrato crowns Fiammetta at the end of Day IV, his brief speech indicates his awareness of the displeasure his choice of theme has created: &quot;I give you this crown, since you better than anyone else can console the band for the harshness of today by what you will order tomorrow.&quot; And in his introductory remarks to his own tale of the fifth day he promises to atone for his harsh rule of the previous day by telling an amusing tale.</p>
<p>Yet several features of the story of Ricciardo and Caterina (<a href="../texts/DecShowText.php?lang=eng&myID=nov0504&expand=day05">V.4</a>) vitiate Filostrato's declared apologetic intentions. First among these is his repetitive use of the obscene nightingale metaphor (matched in its transgression perhaps only by Dioneo's tale of Alibech [<a href="../texts/DecShowText.php?lang=eng&myID=nov0310&expand=day03">III.10]</a>), which seems designed to shock the ladies of the <em>brigata</em>. More importantly, however, Filostrato's tale emerges as an ironic rewriting of Fiammetta's tale of Tancredi and Ghismonda. The similarities between the two tales are readily apparent: both Caterina and Ghismonda are much beloved, overprotected daughters; Ricciardo is a trusted visitor in messer Lizio's home, much as Guiscardo was a trusted servant of Tancredi; both Caterina and Ghismonda are discovered <em>in flagrante delicto</em>&nbsp;by their respective fathers after having arranged clandestine meetings with their lovers.</p>
<p>The reactions of the betrayed fathers bear a striking likeness to one another as well. Messer Lizio's words to Ricciardo, &quot;Ricciardo, the love and trust I bore you did not merit this&quot; strongly echo those of Tancredi to Guiscardo, &quot;Guiscardo, my kindness to you has not merited the outrage and shame you have done me.&quot; The similarities between the two tales end here, as messer Lizio's astuteness (with an eye towards the social position of Ricciardo) and paternal understanding replace the jealous rage of Tancredi, diffusing the potentially tragic situation and leading to an impromptu wedding on the veranda.</p>
<p>In addition to these general parallels between the two stories, a passage at the height of the novella's dramatic tension provides even better grounds for reading Filostrato's tale as a palinode of IV.1. Ricciardo's reaction upon being discovered with Caterina by messer Lizio is described as follows: &quot;Quando Ricciardo il vide, <em>parve che gli fosse strappato il cuore</em>. (&quot;When Ricciardo saw him, he felt as though his heart had been ripped from his body,&quot; italics added).</p>
<p> This quick but clear allusion to the tragic outcome of IV.1 reminds the <em>brigata</em>, and Fiammetta in particular, that he is now obeying her edict and adhering to the &quot;pleasure principle&quot; of the <em>brigata</em>, as he had promised to do in his introductory remarks to the tale. The brutal literalization of the heart on Day IV has been replaced by the figurative song of the nightingale. Yet by modeling his story of Caterina and Ricciardo on Fiammetta's tale of the fourth day, by &quot;rewriting&quot; <em>her</em>&nbsp;tale, Filostrato continues the repartee which began on the previous day.</p>
<p>(A. T.) Marcus, Millicent. &quot;Tragedy as Trespass&quot; in <em>An Allegory of Form: Literary Self-Consciousness in the</em>&nbsp;Decameron. Stanford, CA: Anma Libri, 1979. pp. 48-65. For an interesting analysis of the thematic continuity of Days IV-V see: Sherberg, Michael. &quot;The Patriarch's Pleasure and the Frametale Crisis: <em>Decameron</em>&nbsp;IV-V.&quot; <em>	Romance Quarterly</em>&nbsp;38:2 (1991): 227-38. </p>
	
<?php
	$last_modified =  filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../footer.php';
?>
