<?php
	$selected = "brigata";
	require '../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../">Main</a></li>
	<li><a href="index.php">Brigata</a></li>
	<li><a href="filostrato.php">Filostrato</a></li>
	<li>Filostrato's Reign and the Proem</li>
</ul>
<h2>Observations on the Relation of Filostrato's Reign on Day IV to the Proem of the <em>Decameron</em></h2>
	<p>The placement of Boccaccio's defense and <a href="../texts/DecShowText.php?lang=eng&myID=d04intro&expand=day04">the half-tale of Filippo Balducci</a> before the storytelling of <a href="../texts/DecShowText.php?lang=eng&myID=day04&expand=day04">the fourth day</a> presents a frame which demands close consideration for an interpretation of the tragic tales which follow. Certainly the higher register of tragedy may be read as a response to the critics who claim that the subject matter of the <em>Decameron</em>&nbsp;is unworthy of the Muses. Yet notwithstanding the importance of the interpretive problems which the frame of the Narrator's introductory defense poses, Filostrato's justification of his choice of theme at the end of Day III brings to the foreground the first and all-encompassing frame of the <em>Decameron</em> which is first established in <a href="../texts/DecShowText.php?lang=eng&myID=d01intro&expand=day01">the Proem</a>. Read in the light of the Narrator's autobiographical depiction of the genesis of his work (presented in the first half of the Proem), Filostrato's reign marks a crucial [counter]point in the development of the theme of pleasure and its relation to storytelling.</p>
	<p>At the outset of their sojourn, Pampinea establishes pleasure-seeking as one of the premises of the <em>brigata</em>'s existence: &quot;...let us amuse ourselves, for that was the reason why we fled from our sorrows.&quot; After three days of harmonious cohabitation, Filostrato's reign on Day IV threatens to disrupt the society of the <em>brigata</em>. The storyteller's resistance to his choice of theme is evident on several textual levels. Fiammetta introduces her tale in protest of Filostrato's decision: &quot;Our king has given us a sad theme for tale-telling today, thinking that as we came here to enjoy ourselves it is befitting to speak of the tears of others...&quot;</p>
	<p>In addition to her explicit censure, several critics, following Millicent Marcus' analysis, have read Fiammetta's tale of Prince Tancredi and Ghismonda as an encoded critique of Filostrato's rule. By telling a story about a prince whose amorous jealousy leads to tyranny and bloodshed, Fiammetta provides king Filostrato with a devastating depiction of his failing as ruler of the <em>brigata</em>. Pampinea, by telling the comic tale of Frate Alberto (<a href="../texts/DecShowText.php?lang=eng&myID=nov0402&expand=day04">IV, 2</a>), is the most openly disobedient to Filostrato's edict, and her decision reflects the extent to which Filostrato has offended the brigata's will: &quot;Pampinea felt the wishes of the company more through her own affection than through the king's will, and, being more willing to amuse them than to please the king, she determined to tell an amusing tale...&quot; At the end of the day, Dioneo issues the final salvo: &quot;Now, thank god, they are done with - unless I should add another tale on this dreary topic, which God forbid...&quot;</p>
	<p>The principle of storytelling as a source of pleasure had been established outside the frame of the <em>brigata</em>'s existence by the Narrator in the Proem, in which he dedicates the work to amorous ladies who he hopes will &quot;derive from the delightful things that happen in these tales both pleasure and useful counsel&quot;. The undermining of this principle by Filostrato creates a point within the text in which these frames meet, creating a discord which in part constitutes the crisis of the fourth day. A brief paraphrase of the Narrator's autobiographical portrait and that of Filostrato at the end of Day III suffices to show the antithetical relation between the two: in the Proem the Narrator presents himself as an erstwhile &quot;sick&quot; lover who almost died (not, he is quick to clarify, due to the cruelty of his lady, but rather to the unrestrained nature of his own desire), but whose cure has led him to seek to ease women's amorous pangs out of gratitude. Filostrato offers a self-portrait of a lover who has obeyed all the tenets of love only to be betrayed, whose lovesickness will continue unto death, and demands tales which conform to his own unhappy state. Thus in his &quot;coronation speech&quot;, Filostrato emerges as a mirror image of the Narrator, whose choice of theme reverses the principle of storytelling as pleasurable &quot;cure&quot; upon which the Narrator bases the work, and the <em>brigata</em>&nbsp;their country existence.</p>
	<p>(A.T.) Marcus, Millicent. &quot;Tragedy as Trespass&quot;, <em>An Allegory of Form: Literary Self Consciousness in the</em>&nbsp;Decameron. (Stanford, Calif.: Anma Libri, 1979), p. 48-73; Sherberg, Michael. &quot;The Patriarch's Pleasure and the Frametale crisis: Decameron IV-V.&quot; <em>Romance Quartery</em>&nbsp;38:2 (1991): 227-238.</p>	

<?php
	$last_modified =  filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../footer.php';
?>
