<?php
	$selected = "themes_motifs";
	require '../../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../../">Main</a></li>
	<li><a href="../../">Themes &amp; Motifs</a></li>
	<li><a href="../">Module</a></li>
	<li><a href="index.php">Love</a></li>
	<li>All stories containing Love</li>
</ul>
<h2>All stories containing Love</h2>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0105&expand=day01">The First Day, The Fifth Novell</a> (Fiammetta)</p>
<p>The Lady Marquesse of Montferrat, with a Banquet of Hennes, and divers other gracious speeches beside, repressed the fond love of the King of France. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0110&expand=day01">The First Day, The Tenth Novell</a> (Pampinea)</p>
<p>Master Albert of Bullen, honestly made a Lady to blush, that thought to have done as much to him, because shee perceived him, to be amorously affected towards her. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0203&expand=day02">The Second Day, The Third Novell</a> (Pampinea)</p>
<p>Three young Gentlemen, being Brethren, and having spent all their Lands and possessions vainely, became poore. A Nephew of theirs (falling almost into as desperate a condition) became acquainted with an Abbot, whom he afterward found to be the King of Englands Daughter, and made him her Husband in mariage, recompencing all his Uncles losses, and seating them againe in good estate. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0206&expand=day02">The Second Day, The Sixth Novell</a> (Emilia)</p>
<p>Madame Beritola Caracalla, was found in an Island with two Goates, having lost her two Sonnes, and thence travailed into Lunigiana: where one of her Sonnes became servant to the Lord thereof, and was found somewhat overfamiliar with his Masters daughter, who therefore caused him to be imprisoned. Afterward, when the country of Sicely rebelled against King Charles, the aforesaid Sonne chanced to bee knowne by his Mother, and was married to his Masters daughter. And his Brother being found likewise, they both returned to great estate and credit. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0207&expand=day02">The Second Day, The Seventh Novell</a> (Panfilo)</p>
<p>The Soldan of Babylon sent one of his Daughters, to be joyned in marriage with the King of Cholcos, who by divers accidents (in the space of foure yeeres) happened into the custodie of nine men, and in sundry places. At length, being restored backe to her Father, she went to the saide King of Cholcos, as a Maid, and as at first she was intended to be his wife. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0210&expand=day02">The Second Day, The Tenth Novell</a> (Dioneo)</p>
<p>Pagamino da Monaco, a roving Pyrate on the Seas, carried away the fayre Wife of Signior Ricciardo de Chinzica, who understanding where shee was, went thither; and falling into friendship with Pagamino, demanded his Wife of him; whereto he yeelde, provided, that shee would willing goe away with him. She denied to part thence with her Husband, and Signior Ricciardo dying, she became the wife of Pagamino. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0303&expand=day03">The Third Day, The Third Novell</a> (Filomena)</p>
<p>Under colour of Confession, and of a most pure conscience, a faire yong Gentlewoman, being amourously affected to an honest man, induced a devoute and solemne religious Friar, to advise her in the meanes (without his suspition or perceiving) how to enjoy the benefit of her friend, and bring her desires to their full effect. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0305&expand=day03">The Third Day, The Fifth Novell</a> (Elissa)</p>
<p>Ricciardo surnamed the Magnifico, gave a Horse to Signior Francesco Vergillisi, on condition that he might speake to his wife in his presence; which he did, and she not returning him any answer, made answer to himselfe on her behalfe, and according to his answer, so the effect followed. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0306&expand=day03">The Third Day, The Sixth Novell</a> (Fiammetta)</p>
<p>Ricciardo Minutolo fell in love with the wife of Philippello Fighinolfi, and knowing her to be very jealous of her Husband, gave her to understand, that hee was greatly enamoured of his Wife, and had appointed to meete her privately in a Bathing house, on the next day following: where shee hoping to take him tardie with his close compacted Mistresse, found her selfe to be deceived by the said Ricciardo. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0307&expand=day03">The Third Day, The Seventh Novell</a> (Emilia)</p>
<p>Theobaldo Elisei, having received an unkinde repulse by his beloved, departed from Florence, and returning thither (a long while after) in the habite of a Pilgrime; he spake with her, and made his wrongs knowne unto her. He delivered her Father from the danger of death, because it was proved, that he had slaine Theobaldo: he made peace with his brethren, and in the end, wisely enjoyed his hearts desire. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0309&expand=day03">The Third Day, The Ninth Novell</a> (Neifile)</p>
<p>Juliet of Narbona, cured the King of France of a daungerous Fistula, in recompence whereof, she requested to enjoy as her husband in marriage, Bertrand Count of Roussilion. Hee having married her against his will, as utterly despising her, went to Florence, where hee made love to a young Gentlewoman. Juliet, by a queint and cunning policy, compassed the meanes (insted of his chosen new friend) to lye with her owne husband, by whom shee conceived, and had two Sonnes; which being afterward made knowne unto Count Bertrand, he accepted her into his favour againe, and loved her as his loyall and honourable wife. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0401&expand=day04">The Fourth Day, The First Novell</a> (Fiammetta)</p>
<p>Tancrede, Prince of Salerne, caused the amorous friend of his daughter to bee slaine, and sent her his heart in a cup of Gold: which afterwards she steeped in an impoysoned water, and then drinking it, so dyed. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0403&expand=day04">The Fourth Day, The Third Novell</a> (Lauretta)</p>
<p>Three yong Gentlemen affecting three Sisters, fledde with them into Candie. The eldest of them (through jealousie) becommeth the death of her Lover; The second, by consenting to the Duke of Candies request, is the meanes of saving her life. Afterward, her owne Friend killeth her, and thence flyeth away with the elder Sister. The third couple, are charged with her death, and being committed prisoners, they confesse the fact; and fearing death, by corruption of money they prevaile with their Keepers, escaping from thence to Rhodes, where they dyed in great poverty. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0404&expand=day04">The Fourth Day, The Fourth Novell</a> (Elissa)</p>
<p>Gerbino, contrary to the former plighted faith of his Grand-father, King Gulielmo, fought with a Ship at Sea, belonging to the King of Thunis, to take away his Daughter, who was then in the same Ship. Shee being slaine by them that had the possession of her, he likewise slew them; and afterward had his owne head smitten off. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0405&expand=day04">The Fourth Day, The Fifth Novell</a> (Filomena)</p>
<p>The three Brethren to Isabella, slew a Gentleman that secretly loved her. His ghost appeared to her in her sleepe, and shewed her in what place they had buried his body. She (in silent manner) brought away his head, aid putting it into a pot of earth, such as Flowers, Basile, or other sweete hearbes are usually set in; she watered it (a long while) with her teares. Wherefore her Brethren having intelligence; soone after she dyed, with meere conceite of sorrow. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0406&expand=day04">The Fourth Day, The Sixth Novell</a> (Panfilo)</p>
<p>A beautifull young Virgine, named Andreana, became enamoured of a young Gentleman called Gabriello. In conference together, she declared a dreame of hers to him, and he another of his to her; whereupon Gabriello fell downe sodainly dead in her armes. She, and her Chamber-maide were apprehended, by the Officers belonging to the Seigneury, as they were carrying Gabriello, to lay him before his owne doore. The Potestate offering violence to the Virgin, and she resisting him vertuously: it came to the understanding of her Father, who approved the innocence of his daughter, and compassed her deliverance. But she afterward, being weary of all worldly felicities, entred into Religion, and became a Nun. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0407&expand=day04">The Fourth Day, The Seventh Novell</a> (Emilia)</p>
<p>Faire Simonida affecting Pasquino, and walking with him in a pleasant garden, it fortuned, that Pasquino rubbed his teeth with a leafe of Sage, and immediately fell downe dead. Simonida being brought before the bench of Justice, and charged with the death of Pasquino, she rubbed her teeth likewise with one of the leaves of the same Sage, as declaring what shee saw him do, and thereon she dyed also in the same manner. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0408&expand=day04">The Fourth Day, The Eight Novell</a> (Neifile)</p>
<p>Jeronimo affecting a yong Maiden, named Silvestra, was constrained (by the earnest importunity of his Mother) to take a journey to Paris. At his return home from thence againe, he found his love Silvestra married. By secret meanes, he got entrance into her house, and dyed upon the bed lying by her. Afterward, his body being carried to Church, to receive buriall, she likewise died there instantly upon his coarse. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0409&expand=day04">The Fourth Day, The Ninth Novell</a> (Filostrato)</p>
<p>Messer Guiglielmo of Rossiglione having slaine Messer Guiglielmo Guardastagno, whom hee imagined to love his wife, gave her his heart to eate. Which she knowing afterward, threw her selfe out of an high window to the ground; and being dead, was then buried with her friend. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0410&expand=day04">The Fourth Day, The Tenth Novell</a> (Dioneo)</p>
<p>A physitians wife laide a Lover of her Maides (supposing him to be dead) in a Chest, by reason that he had drunke Water, which usually was given to procure a sleepy entrancing. Two Lombard usurers, stealing the Chest, in hope of a rich booty, carryed it into their owne house, where afterward the man awaking, was apprehended for a Theefe. The Chamber-maide to the Physitians wife, going before the bench of Justice, accuseth her selfe for putting the imagined dead body into the Chest, by which meanes he escapeth hanging. And the theeves which stole away the Chest, were condemned to pay a great summe of money. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0501&expand=day05">The Fifth Day, The First Novell</a> (Panfilo)</p>
<p>Chynon, by falling in Love, became wise, and by force of Armes, winning his faire Lady Iphigenia on the Seas, was afterward imprisoned at Rhodes. Being delivered by anyone named Lysimachus, with him he recovered his Iphigenia againe, and faire Cassandra, even in the middest of their marriage. They fled with them into Candye, where after they had married them, they were called home to their owne dwelling. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0502&expand=day05">The Fifth Day, The Second Novell</a> (Emilia)</p>
<p>Faire Constance of Liparis, fell in love with Martuccio Gomito: and hearing that he was dead, desperately she entred into a Barke, which being transported by the windes to Susa in Barbary, from thence she went to Thunis, where she found him to be living. There she made her selfe knowne to him, and he being in great authority, as a privy Counsellor to the King: he married the saide Constance, and returned richly home with Air, to the Island of Liparis. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0503&expand=day05">The Fifth Day, The Third Novell</a> (Elissa)</p>
<p>Pedro Bocamazzo, escaping away with a yong Damosell which he loved, named Angelina, met with Theeves in his journey. The Damosell flying fearfully into a Forrest, by chance arriveth at a Castle. Pedro being taken by the Theeves, and happening afterward to escape from them; commeth (accidentally) to the same Castle where Angelina was. And marrying her, they then returned home to Rome. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0504&expand=day05">The Fifth Day, The Fourth Novell</a> (Filostrato)</p>
<p>Ricciardo Manardy, was found by Messer Lizio da Valbonna, as he sate fast asleepe at his Daughters Chamber window, having his hand fast in hers, and she sleeping in the same manner. Whereupon, they are joyned together in marriage, and their long loyall love mutually recompenced. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0505&expand=day05">The Fifth Day, The Fifth Novell</a> (Neifile)</p>
<p>Guidotto of Cremona, out of this mortall life, left a Daughter of his, with Jacomino of Pavia. Giovanni di Severino, and Menghino da Minghole, fell both in love with the young Maiden, and fought for her; who being afterward knowne to be the Sister to Giovanni, she was given in mariage to Menghino. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0506&expand=day05">The Fifth Day, The Sixth Novell</a> (Pampinea)</p>
<p>Guion di Procida, being found familiarly conversing with a young Damosell, which he loved; and had beene given (formerly) to Frederigo, King of Sicilie: was bound to a stake, to be consumed with fire. From which h dan ger (neverthelesse) he escaped, being knowne by Don Rogiero de Oria, Lord Admirall of Sicilie, and afterward married the Damosell. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0507&expand=day05">The Fifth Day, The Seventh Novell</a> (Lauretta)</p>
<p>Theodoro falling in love with Violenta, the Daughter to his Master, named Amarigo, and she conceiving with child by him; was condemned to be hanged. As they were leading him to the Gallowes, beating and misusing him all the way: he happened to be knowne of his owne Father, whereupon he was released, and afterward enjoyed Violenta in marriage. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0508&expand=day05">The Fifth Day, The Eight Novell</a> (Filomena)</p>
<p>Anastasio, a Gentleman of the Family of the Honesti, by loving the Daughter to Signior Paulo Traversario, lavishly wasted a great part of his substance, without receiving any love from her againe. By perswasion of some of his kindred and friends, he went to a Countrey dwelling of his, called Chiasso, where he saw a Knight desperately pursue a young Damosell; whom he slew, and afterward gave her to be devoured by his Hounds. Anastasio invited his friends, and hers also whom he so dearely loved, to take part of a dinner with him, who likewise saw the same Damosell so torne in peeces: which his unkind Love perceiving, and fearing least the like ill fortune should happen to her; she accepted Anastasio to be her Husband. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0509&expand=day05">The Fifth Day, The Ninth Novell</a> (Fiammetta)</p>
<p>Frederigo, of the Alberighi Family, loved a Gentlewoman, and was not requited with like love againe. By bountifull expences, and over liberall invitations, he wasted and consumed all his lands and goods, having nothing left him, but a Hawke or Faulcon. His unkinde Mistresse happeneth to come visite him, and he not having any other foode for her dinner; made a dainty dish of his Faulcone for her to feede on. Being conquered by this exceeding kinde courtesie; she changed her former hatred towardes him, accepting him as her Husband in marriage, and made him a man of wealthy possessions. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0510&expand=day05">The Fifth Day, The Tenth Novell</a> (Dioneo)</p>
<p>Pedro di Vinciolo went to sup at a friends house in the City. His wife (in the meane while) had a young man whom shee loved, at supper with Pedro returning home on a sodaine, the young man was hidden under a Coope for Hens. Pedro in excuse of his so soone comming home, declareth, how in the house of Herculano (with whom he should have supt) a friend of his Wives was found, which was the reason of the Suppers breaking off. Pedroes Wife reproving the error of Herculanoes wife, an Asse (by chance) treads on the yong mans fingers that lay hidden under the Hen-coope. Upon his crying out Pedro steppeth thither, sees him, knowes him, and findeth the fallacy of his wife; with whom (nevertbelesse) he groweth to agreement, in regard of some imperfections in himselfe. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0709&expand=day07">The Seventh Day, The Ninth Novell</a> (Panfilo)</p>
<p>Lydia, a Lady of great beauty, birth, and honor, being Wife to Nicostratus, Governour of Argos, falling in love with a Gentleman, named Pyrrhus; was requested by him (as a true testimony of her unfeigned affection) to performe three severall actions of her selfe. She did accomplish them all, and imbraced and kissed Pyrrhus in the presence of Nicostratus; by perswading him, that whatsoever he saw, was meerely false. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0804&expand=day08">The Eigth Day, The Fourth Novell</a> (Emilia)</p>
<p>The Provost belonging to the Cathedrall Church of Fiesola, fell in love with a Gentlewoman, being a widdow, and named Piccarda, who hated him as much as he loved her. He imagining, that he lay with her: by the Gentlewomans Bretheren, and the Byshop under whom he served, was taken in bed with her Mayde, an ugly, foule, deformed Slut. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0807&expand=day08">The Eigth Day, The Seventh Novell</a> (Pampinea)</p>
<p>A young Gentleman being a Scholler, fell in love with a Ladie, named Helena, she being a Widdow, and addicted in affection to another Gentleman. One whole night in cold Winter, she caused the Scholler to expect her comming, in an extreame frost and snow. In revenge whereof, by his imagined Art and skill, he made her to stand naked on the top of a Tower, the space of a whole day, and in the hot moneth of July, to be Sunburnt and bitten with Waspes and Flies. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov0901&expand=day09">The Ninth Day, The First Novell</a> (Filomena)</p>
<p>Madame Francesca, a Widdow of Pistoya, being affected by two Florentine Gentlemen, the one named Rinuccio Palermini, and the other Alessandro Chiarmontesi, and she bearing no good will to eyther of them; ingeniously freed her selfe from both their importunate suites. One of them she caused to lye as dead in a grave, and the other to fetch him from thence: so neither of them accomplishing what they were enjoyned, fayled of obtaining his hoped expectation. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov1004&expand=day10">The Tenth Day, The Fourth Novell</a> (Lauretta)</p>
<p>Signior Gentile de Carisendi, being come from Modena, took a Gentlewoman, named Madam Catharina, forth of a grave, wherin she was buried for dead: which act he did, in regard of his former honest affection to the said Gentlewoman. Madame Catharina remaining there afterward, and delivered of a goodly Sonne: was (by Signior Gentile) delivered to her owne Husband, named Signior Nicoluccio Caccianimico, and the yong infant with her. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov1005&expand=day10">The Tenth Day, The Fifth Novell</a> (Emilia)</p>
<p>Madame Dianora, the Wife of Signior Gilberto, being immodestly affected by Signior Ansaldo, to free her selfe from his tedious importunity, she appointed him to performe (in her judgement) an act of impossibility; namely, to give her a Garden, as plentifully stored with fragrant Flowers in January, as in the flourishing moneth of May. Ansaldo, by meanes of a bond which he made to a Magitian, performed her request. Signior Gilberto, the Ladyes Husband, gave consent, that his Wife should fulfill her promise made to Ansaldo. Who hearing the bountifull mind of her Husband; released her of her promise: And the Magitian likewise discharged Signior Ansaldo, without taking any thing of him. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov1006&expand=day10">The Tenth Day, The Sixth Novell</a> (Fiammetta)</p>
<p>Victiorious King Charles, sirnamed the Aged, and first of that Name, fell in love with a yong Maiden, named Genevera, daughter to an ancient Knight, called Signior Neri degli Uberti. And waxing ashamed of his amorous folly, caused both Genevera, and her fayre Sister Isotta, to be joyned in marriage with two Noble Gentlemen; the one named Signior Maffeo da Palizzi, and the other, Signior Gulielmo della Magna. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov1007&expand=day10">The Tenth Day, The Seventh Novell</a> (Pampinea)</p>
<p>Lisana, the Daughter of a Florentine Apothecary, named Bernardo Puccino, being at Palermo, and seeing Piero, King of Aragon run at the Tilt; fell so affectionately enamored of him, that she languished in an extreame and long sickenesse. By her owne devise, and means of a Song, sung in the hearing of the King: he vouchsafed to visite her, and giving her a kisse, terming himselfe also to bee her Knight for ever after, hee honourably bestowed her in marriage on a young Gentleman, who was called Perdicano, and gave him liberall endowments with her. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov1008&expand=day10">The Tenth Day, The Eight Novell</a> (Filomena)</p>
<p>Sophronia, thinking her selfe to be the maried wife of Gisippus, was (indeed) the wife of Titus Quintus Fulvius, and departed thence with him to Rome. Within a while after, Gisippus also came thither in very poore condition, and thinking that he was despised by Titus, grew weary of his life, and confessed that he had murdred a man, with ful intent to die for the fact. But Titus taking knowledge of him, and desiring to save the life of Gisippus, charged himself to have done the bloody deed. Which the murderer himself (standing then among the multitude) seeing, truly confessed the deed. By meanes whereof, all three were delivered by the Emperor Octavius; and Titus gave his Sister in mariage to Gisippus, giving them also the most part of his goods and inheritances. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov1009&expand=day10">The Tenth Day, The Ninth Novell</a> (Panfilo)</p>
<p>Saladine, the great Soldan of Babylon, in the habite of a Merchant, was honourably received and welcommed, into the house of Signior Thorello d'Istria. Who travelling to the Holy Land, prefixed a certaine time to his Wife, for his returne back to her againe, wherein, if he failed, it was lawfull for her to take another Husband. By clouding himselfe in the disguise of a Faulkner, the Soldan tooke notice of him, and did him many great honours. Afterward, Thorello falling sicke, by Magicall Art, he was conveighed in one night to Pavia, when his Wife was to be married on the morrow: where making himselfe knowne to her, all was disappointed, and shee went home with him to his owne house. </p>
<p><a href="../../../texts/DecShowText.php?lang=eng&myID=nov1010&expand=day10">The Tenth Day, The Tenth Novell</a> (Dioneo)</p>
<p>The Marquesse of Saluzzo, named Gualtiero, being constrained by the importunate solliciting of his Lords, and other inferiour people, to joyne himselfe in marriage; tooke a woman according to his owne liking, called Grizelda, she being the daughter of a poore Countriman, named Janiculo, by whom he had two children, which he pretended to be secretly murdered. Afterward, they being grown to yeres of more stature, and making shew of taking in marriage another wife, more worthy of his high degree and Calling: made a seeming publique liking of his owne daughter, expulsing his wife Grizelda poorely from him. But finding her incomparable patience; more dearely (then before) hee received her into favour againe, brought her home to his owne Pallace, where (with her children) hee caused her and them to be respectively honoured, in despight of all her adverse enemies. </p>

<ul>
	<li>View all stories containing Love</li>
</ul>
<h3>Narrow stories down by:</h3>
<ul class="links">
	<li><a href="happily.php">Love ends happily</a></li>
	<li><a href="rejection.php">Love ends tragically due to rejection</a></li>
	<li><a href="death.php">Love ends tragically due to death</a></li>
</ul>
<ul>
	<li>See also: <a href="../dead/both.php">both lovers die</a></li>
</ul>
<ul class="links">
	<li><a href="society.php">Love is blocked by social rankings</a></li>
	<li><a href="marriage.php">Love is blocked by marriage</a></li>
</ul>
<ul>
	<li>See also: <a href="../sex/adultery.php">adultery</a></li>
</ul>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../../footer.php';
?>
