<?php
	$selected = "arts";
	require '../../header.php';
?>

<ul id="breadcrumbs">
	<li><a href="../../">Main</a></li>
	<li><a href="../">Arts</a></li>
	<li><a href="../visualizing/">Visualizing the Text</a></li>
	<li>Boccaccio, the Scribe</li>
</ul>
<h2>Boccaccio, the Scribe, Boccaccio, the Author, and the Relationship between Word and Image in the Early Editorial History of the <em>Decameron</em>.</h2>
<p>There are 33 extant codices in which scholars recognize the hand of Boccaccio as a scribe: 22 are considered autographs and 11 have marginal notes, marks etc. which suggest they were at one time on his desk or part of his library.  Only three of all these codices are signed (or &quot;subscribed&quot;) by Boccaccio and none has a date. They include three copies of Dante's <em>Comedy</em> and works by major Latin authors as well as miscellanea (<em>Zibaldoni</em>, anthologies or scrapbooks) with excerpts of scholastic or &quot;scientific&quot; treatises and commentaries. As far as the <em>Decameron</em> is concerned, among the hundreds of extant early manuscript copies (Branca), by far the most important is the Hamilton 90 at the Berlin Staatsbibliothek Preussischer Kulturbesitz, recognized by scholars (Vandelli, Branca, de la Mare, Cursi) as an autograph that Boccaccio completed just a few years before his death, most likely in 1370-72. Second in importance for the editorial history of the <em>Decameron</em> is the ms. Ital. 482 of the Bibliothèque Nationale de France, subscribed by the Florentine copyist Giovanni d'Agnolo Capponi. This manuscript is noteworthy also because it contains 18 drawings or illustrations and is believed to have been produced at least a decade earlier than the Hamilton. The latter has no illustrations.</p>
<p>In his recent book, <em>La scrittura e i libri di Giovanni Boccaccio</em> (Viella, 2013), Marco Cursi has persuasively argued that Boccaccio did not limit himself to transcribe but actively designed the format of the <em>Decameron</em> as a book, as shown by the Hamilton ms. After a close comparison of the Hamilton and Capponi codices, focused in particular on paragraph divisions, filigree and colored capital letters as well as the typology of writing, critically analyzed against the backdrop of fourteenth-century conventions (<em>scrittura posata, corsiva, cancelleresca, mercantile, semi-gotica,</em> etc.), Cursi reaches the conclusion that the editorial form of the <em>Decameron</em> evolved since the time it was presumably completed by its author as a book. This has important implications for ascertaining the way Boccaccio himself intended his book to be read, at different stages of his life.</p>
<p>Let's sinthesize Cursi's argument: he provides detailed evidence to suggest that the ms Ital 482 is not by the hand of Boccaccio himself - it is not, in other words, an autograph owned by Capponi, as some scholars have suggested (for these scholars, Rossi in particular, Capponi's subscription would be a sign of of ownership and not authorship). However, Cursi suggests that Capponi's transcription was likely made from a Boccaccio autograph or at least an &quot;antigraph&quot; (a copy or transcript) that had gone through Boccaccio's hands or was given to Capponi by Boccaccio himself. Most interesting are Cursi's conjectures about the presence of illustrations in the Capponi ms. and their absence in the Hamilton autograph. Some scholars (the same who tend to consider it an autograph) have suggested that the author of the drawings in the Capponi ms. could be Boccaccio himself. While excluding this (for reasons that would be interesting to analyze separately and have to do with the imperfect correspondence between some of the images and the text they are meant to illustrate), Cursi nevertheless supports the idea that Capponi was transcribing from a manuscript that Boccaccio himself had planned (or at least approved) to include illustrations. Cursi presents three possibilities: </p>
<p>a) Capponi had on his desk a ms. autographed by Boccaccio, complete with images that he or an unknown miniaturist tried to copy (with a few inconsistencies or misunderstandings as to their exact textual references);<br />
  b) Capponi had on his desk a ms. designed (not autographed) by Boccaccio in which the space for the images was already drafted but the images themselves were not yet included - a kind of editorial proofs for the book to be;<br />
c)  Boccaccio himself provided the ms. without images and guided Capponi to draft the layout and include the images.</p>
<p>In any case, it is plausible to conclude with Cursi that between the end of the 1350s and the beginning of the 1360s (when the Capponi ms. was produced), Boccaccio was designing (if not authoring, at least <em>authorizing</em>) a book-form for the <em>Decameron</em> very different from the one he himself scripted a decade later (the Hamilton ms.). In short, the paratextual and editorial apparatus of the Hamilton codex - its dimensions, the fact that it is written on animal membrane or parchment, the &quot;semi-gothic&quot; script, the ample space on the margins, paragraph divisions, the strategic positioning of capital and colored letters within the text, etc. - is consistent with the format of a scientific treatise and is aimed to promote a vernacular literary text to the dignity of a  Latin scholastic-academic model (hence also the title of the <em>Decameron</em>, a reference to a commentary on <em>Genesis</em>, the <em>Exameron Beati Ambrosii</em>, a copy of which was in Boccaccio's library). The Capponi codex, instead, virtually configures another <em>Decameron</em>, presumably also designed by Boccaccio, the Author: as Cursi writes, &quot;a visualized or at least <em>visualizable</em> book, characterized by a thorough agreement (<em>solidarietà piena</em>) between text and illustration,&quot; a departure from the usual, predictable figuration criteria which were conventional at the time: an implicit re-affirmation of the equal dignity, in the eyes of Boccaccio, and reciprocal inspiration of the art of the word and the art of the image.</p>

<p>(M.R.)  Bibliography: Cursi, Marco. <em>La scrittura e i libri di Giovanni Boccaccio</em>, Rome: Viella, 2013.</p>

<?php
	include 'relatedPages.php';
?>

<?php
	$last_modified = filemtime($_SERVER["SCRIPT_FILENAME"]);
	include '../../footer.php';
?>
